// This is a collection of modules that may be used by HLS synthesized modules generated by Holoso.
// Where reasonable, Holoso may also inject ad-hoc combinational logic directly into the generated module.
// Some of the modules depend on the Kulibin library: https://github.com/Zubax/kulibin
//
// Modules use the in_valid/out_valid pattern to signal data availability.
// Those that have limited throughput provide in_ready/out_ready for stalling.
// The active-high synchronous reset only resets the control path, leaving data path undefined.
// Before the first out_valid is asserted, the values of the outputs are indeterminate (may be X).
//
// Modules named with an underscore are internal implementation details.

`include "holoso_support.vh"

`timescale 1ns/1ps

// ====================================================================================================================
// FLOATING POINT BASIC OPERATORS
//
// Using Zubax Kulibin float -- an IEEE 754-like format with simplifications: no NaN, no subnormals, no negative 0.
// Refer to the Kulibin library for details.
//
// Parameters: WEXP -- exponent bit width, WMAN -- mantissa/significand bit width (incl. hidden bit).
// The total width is WFULL=WEXP+WMAN (the significand MSb is absent but there is also the sign bit, like IEEE 754).
//
// Additional register stages can be introduced to tweak critical path timings vs. pipeline latency using
// dedicated parameters; refer to the Kulibin source for their specific meaning.

// Combinational floating-point sign conditioner operator; to be used at the inputs/outputs of arithmetic operators.
// Sign conditioning is a trivial and/xor single-bit gate enabling free computation of abs/neg.
// Conditional inputs can be tied off to constants, in which case the corresponding circuits are optimized away.
// Function:
//      y =     +x      if op=0
//      y =     -x      if op=1
//      y = +abs(x)     if op=2
//      y = -abs(x)     if op=3
module holoso_fsgnop#(parameter WFULL = 24) (input wire [WFULL-1:0] x, input wire [1:0] op, output wire [WFULL-1:0] y);
    wire   op_abs = op[1];
    wire   op_neg = op[0];
    wire   s_in   = x[WFULL-1];
    wire   s_out  = (s_in & ~op_abs) ^ op_neg;
    assign y      = { s_out, x[WFULL-2:0] };
endmodule

// Floating point adder/subtractor with sign conditioning:  y = sgnop(sgnop(a) + sgnop(b))
// E.g., subtraction: y=a+(-b); negative absolute difference: y=-abs(a-b), magnitude difference: y=abs(a)-abs(b), ...
// The inputs are sampled once at in_valid and are not required to remain stable during operation.
// Register stages: 4+STAGE_INPUT+STAGE_DECODE+STAGE_ALIGN+STAGE_NORMALIZE+STAGE_PACK+STAGE_OUTPUT.
module holoso_fadd#(parameter WEXP = 6, parameter WMAN = 18,
                    parameter STAGE_INPUT = 0, parameter STAGE_DECODE = 0, parameter STAGE_ALIGN = 0,
                    parameter STAGE_NORMALIZE = 0, parameter STAGE_PACK = 0, parameter STAGE_OUTPUT = 0) (
    input  wire clk,
    input  wire rst,
    input  wire                 in_valid,
    input  wire           [1:0] a_sgnop,
    input  wire           [1:0] b_sgnop,
    input  wire           [1:0] y_sgnop,
    input  wire [WEXP+WMAN-1:0] a,
    input  wire [WEXP+WMAN-1:0] b,
    output wire                 out_valid,
    output wire [WEXP+WMAN-1:0] y
);
    localparam WFULL = WEXP + WMAN;
    localparam LATENCY = 4 + STAGE_INPUT + STAGE_DECODE + STAGE_ALIGN + STAGE_NORMALIZE + STAGE_PACK + STAGE_OUTPUT;
    wire [WFULL-1:0] a1;
    wire [WFULL-1:0] b1;
    wire [WFULL-1:0] y1;
    wire       [1:0] y_sgnop_q;
    holoso_fsgnop#(.WFULL(WFULL)) u_sgnop_a (.x(a), .op(a_sgnop), .y(a1));
    holoso_fsgnop#(.WFULL(WFULL)) u_sgnop_b (.x(b), .op(b_sgnop), .y(b1));
    _zkf_pipe#(.W(2), .N(LATENCY)) u_y_sgnop_pipe (.clk(clk), .rst(rst), .in_valid(in_valid), .in(y_sgnop),
                                                   .out_valid(), .out(y_sgnop_q));
    holoso_fsgnop#(.WFULL(WFULL)) u_sgnop_y (.x(y1), .op(y_sgnop_q), .y(y));
    zkf_add#(.WEXP(WEXP), .WMAN(WMAN), .STAGE_INPUT(STAGE_INPUT),
             .STAGE_DECODE(STAGE_DECODE), .STAGE_ALIGN(STAGE_ALIGN), .STAGE_NORMALIZE(STAGE_NORMALIZE),
             .STAGE_PACK(STAGE_PACK), .STAGE_OUTPUT(STAGE_OUTPUT)) u_add (
        .clk(clk), .rst(rst),
        .in_valid(in_valid), .a(a1), .b(b1),
        .out_valid(out_valid), .y(y1)
    );
endmodule

// Floating point multiplier with sign conditioning: y = sgnop(sgnop(a) * sgnop(b))
// The inputs are sampled once at in_valid and are not required to remain stable during operation.
// Caution: STAGE_PRODUCT is almost never a good idea unless WMAN is wider than DSP multiplier input widths.
// Register stages: 1+STAGE_INPUT+STAGE_PRODUCT+STAGE_PACK+STAGE_OUTPUT.
module holoso_fmul#(parameter WEXP = 6, parameter WMAN = 18, parameter STAGE_INPUT = 0,
                    parameter STAGE_PRODUCT = 0, parameter STAGE_PACK = 0, parameter STAGE_OUTPUT = 0) (
    input  wire clk,
    input  wire rst,
    input  wire                 in_valid,
    input  wire           [1:0] a_sgnop,
    input  wire           [1:0] b_sgnop,
    input  wire           [1:0] y_sgnop,
    input  wire [WEXP+WMAN-1:0] a,
    input  wire [WEXP+WMAN-1:0] b,
    output wire                 out_valid,
    output wire [WEXP+WMAN-1:0] y
);
    localparam WFULL = WEXP + WMAN;
    localparam LATENCY = 1 + STAGE_INPUT + STAGE_PRODUCT + STAGE_PACK + STAGE_OUTPUT;
    wire [WFULL-1:0] a1;
    wire [WFULL-1:0] b1;
    wire [WFULL-1:0] y1;
    wire       [1:0] y_sgnop_q;
    holoso_fsgnop#(.WFULL(WFULL)) u_sgnop_a (.x(a), .op(a_sgnop), .y(a1));
    holoso_fsgnop#(.WFULL(WFULL)) u_sgnop_b (.x(b), .op(b_sgnop), .y(b1));
    _zkf_pipe#(.W(2), .N(LATENCY)) u_y_sgnop_pipe (.clk(clk), .rst(rst), .in_valid(in_valid), .in(y_sgnop),
                                                   .out_valid(), .out(y_sgnop_q));
    holoso_fsgnop#(.WFULL(WFULL)) u_sgnop_y (.x(y1), .op(y_sgnop_q), .y(y));
    zkf_mul#(.WEXP(WEXP), .WMAN(WMAN), .STAGE_INPUT(STAGE_INPUT),
             .STAGE_PRODUCT(STAGE_PRODUCT), .STAGE_PACK(STAGE_PACK), .STAGE_OUTPUT(STAGE_OUTPUT)) u_mul (
        .clk(clk), .rst(rst),
        .in_valid(in_valid), .a(a1), .b(b1),
        .out_valid(out_valid), .y(y1)
    );
endmodule

// Constant-power-of-two scaler with sign conditioning:  y = sgnop(sgnop(a) * 2^K)
// K is a signed integer exponent shift; -2^(WEXP-1) < K < 2^(WEXP-1). The scaling is exact.
// The inputs are sampled once at in_valid and are not required to remain stable during operation.
// Register stages: 1+STAGE_INPUT+STAGE_DECODE.
module holoso_fmul_ilog2_const#(parameter WEXP = 6, parameter WMAN = 18, parameter integer K = 0,
                                parameter STAGE_INPUT = 0, parameter STAGE_DECODE = 0) (
    input  wire clk,
    input  wire rst,
    input  wire                 in_valid,
    input  wire           [1:0] a_sgnop,
    input  wire           [1:0] y_sgnop,
    input  wire [WEXP+WMAN-1:0] a,
    output wire                 out_valid,
    output wire [WEXP+WMAN-1:0] y
);
    localparam WFULL = WEXP + WMAN;
    localparam LATENCY = 1 + STAGE_INPUT + STAGE_DECODE;
    wire [WFULL-1:0] a1;
    wire [WFULL-1:0] y1;
    wire       [1:0] y_sgnop_q;
    holoso_fsgnop#(.WFULL(WFULL)) u_sgnop_a (.x(a),  .op(a_sgnop), .y(a1));
    _zkf_pipe#(.W(2), .N(LATENCY)) u_y_sgnop_pipe (.clk(clk), .rst(rst), .in_valid(in_valid), .in(y_sgnop),
                                                   .out_valid(), .out(y_sgnop_q));
    holoso_fsgnop#(.WFULL(WFULL)) u_sgnop_y (.x(y1), .op(y_sgnop_q), .y(y));
    zkf_mul_ilog2_const#(.WEXP(WEXP), .WMAN(WMAN), .K(K),
                         .STAGE_INPUT(STAGE_INPUT), .STAGE_DECODE(STAGE_DECODE)) u_mul_ilog2_const (
        .clk(clk), .rst(rst),
        .in_valid(in_valid), .a(a1),
        .out_valid(out_valid), .y(y1)
    );
endmodule

// Floating point divider with sign conditioning: y = sgnop(sgnop(a) / sgnop(b))
// div0 is asserted alongside out_valid when the divisor is (positive) zero; the value of y is then unspecified.
// The quotient is rounded.
// The inputs are sampled once at in_valid and are not required to remain stable during operation.
// Register stages: 2+STAGE_INPUT+((WMAN+2+((WMAN+2)%2))/2)+STAGE_PACK+STAGE_OUTPUT.
module holoso_fdiv#(parameter WEXP = 6, parameter WMAN = 18,
                    parameter STAGE_INPUT = 0, parameter STAGE_PACK = 0, parameter STAGE_OUTPUT = 0) (
    input  wire clk,
    input  wire rst,
    input  wire                 in_valid,
    input  wire           [1:0] a_sgnop,
    input  wire           [1:0] b_sgnop,
    input  wire           [1:0] y_sgnop,
    input  wire [WEXP+WMAN-1:0] a,
    input  wire [WEXP+WMAN-1:0] b,
    output wire                 out_valid,
    output wire [WEXP+WMAN-1:0] y,
    output wire                 div0
);
    localparam WFULL = WEXP + WMAN;
    localparam LATENCY = 2 + STAGE_INPUT + ((WMAN + 2 + ((WMAN + 2) % 2)) / 2) + STAGE_PACK + STAGE_OUTPUT;
    wire [WFULL-1:0] a1;
    wire [WFULL-1:0] b1;
    wire [WFULL-1:0] y1;
    wire       [1:0] y_sgnop_q;
    holoso_fsgnop#(.WFULL(WFULL)) u_sgnop_a (.x(a),  .op(a_sgnop), .y(a1));
    holoso_fsgnop#(.WFULL(WFULL)) u_sgnop_b (.x(b),  .op(b_sgnop), .y(b1));
    _zkf_pipe#(.W(2), .N(LATENCY)) u_y_sgnop_pipe (.clk(clk), .rst(rst), .in_valid(in_valid), .in(y_sgnop),
                                                   .out_valid(), .out(y_sgnop_q));
    holoso_fsgnop#(.WFULL(WFULL)) u_sgnop_y (.x(y1), .op(y_sgnop_q), .y(y));
    zkf_div#(.WEXP(WEXP), .WMAN(WMAN),
             .STAGE_INPUT(STAGE_INPUT), .STAGE_PACK(STAGE_PACK), .STAGE_OUTPUT(STAGE_OUTPUT)) u_div (
        .clk(clk), .rst(rst),
        .in_valid(in_valid), .a(a1), .b(b1),
        .out_valid(out_valid), .q(y1), .div0(div0)
    );
endmodule

// Combinational saturator: replaces infinity with the largest finite value of the same sign; finite pass through.
module holoso_fsaturate#(parameter WEXP = 6, parameter WMAN = 18) (
    input  wire [WEXP+WMAN-1:0] x,
    output wire [WEXP+WMAN-1:0] y
);
    zkf_saturate#(.WEXP(WEXP), .WMAN(WMAN)) u_saturate (.x(x), .y(y));
endmodule

// Floating point min/max sorter with sign conditioning on inputs and outputs:
//      min = sgnop(min(sgnop(a), sgnop(b)))
//      max = sgnop(max(sgnop(a), sgnop(b)))
// Useful for e.g. sort-by-absolute-value or producing sign-flipped extrema.
// Register stages: 1.
module holoso_fsort#(parameter WEXP = 6, parameter WMAN = 18) (
    input  wire clk,
    input  wire rst,
    input  wire                 in_valid,
    input  wire           [1:0] a_sgnop,
    input  wire           [1:0] b_sgnop,
    input  wire           [1:0] min_sgnop,
    input  wire           [1:0] max_sgnop,
    input  wire [WEXP+WMAN-1:0] a,
    input  wire [WEXP+WMAN-1:0] b,
    output wire                 out_valid,
    output wire [WEXP+WMAN-1:0] min,
    output wire [WEXP+WMAN-1:0] max
);
    localparam WFULL = WEXP + WMAN;
    localparam LATENCY = 1;
    wire [WFULL-1:0] a1;
    wire [WFULL-1:0] b1;
    wire [WFULL-1:0] min1;
    wire [WFULL-1:0] max1;
    wire       [3:0] out_sgnop_q;
    wire       [1:0] min_sgnop_q = out_sgnop_q[1:0];
    wire       [1:0] max_sgnop_q = out_sgnop_q[3:2];
    holoso_fsgnop#(.WFULL(WFULL)) u_sgnop_a   (.x(a),    .op(a_sgnop),   .y(a1));
    holoso_fsgnop#(.WFULL(WFULL)) u_sgnop_b   (.x(b),    .op(b_sgnop),   .y(b1));
    _zkf_pipe#(.W(4), .N(LATENCY)) u_out_sgnop_pipe (.clk(clk), .rst(rst), .in_valid(in_valid),
                                                      .in({max_sgnop, min_sgnop}), .out_valid(), .out(out_sgnop_q));
    holoso_fsgnop#(.WFULL(WFULL)) u_sgnop_min (.x(min1), .op(min_sgnop_q), .y(min));
    holoso_fsgnop#(.WFULL(WFULL)) u_sgnop_max (.x(max1), .op(max_sgnop_q), .y(max));
    zkf_sort#(.WEXP(WEXP), .WMAN(WMAN)) u_sort (.clk(clk), .rst(rst),
                                                .in_valid(in_valid), .a(a1), .b(b1),
                                                .out_valid(out_valid), .min(min1), .max(max1));
endmodule

// Floating point comparator with sign conditioning on inputs only:
//      (a_gt_b, a_eq_b, a_lt_b) = compare(sgnop(a), sgnop(b))
// Outputs are mutually-exclusive one-hot flags.
// Register stages: 1
module holoso_fcmp#(parameter WEXP = 6, parameter WMAN = 18) (
    input  wire clk,
    input  wire rst,
    input  wire                 in_valid,
    input  wire           [1:0] a_sgnop,
    input  wire           [1:0] b_sgnop,
    input  wire [WEXP+WMAN-1:0] a,
    input  wire [WEXP+WMAN-1:0] b,
    output wire                 out_valid,
    output wire                 a_gt_b,
    output wire                 a_eq_b,
    output wire                 a_lt_b
);
    localparam WFULL = WEXP + WMAN;
    wire [WFULL-1:0] a1;
    wire [WFULL-1:0] b1;
    holoso_fsgnop#(.WFULL(WFULL)) u_sgnop_a (.x(a), .op(a_sgnop), .y(a1));
    holoso_fsgnop#(.WFULL(WFULL)) u_sgnop_b (.x(b), .op(b_sgnop), .y(b1));
    zkf_cmp#(.WEXP(WEXP), .WMAN(WMAN)) u_cmp (.clk(clk), .rst(rst),
                                              .in_valid(in_valid), .a(a1), .b(b1),
                                              .out_valid(out_valid),
                                              .a_gt_b(a_gt_b), .a_eq_b(a_eq_b), .a_lt_b(a_lt_b));
endmodule

// Combinational predicate: y=1 iff x is finite (i.e., x is not an infinity).
module holoso_fisfinite#(parameter WEXP = 6, parameter WMAN = 18) (input  wire [WEXP+WMAN-1:0] x, output wire y);
    zkf_is_finite#(.WEXP(WEXP), .WMAN(WMAN)) u_is_finite (.x(x), .y(y));
endmodule

// Combinational mapping from float to boolean: a zero or a subnormal (if supported) float is false, otherwise true.
// E.g., if IEEE 754 binary32 is used (with subnormals), values with magnitude under ~1e-38 are mapped to falsity.
module holoso_ftobool#(parameter WEXP = 6, parameter WMAN = 18) (input wire [WEXP+WMAN-1:0] x, output wire y);
    assign y = |x[WEXP+WMAN-2:WMAN-1];  // zero if the exponent is zero; assume no subnormals or subnormals~0
endmodule

// Combinational mapping from boolean to float: falsity is zero, truth is one.
module holoso_ffrombool#(parameter WEXP = 6, parameter WMAN = 18) (input wire x, output wire [WEXP+WMAN-1:0] y);
    // ZKF 1.0 is sign 0, biased exponent BIAS = 2^(WEXP-1)-1, fraction 0.
    localparam [WEXP+WMAN-1:0] ONE = (((1 << (WEXP-1)) - 1) << (WMAN-1));
    assign y = x ? ONE : {(WEXP+WMAN){1'b0}};
endmodule
