// Generated by Holoso v<VERSION> <https://holoso.digital>.
// This file is generated output and is unencumbered: no copyright is claimed over it and no license terms apply.
// You may use, modify, and redistribute it freely, in open-source or proprietary designs, without restrictions.

`timescale 1ns/1ps

// Float format: exponent 8 bits, significand 36 bits, total 44 bits.
module cordic_sincos (
    // CONTROL PORTS
    // Clock/reset and ready/valid handshake for one scheduled invocation.
    input  wire clk,
    input  wire rst,
    input  wire in_valid,
    output wire in_ready,
    output wire out_valid,
    input  wire out_ready,
    // INPUT PORTS
    // Latched when in_valid && in_ready.
    input  wire [43:0] in_theta,
    // OUTPUT/STATE PORTS
    // Valid when out_valid is pulsed. Publicly visible states are included here.
    output wire [43:0] out_0,
    output wire [43:0] out_1,
    // DIAGNOSTIC PORTS
    // Runtime diagnostics available while the module is running.
    output wire [6:0] err_pc
);

localparam           WEXP      =   8;  // Float exponent bits fixed by the static schedule
localparam           WMAN      =  36;  // Float mantissa bits fixed by the static schedule
localparam           W         = WEXP + WMAN;
localparam           NREG      =   7;
localparam           CYCW      =   7;  // err_pc width: enough for any executing step (0..present)
localparam           PCW       =   7;  // fetch-PC width: counts to LASTPC (execution lags the fetch by FETCH_LAG)
localparam           FETCH_LAG =   2;  // executing step = pc - FETCH_LAG (3-stage control fetch)
localparam [PCW-1:0] PRESENT   = 102;  // executing step on which the outputs are valid in the array
localparam [PCW-1:0] LASTPC    = 104;  // = PRESENT + FETCH_LAG; out_valid asserts here
localparam           UCW       =  44;  // microcode word width after lifting out constant control fields
localparam           NBREG     =   1;
// pc: 0 = idle/accept, present at executing step PRESENT; out_valid at pc==LASTPC (fetch leads execution).

// BEGIN holoso_support_inline.vh: the file is spliced into each generated module.

// Arithmetic shift by a constant. Positive shamt shifts left. For variable shamt use holoso_ashift.
function signed [W-1:0] holoso_ashiftc;
    input signed [W-1:0] x;
    input signed [W-1:0] shamt;
    reg signed [W:0] shamt_ext;
    reg [$clog2(W)-1:0] shamt_narrow;
    reg signed [W-1:0] shifted_left;
    reg signed [W-1:0] shifted_right;
    begin
        shamt_ext = {shamt[W-1], shamt};
        shamt_narrow = shamt[$clog2(W)-1:0];
        shifted_left = x << shamt_narrow;
        shifted_right = x >>> -shamt_narrow;
        if (shamt_ext >= W) begin
            holoso_ashiftc = {W{1'b0}};
        end else if (shamt_ext <= -W) begin
            holoso_ashiftc = {W{x[W-1]}};
        end else if (shamt[W-1]) begin
            holoso_ashiftc = shifted_right;
        end else begin
            holoso_ashiftc = shifted_left;
        end
    end
endfunction

// Combinational mapping from float to boolean: a zero or a subnormal (if supported) float is false, otherwise true.
// E.g., if IEEE 754 binary32 is used (with subnormals), values with magnitude under ~1e-38 are mapped to falsity.
function holoso_ftobool;
    input [W-1:0] x;
    holoso_ftobool = |x[W-2:WMAN-1];
endfunction

// Combinational mapping from boolean to float: falsity is zero, truth is one.
function [W-1:0] holoso_ffrombool;
    input b;
    holoso_ffrombool = b ? {2'b00, {(WEXP - 1) {1'b1}}, {(WMAN - 1) {1'b0}}} : {W{1'b0}};
endfunction

// Combinational predicate: y=1 iff x is finite (i.e., x is not an infinity).
function holoso_fisfinite;
    input [W-1:0] x;
    holoso_fisfinite = ~&x[W-2:WMAN-1];
endfunction

function holoso_fisposinf;
    input [W-1:0] x;
    holoso_fisposinf = ~holoso_fisfinite(x) & ~x[W-1];
endfunction

function holoso_fisneginf;
    input [W-1:0] x;
    holoso_fisneginf = ~holoso_fisfinite(x) & x[W-1];
endfunction

// Combinational saturator: replaces infinity with the largest finite value of the same sign; finite pass through.
function [W-1:0] holoso_fsaturate;
    input [W-1:0] x;
    holoso_fsaturate = (&x[W-2:WMAN-1]) ? {x[W-1], {(WEXP - 1) {1'b1}}, 1'b0, {(WMAN - 1) {1'b1}}} : x;
endfunction

// Combinational floating-point sign conditioner (absolute first, then optional negate): op[0]=negate, op[1]=absolute.
//      op=0: +x        op=1: -x        op=2: +|x|      op=3: -|x|
function [W-1:0] holoso_fsgnop;
    input [W-1:0] x;
    input [1:0]   op;
    holoso_fsgnop = {(x[W-1] & ~op[1]) ^ op[0], x[W-2:0]};
endfunction

// END of holoso_support_inline.vh

reg  [PCW-1:0]  pc;            // fetch program counter; the executing step lags it by FETCH_LAG
reg  [PCW-1:0]  next_pc;       // combinational next-state presented to the ROM each cycle
reg  [PCW-1:0]  ucode_addr_q;  // PC latch: splits pc -> next_pc -> ROM address for the case read
reg  [CYCW-1:0] err_pc_q;
wire            err;           // an operator error is detected on the current step

reg                 transacting_in;                           // per-branch tag: this pc's word is a live step
reg [FETCH_LAG-1:0] transacting_q;                            // delays the tag FETCH_LAG onto executing word
wire                transacting = transacting_q[FETCH_LAG-1]; // gates the executing word's effects

reg  [W-1:0] regs  [0:NREG-1];   // read-first: a write is visible next step
reg          bregs [0:NBREG-1];

reg  [W-1:0] s_fcmp_63b877a8_0_a;
reg  [W-1:0] s_fcmp_63b877a8_0_b;
wire         s_fcmp_63b877a8_0_y0;
reg  [W-1:0] s_fadd_9eba50d4_0_a;
reg  [W-1:0] s_fadd_9eba50d4_0_b;
wire [W-1:0] s_fadd_9eba50d4_0_y0;
reg  [W-1:0] s_fmul_ilog2_const_98e5699d_0_a;
wire [W-1:0] s_fmul_ilog2_const_98e5699d_0_y0;
reg  [W-1:0] s_fmul_ilog2_const_b971b71f_0_a;
wire [W-1:0] s_fmul_ilog2_const_b971b71f_0_y0;
reg  [W-1:0] s_fmul_ilog2_const_91771f93_0_a;
wire [W-1:0] s_fmul_ilog2_const_91771f93_0_y0;
reg  [W-1:0] s_fmul_ilog2_const_72d9b6c9_0_a;
wire [W-1:0] s_fmul_ilog2_const_72d9b6c9_0_y0;
reg  [W-1:0] s_fmul_ilog2_const_0436199d_0_a;
wire [W-1:0] s_fmul_ilog2_const_0436199d_0_y0;
reg  [W-1:0] s_fmul_ilog2_const_3fcbcfed_0_a;
wire [W-1:0] s_fmul_ilog2_const_3fcbcfed_0_y0;
reg  [W-1:0] s_fmul_ilog2_const_9afe18ac_0_a;
wire [W-1:0] s_fmul_ilog2_const_9afe18ac_0_y0;
reg  [W-1:0] s_fmul_ilog2_const_1ee6091d_0_a;
wire [W-1:0] s_fmul_ilog2_const_1ee6091d_0_y0;
reg  [W-1:0] s_fmul_ilog2_const_c32f4dd0_0_a;
wire [W-1:0] s_fmul_ilog2_const_c32f4dd0_0_y0;
reg  [W-1:0] s_fmul_ilog2_const_640a8f67_0_a;
wire [W-1:0] s_fmul_ilog2_const_640a8f67_0_y0;
reg  [W-1:0] s_fmul_ilog2_const_03d3dd98_0_a;
wire [W-1:0] s_fmul_ilog2_const_03d3dd98_0_y0;

wire [W-1:0] const_0 = 44'h3f490fdaa22;  // 0.7853981633974483
wire [W-1:0] const_1 = 44'h3f1b74ee0fe;  // 0.607252959138945
wire [W-1:0] const_2 = 44'h3e9b74ee0fe;  // 0.3036264795694725
wire [W-1:0] const_3 = 44'h3eed63382b1;  // 0.4636476090008061
wire [W-1:0] const_4 = 44'h3e7adbafc96;  // 0.24497866312686414
wire [W-1:0] const_5 = 44'h3dfeadd4d56;  // 0.12435499454676144
wire [W-1:0] const_6 = 44'h3d7faaddb96;  // 0.06241880999595735
wire [W-1:0] const_7 = 44'h3cffeaaddd5;  // 0.031239833430268277
wire [W-1:0] const_8 = 44'h3c7ffaaadde;  // 0.015623728620476831
wire [W-1:0] const_9 = 44'h3bfffeaaade;  // 0.007812341060101111
wire [W-1:0] const_10 = 44'h3b7fffaaaae;  // 0.0039062301319669718
wire [W-1:0] const_11 = 44'h3affffeaaab;  // 0.0019531225164788188
wire [W-1:0] const_12 = 44'h3a7ffffaaab;  // 0.0009765621895593195
wire [W-1:0] const_13 = 44'h00000000000;  // 0.0

// Microcode VLIW ROM.
reg [UCW-1:0] ucode_q;     // 2nd fetch stage
reg [UCW-1:0] ucode_word;  // 3rd fetch stage
// Microcode word field map:
//   [0]      uc_issue_fcmp_63b877a8_0
//   [1]      uc_fcmp_63b877a8_0_brd
//   [2]      uc_issue_fadd_9eba50d4_0
//   [4:3]    uc_fadd_9eba50d4_0_ard
//   [6:5]    uc_fadd_9eba50d4_0_bsgn
//   [10:7]   uc_fadd_9eba50d4_0_brd
//   [11]     uc_issue_fmul_ilog2_const_98e5699d_0
//   [12]     uc_issue_fmul_ilog2_const_b971b71f_0
//   [13]     uc_fmul_ilog2_const_b971b71f_0_ard
//   [14]     uc_issue_fmul_ilog2_const_91771f93_0
//   [15]     uc_fmul_ilog2_const_91771f93_0_ard
//   [16]     uc_issue_fmul_ilog2_const_72d9b6c9_0
//   [17]     uc_fmul_ilog2_const_72d9b6c9_0_ard
//   [18]     uc_issue_fmul_ilog2_const_0436199d_0
//   [19]     uc_fmul_ilog2_const_0436199d_0_ard
//   [20]     uc_issue_fmul_ilog2_const_3fcbcfed_0
//   [21]     uc_fmul_ilog2_const_3fcbcfed_0_ard
//   [22]     uc_issue_fmul_ilog2_const_9afe18ac_0
//   [23]     uc_fmul_ilog2_const_9afe18ac_0_ard
//   [24]     uc_issue_fmul_ilog2_const_1ee6091d_0
//   [25]     uc_fmul_ilog2_const_1ee6091d_0_ard
//   [26]     uc_issue_fmul_ilog2_const_c32f4dd0_0
//   [27]     uc_fmul_ilog2_const_c32f4dd0_0_ard
//   [28]     uc_issue_fmul_ilog2_const_640a8f67_0
//   [29]     uc_fmul_ilog2_const_640a8f67_0_ard
//   [30]     uc_issue_fmul_ilog2_const_03d3dd98_0
//   [31]     uc_fmul_ilog2_const_03d3dd98_0_ard
//   [32]     uc_op_b0
//   [33]     uc_op_r1
//   [34]     uc_op_r3
//   [38:35]  uc_op_r2
//   [40:39]  uc_op_r0
//   [41]     uc_op_r4
//   [42]     uc_op_r5
//   [43]     uc_op_r6
(* rom_style = "block", syn_romstyle = "EBR" *)
always @(posedge clk)
    case (ucode_addr_q)
        0: ucode_q <= 44'h000000000a5;  // issue r1=r0+-c0, ~b0=cmp(c13,r0)
        1: ucode_q <= 44'h00100000084;  // issue r3=r0+c0; commit b0
        2: ucode_q <= 44'h08000000000;  // land r0=b0?c1:-c1
        3: ucode_q <= 44'h00000000904;  // issue r1=r0+c2, r2=r0×2^-1
        4: ucode_q <= 44'h00a00000124;  // issue r3=r0+-c2; commit r1, r2
        5: ucode_q <= 44'h00400000034;  // issue r1=c1+-r2; commit r3
        6: ucode_q <= 44'h10000000014;  // issue r3=c1+r2; land r0=b0?r1:r3
        7: ucode_q <= 44'h002000001a5;  // issue r1=r0+-c3, ~b0=cmp(c13,r0); commit r1
        8: ucode_q <= 44'h00500000184;  // issue r3=r0+c3; commit r3, b0
        9: ucode_q <= 44'h10200000000;  // commit r1; land r0=b0?r1:r3
        10: ucode_q <= 44'h00400001000;  // issue r2=r0×2^-2; commit r3
        11: ucode_q <= 44'h21200000000;  // commit r1, r2; land r4=b0?r1:r3
        12: ucode_q <= 44'h0040000302c;  // issue r1=r4+-r2, r2=r4×2^-2; commit r3
        13: ucode_q <= 44'h2100000000c;  // issue r3=r4+r2; commit r2; land r4=b0?r1:r3
        14: ucode_q <= 44'h00000000007;  // issue r1=r0+r2, ~b0=cmp(c13,r4)
        15: ucode_q <= 44'h00100000024;  // issue r3=r0+-r2; commit b0
        16: ucode_q <= 44'h0020000022c;  // issue r1=r4+-c4; commit r1
        17: ucode_q <= 44'h0040000020c;  // issue r3=r4+c4; commit r3
        18: ucode_q <= 44'h10200000000;  // commit r1; land r0=b0?r1:r3
        19: ucode_q <= 44'h00400004000;  // issue r2=r0×2^-3; commit r3
        20: ucode_q <= 44'h21a00000000;  // commit r1, r2; land r4=b0?r1:r3
        21: ucode_q <= 44'h0040000c00c;  // issue r1=r4+r2, r2=r4×2^-3; commit r3
        22: ucode_q <= 44'h2180000002c;  // issue r3=r4+-r2; commit r2; land r4=b0?r1:r3
        23: ucode_q <= 44'h00000000027;  // issue r1=r0+-r2, ~b0=cmp(c13,r4)
        24: ucode_q <= 44'h00100000004;  // issue r3=r0+r2; commit b0
        25: ucode_q <= 44'h002000002ac;  // issue r1=r4+-c5; commit r1
        26: ucode_q <= 44'h0040000028c;  // issue r3=r4+c5; commit r3
        27: ucode_q <= 44'h10200000000;  // commit r1; land r0=b0?r1:r3
        28: ucode_q <= 44'h00400010000;  // issue r2=r0×2^-4; commit r3
        29: ucode_q <= 44'h22200000000;  // commit r1, r2; land r4=b0?r1:r3
        30: ucode_q <= 44'h0040003002c;  // issue r1=r4+-r2, r2=r4×2^-4; commit r3
        31: ucode_q <= 44'h2200000000c;  // issue r3=r4+r2; commit r2; land r4=b0?r1:r3
        32: ucode_q <= 44'h00000000007;  // issue r1=r0+r2, ~b0=cmp(c13,r4)
        33: ucode_q <= 44'h00100000024;  // issue r3=r0+-r2; commit b0
        34: ucode_q <= 44'h0020000032c;  // issue r1=r4+-c6; commit r1
        35: ucode_q <= 44'h0040000030c;  // issue r3=r4+c6; commit r3
        36: ucode_q <= 44'h10200000000;  // commit r1; land r0=b0?r1:r3
        37: ucode_q <= 44'h00400040000;  // issue r2=r0×2^-5; commit r3
        38: ucode_q <= 44'h22a00000000;  // commit r1, r2; land r4=b0?r1:r3
        39: ucode_q <= 44'h004000c000c;  // issue r1=r4+r2, r2=r4×2^-5; commit r3
        40: ucode_q <= 44'h2280000002c;  // issue r3=r4+-r2; commit r2; land r4=b0?r1:r3
        41: ucode_q <= 44'h00000000027;  // issue r1=r0+-r2, ~b0=cmp(c13,r4)
        42: ucode_q <= 44'h00100000004;  // issue r3=r0+r2; commit b0
        43: ucode_q <= 44'h002000003ac;  // issue r1=r4+-c7; commit r1
        44: ucode_q <= 44'h0040000038c;  // issue r3=r4+c7; commit r3
        45: ucode_q <= 44'h10200000000;  // commit r1; land r0=b0?r1:r3
        46: ucode_q <= 44'h00400100000;  // issue r2=r0×2^-6; commit r3
        47: ucode_q <= 44'h23200000000;  // commit r1, r2; land r4=b0?r1:r3
        48: ucode_q <= 44'h0040030002c;  // issue r1=r4+-r2, r2=r4×2^-6; commit r3
        49: ucode_q <= 44'h2300000000c;  // issue r3=r4+r2; commit r2; land r4=b0?r1:r3
        50: ucode_q <= 44'h00000000007;  // issue r1=r0+r2, ~b0=cmp(c13,r4)
        51: ucode_q <= 44'h00100000024;  // issue r3=r0+-r2; commit b0
        52: ucode_q <= 44'h0020000042c;  // issue r1=r4+-c8; commit r1
        53: ucode_q <= 44'h0040000040c;  // issue r3=r4+c8; commit r3
        54: ucode_q <= 44'h10200000000;  // commit r1; land r0=b0?r1:r3
        55: ucode_q <= 44'h00400400000;  // issue r2=r0×2^-7; commit r3
        56: ucode_q <= 44'h23a00000000;  // commit r1, r2; land r4=b0?r1:r3
        57: ucode_q <= 44'h00400c0000c;  // issue r1=r4+r2, r2=r4×2^-7; commit r3
        58: ucode_q <= 44'h2380000002c;  // issue r3=r4+-r2; commit r2; land r4=b0?r1:r3
        59: ucode_q <= 44'h00000000027;  // issue r1=r0+-r2, ~b0=cmp(c13,r4)
        60: ucode_q <= 44'h00100000004;  // issue r3=r0+r2; commit b0
        61: ucode_q <= 44'h002000004ac;  // issue r1=r4+-c9; commit r1
        62: ucode_q <= 44'h0040000048c;  // issue r3=r4+c9; commit r3
        63: ucode_q <= 44'h10200000000;  // commit r1; land r0=b0?r1:r3
        64: ucode_q <= 44'h00401000000;  // issue r2=r0×2^-8; commit r3
        65: ucode_q <= 44'h24200000000;  // commit r1, r2; land r4=b0?r1:r3
        66: ucode_q <= 44'h0040300002c;  // issue r1=r4+-r2, r2=r4×2^-8; commit r3
        67: ucode_q <= 44'h2400000000c;  // issue r3=r4+r2; commit r2; land r4=b0?r1:r3
        68: ucode_q <= 44'h00000000007;  // issue r1=r0+r2, ~b0=cmp(c13,r4)
        69: ucode_q <= 44'h00100000024;  // issue r3=r0+-r2; commit b0
        70: ucode_q <= 44'h0020000052c;  // issue r1=r4+-c10; commit r1
        71: ucode_q <= 44'h0040000050c;  // issue r3=r4+c10; commit r3
        72: ucode_q <= 44'h10200000000;  // commit r1; land r0=b0?r1:r3
        73: ucode_q <= 44'h00404000000;  // issue r2=r0×2^-9; commit r3
        74: ucode_q <= 44'h24a00000000;  // commit r1, r2; land r4=b0?r1:r3
        75: ucode_q <= 44'h0040c00000c;  // issue r1=r4+r2, r2=r4×2^-9; commit r3
        76: ucode_q <= 44'h2480000002c;  // issue r3=r4+-r2; commit r2; land r4=b0?r1:r3
        77: ucode_q <= 44'h00000000027;  // issue r1=r0+-r2, ~b0=cmp(c13,r4)
        78: ucode_q <= 44'h00100000004;  // issue r3=r0+r2; commit b0
        79: ucode_q <= 44'h002000005ac;  // issue r1=r4+-c11; commit r1
        80: ucode_q <= 44'h0040000058c;  // issue r3=r4+c11; commit r3
        81: ucode_q <= 44'h10200000000;  // commit r1; land r0=b0?r1:r3
        82: ucode_q <= 44'h00410000000;  // issue r2=r0×2^-10; commit r3
        83: ucode_q <= 44'h25200000000;  // commit r1, r2; land r4=b0?r1:r3
        84: ucode_q <= 44'h0043000002c;  // issue r1=r4+-r2, r2=r4×2^-10; commit r3
        85: ucode_q <= 44'h2500000000c;  // issue r3=r4+r2; commit r2; land r4=b0?r1:r3
        86: ucode_q <= 44'h00000000007;  // issue r1=r0+r2, ~b0=cmp(c13,r4)
        87: ucode_q <= 44'h00100000024;  // issue r3=r0+-r2; commit b0
        88: ucode_q <= 44'h0020000062c;  // issue r1=r4+-c12; commit r1
        89: ucode_q <= 44'h0040000060c;  // issue r3=r4+c12; commit r3
        90: ucode_q <= 44'h10200000000;  // commit r1; land r0=b0?r1:r3
        91: ucode_q <= 44'h00440000000;  // issue r2=r0×2^-11; commit r3
        92: ucode_q <= 44'h25a00000000;  // commit r1, r2; land r4=b0?r1:r3
        93: ucode_q <= 44'h004c000000c;  // issue r1=r4+r2, r2=r4×2^-11; commit r3
        94: ucode_q <= 44'h2580000002c;  // issue r3=r4+-r2; commit r2; land r4=b0?r1:r3
        95: ucode_q <= 44'h00000000027;  // issue r1=r0+-r2, ~b0=cmp(c13,r4)
        96: ucode_q <= 44'h00100000004;  // issue r3=r0+r2; commit b0
        97: ucode_q <= 44'h00200000000;  // commit r1
        98: ucode_q <= 44'h00400000000;  // commit r3
        99: ucode_q <= 44'h40200000000;  // commit r1; land r5=b0?r1:r3
        100: ucode_q <= 44'h00400000000;  // commit r3
        101: ucode_q <= 44'h80000000000;  // land r6=b0?r1:r3
        102: ucode_q <= 44'h00000000000;
        103: ucode_q <= 44'h00000000000;
        104: ucode_q <= 44'h00000000000;
        default: ucode_q <= 44'h0;  // unreached (PC bounded to LASTPC); NOP fill
    endcase

// Decoded control fields. A field constant across the whole program is driven by a constant net (so synthesis prunes
// the logic it feeds); a varying field is a slice of the instruction word. The effect-trigger fields -- the ``gated``
// ones (operator issue strobes and per-register write opcodes) -- are ANDed with `transacting` HERE, so a held
// ucode[0] dwell, a fill bubble, or a stale pre-reset word decodes to 0 (NOP): no issue and every register holds.
// The AND wraps the constant branch too, so the gate stays unconditional even if a trigger ever folds to a constant.
wire        uc_issue_fcmp_63b877a8_0 = transacting & ucode_word[0 +: 1];
wire [ 1:0] uc_fcmp_63b877a8_0_asgn = 2'd0;
wire [ 1:0] uc_fcmp_63b877a8_0_bsgn = 2'd0;
wire        uc_fcmp_63b877a8_0_brd = ucode_word[1 +: 1];
wire        uc_issue_fadd_9eba50d4_0 = transacting & ucode_word[2 +: 1];
wire [ 1:0] uc_fadd_9eba50d4_0_asgn = 2'd0;
wire [ 1:0] uc_fadd_9eba50d4_0_ard = ucode_word[3 +: 2];
wire [ 1:0] uc_fadd_9eba50d4_0_bsgn = ucode_word[5 +: 2];
wire [ 3:0] uc_fadd_9eba50d4_0_brd = ucode_word[7 +: 4];
wire [ 1:0] uc_fadd_9eba50d4_0_y0sgn = 2'd0;
wire        uc_issue_fmul_ilog2_const_98e5699d_0 = transacting & ucode_word[11 +: 1];
wire [ 1:0] uc_fmul_ilog2_const_98e5699d_0_asgn = 2'd0;
wire [ 1:0] uc_fmul_ilog2_const_98e5699d_0_y0sgn = 2'd0;
wire        uc_issue_fmul_ilog2_const_b971b71f_0 = transacting & ucode_word[12 +: 1];
wire [ 1:0] uc_fmul_ilog2_const_b971b71f_0_asgn = 2'd0;
wire        uc_fmul_ilog2_const_b971b71f_0_ard = ucode_word[13 +: 1];
wire [ 1:0] uc_fmul_ilog2_const_b971b71f_0_y0sgn = 2'd0;
wire        uc_issue_fmul_ilog2_const_91771f93_0 = transacting & ucode_word[14 +: 1];
wire [ 1:0] uc_fmul_ilog2_const_91771f93_0_asgn = 2'd0;
wire        uc_fmul_ilog2_const_91771f93_0_ard = ucode_word[15 +: 1];
wire [ 1:0] uc_fmul_ilog2_const_91771f93_0_y0sgn = 2'd0;
wire        uc_issue_fmul_ilog2_const_72d9b6c9_0 = transacting & ucode_word[16 +: 1];
wire [ 1:0] uc_fmul_ilog2_const_72d9b6c9_0_asgn = 2'd0;
wire        uc_fmul_ilog2_const_72d9b6c9_0_ard = ucode_word[17 +: 1];
wire [ 1:0] uc_fmul_ilog2_const_72d9b6c9_0_y0sgn = 2'd0;
wire        uc_issue_fmul_ilog2_const_0436199d_0 = transacting & ucode_word[18 +: 1];
wire [ 1:0] uc_fmul_ilog2_const_0436199d_0_asgn = 2'd0;
wire        uc_fmul_ilog2_const_0436199d_0_ard = ucode_word[19 +: 1];
wire [ 1:0] uc_fmul_ilog2_const_0436199d_0_y0sgn = 2'd0;
wire        uc_issue_fmul_ilog2_const_3fcbcfed_0 = transacting & ucode_word[20 +: 1];
wire [ 1:0] uc_fmul_ilog2_const_3fcbcfed_0_asgn = 2'd0;
wire        uc_fmul_ilog2_const_3fcbcfed_0_ard = ucode_word[21 +: 1];
wire [ 1:0] uc_fmul_ilog2_const_3fcbcfed_0_y0sgn = 2'd0;
wire        uc_issue_fmul_ilog2_const_9afe18ac_0 = transacting & ucode_word[22 +: 1];
wire [ 1:0] uc_fmul_ilog2_const_9afe18ac_0_asgn = 2'd0;
wire        uc_fmul_ilog2_const_9afe18ac_0_ard = ucode_word[23 +: 1];
wire [ 1:0] uc_fmul_ilog2_const_9afe18ac_0_y0sgn = 2'd0;
wire        uc_issue_fmul_ilog2_const_1ee6091d_0 = transacting & ucode_word[24 +: 1];
wire [ 1:0] uc_fmul_ilog2_const_1ee6091d_0_asgn = 2'd0;
wire        uc_fmul_ilog2_const_1ee6091d_0_ard = ucode_word[25 +: 1];
wire [ 1:0] uc_fmul_ilog2_const_1ee6091d_0_y0sgn = 2'd0;
wire        uc_issue_fmul_ilog2_const_c32f4dd0_0 = transacting & ucode_word[26 +: 1];
wire [ 1:0] uc_fmul_ilog2_const_c32f4dd0_0_asgn = 2'd0;
wire        uc_fmul_ilog2_const_c32f4dd0_0_ard = ucode_word[27 +: 1];
wire [ 1:0] uc_fmul_ilog2_const_c32f4dd0_0_y0sgn = 2'd0;
wire        uc_issue_fmul_ilog2_const_640a8f67_0 = transacting & ucode_word[28 +: 1];
wire [ 1:0] uc_fmul_ilog2_const_640a8f67_0_asgn = 2'd0;
wire        uc_fmul_ilog2_const_640a8f67_0_ard = ucode_word[29 +: 1];
wire [ 1:0] uc_fmul_ilog2_const_640a8f67_0_y0sgn = 2'd0;
wire        uc_issue_fmul_ilog2_const_03d3dd98_0 = transacting & ucode_word[30 +: 1];
wire [ 1:0] uc_fmul_ilog2_const_03d3dd98_0_asgn = 2'd0;
wire        uc_fmul_ilog2_const_03d3dd98_0_ard = ucode_word[31 +: 1];
wire [ 1:0] uc_fmul_ilog2_const_03d3dd98_0_y0sgn = 2'd0;
wire        uc_op_b0 = transacting & ucode_word[32 +: 1];
wire        uc_op_r1 = transacting & ucode_word[33 +: 1];
wire        uc_op_r3 = transacting & ucode_word[34 +: 1];
wire [ 3:0] uc_op_r2 = {4{transacting}} & ucode_word[35 +: 4];
wire [ 1:0] uc_op_r0 = {2{transacting}} & ucode_word[39 +: 2];
wire        uc_op_r4 = transacting & ucode_word[41 +: 1];
wire        uc_op_r5 = transacting & ucode_word[42 +: 1];
wire        uc_op_r6 = transacting & ucode_word[43 +: 1];

holoso_fcmp #(
    .WEXP(8), .WMAN(36), .STAGE_INPUT(0), .LATENCY(1)
) u_fcmp_63b877a8_0 (
    .clk(clk), .rst(rst), .in_valid(uc_issue_fcmp_63b877a8_0),
    .a_sgnop(uc_fcmp_63b877a8_0_asgn),
    .b_sgnop(uc_fcmp_63b877a8_0_bsgn),
    .a(s_fcmp_63b877a8_0_a),
    .b(s_fcmp_63b877a8_0_b),
    .out_valid(),
    .a_gt_b(s_fcmp_63b877a8_0_y0),
    .a_eq_b(),
    .a_lt_b()
);

holoso_fadd #(
    .WEXP(8), .WMAN(36), .STAGE_INPUT(0), .STAGE_DECODE(0), .STAGE_ALIGN(0), .STAGE_NORMALIZE(0), .STAGE_PACK(0), .STAGE_OUTPUT(0), .LATENCY(4)
) u_fadd_9eba50d4_0 (
    .clk(clk), .rst(rst), .in_valid(uc_issue_fadd_9eba50d4_0),
    .a_sgnop(uc_fadd_9eba50d4_0_asgn),
    .b_sgnop(uc_fadd_9eba50d4_0_bsgn),
    .y_sgnop(uc_fadd_9eba50d4_0_y0sgn),
    .a(s_fadd_9eba50d4_0_a),
    .b(s_fadd_9eba50d4_0_b),
    .out_valid(),
    .y(s_fadd_9eba50d4_0_y0)
);

holoso_fmul_ilog2_const #(
    .WEXP(8), .WMAN(36), .K(-1), .STAGE_INPUT(0), .STAGE_DECODE(0), .LATENCY(1)
) u_fmul_ilog2_const_98e5699d_0 (
    .clk(clk), .rst(rst), .in_valid(uc_issue_fmul_ilog2_const_98e5699d_0),
    .a_sgnop(uc_fmul_ilog2_const_98e5699d_0_asgn),
    .y_sgnop(uc_fmul_ilog2_const_98e5699d_0_y0sgn),
    .a(s_fmul_ilog2_const_98e5699d_0_a),
    .out_valid(),
    .y(s_fmul_ilog2_const_98e5699d_0_y0)
);

holoso_fmul_ilog2_const #(
    .WEXP(8), .WMAN(36), .K(-2), .STAGE_INPUT(0), .STAGE_DECODE(0), .LATENCY(1)
) u_fmul_ilog2_const_b971b71f_0 (
    .clk(clk), .rst(rst), .in_valid(uc_issue_fmul_ilog2_const_b971b71f_0),
    .a_sgnop(uc_fmul_ilog2_const_b971b71f_0_asgn),
    .y_sgnop(uc_fmul_ilog2_const_b971b71f_0_y0sgn),
    .a(s_fmul_ilog2_const_b971b71f_0_a),
    .out_valid(),
    .y(s_fmul_ilog2_const_b971b71f_0_y0)
);

holoso_fmul_ilog2_const #(
    .WEXP(8), .WMAN(36), .K(-3), .STAGE_INPUT(0), .STAGE_DECODE(0), .LATENCY(1)
) u_fmul_ilog2_const_91771f93_0 (
    .clk(clk), .rst(rst), .in_valid(uc_issue_fmul_ilog2_const_91771f93_0),
    .a_sgnop(uc_fmul_ilog2_const_91771f93_0_asgn),
    .y_sgnop(uc_fmul_ilog2_const_91771f93_0_y0sgn),
    .a(s_fmul_ilog2_const_91771f93_0_a),
    .out_valid(),
    .y(s_fmul_ilog2_const_91771f93_0_y0)
);

holoso_fmul_ilog2_const #(
    .WEXP(8), .WMAN(36), .K(-4), .STAGE_INPUT(0), .STAGE_DECODE(0), .LATENCY(1)
) u_fmul_ilog2_const_72d9b6c9_0 (
    .clk(clk), .rst(rst), .in_valid(uc_issue_fmul_ilog2_const_72d9b6c9_0),
    .a_sgnop(uc_fmul_ilog2_const_72d9b6c9_0_asgn),
    .y_sgnop(uc_fmul_ilog2_const_72d9b6c9_0_y0sgn),
    .a(s_fmul_ilog2_const_72d9b6c9_0_a),
    .out_valid(),
    .y(s_fmul_ilog2_const_72d9b6c9_0_y0)
);

holoso_fmul_ilog2_const #(
    .WEXP(8), .WMAN(36), .K(-5), .STAGE_INPUT(0), .STAGE_DECODE(0), .LATENCY(1)
) u_fmul_ilog2_const_0436199d_0 (
    .clk(clk), .rst(rst), .in_valid(uc_issue_fmul_ilog2_const_0436199d_0),
    .a_sgnop(uc_fmul_ilog2_const_0436199d_0_asgn),
    .y_sgnop(uc_fmul_ilog2_const_0436199d_0_y0sgn),
    .a(s_fmul_ilog2_const_0436199d_0_a),
    .out_valid(),
    .y(s_fmul_ilog2_const_0436199d_0_y0)
);

holoso_fmul_ilog2_const #(
    .WEXP(8), .WMAN(36), .K(-6), .STAGE_INPUT(0), .STAGE_DECODE(0), .LATENCY(1)
) u_fmul_ilog2_const_3fcbcfed_0 (
    .clk(clk), .rst(rst), .in_valid(uc_issue_fmul_ilog2_const_3fcbcfed_0),
    .a_sgnop(uc_fmul_ilog2_const_3fcbcfed_0_asgn),
    .y_sgnop(uc_fmul_ilog2_const_3fcbcfed_0_y0sgn),
    .a(s_fmul_ilog2_const_3fcbcfed_0_a),
    .out_valid(),
    .y(s_fmul_ilog2_const_3fcbcfed_0_y0)
);

holoso_fmul_ilog2_const #(
    .WEXP(8), .WMAN(36), .K(-7), .STAGE_INPUT(0), .STAGE_DECODE(0), .LATENCY(1)
) u_fmul_ilog2_const_9afe18ac_0 (
    .clk(clk), .rst(rst), .in_valid(uc_issue_fmul_ilog2_const_9afe18ac_0),
    .a_sgnop(uc_fmul_ilog2_const_9afe18ac_0_asgn),
    .y_sgnop(uc_fmul_ilog2_const_9afe18ac_0_y0sgn),
    .a(s_fmul_ilog2_const_9afe18ac_0_a),
    .out_valid(),
    .y(s_fmul_ilog2_const_9afe18ac_0_y0)
);

holoso_fmul_ilog2_const #(
    .WEXP(8), .WMAN(36), .K(-8), .STAGE_INPUT(0), .STAGE_DECODE(0), .LATENCY(1)
) u_fmul_ilog2_const_1ee6091d_0 (
    .clk(clk), .rst(rst), .in_valid(uc_issue_fmul_ilog2_const_1ee6091d_0),
    .a_sgnop(uc_fmul_ilog2_const_1ee6091d_0_asgn),
    .y_sgnop(uc_fmul_ilog2_const_1ee6091d_0_y0sgn),
    .a(s_fmul_ilog2_const_1ee6091d_0_a),
    .out_valid(),
    .y(s_fmul_ilog2_const_1ee6091d_0_y0)
);

holoso_fmul_ilog2_const #(
    .WEXP(8), .WMAN(36), .K(-9), .STAGE_INPUT(0), .STAGE_DECODE(0), .LATENCY(1)
) u_fmul_ilog2_const_c32f4dd0_0 (
    .clk(clk), .rst(rst), .in_valid(uc_issue_fmul_ilog2_const_c32f4dd0_0),
    .a_sgnop(uc_fmul_ilog2_const_c32f4dd0_0_asgn),
    .y_sgnop(uc_fmul_ilog2_const_c32f4dd0_0_y0sgn),
    .a(s_fmul_ilog2_const_c32f4dd0_0_a),
    .out_valid(),
    .y(s_fmul_ilog2_const_c32f4dd0_0_y0)
);

holoso_fmul_ilog2_const #(
    .WEXP(8), .WMAN(36), .K(-10), .STAGE_INPUT(0), .STAGE_DECODE(0), .LATENCY(1)
) u_fmul_ilog2_const_640a8f67_0 (
    .clk(clk), .rst(rst), .in_valid(uc_issue_fmul_ilog2_const_640a8f67_0),
    .a_sgnop(uc_fmul_ilog2_const_640a8f67_0_asgn),
    .y_sgnop(uc_fmul_ilog2_const_640a8f67_0_y0sgn),
    .a(s_fmul_ilog2_const_640a8f67_0_a),
    .out_valid(),
    .y(s_fmul_ilog2_const_640a8f67_0_y0)
);

holoso_fmul_ilog2_const #(
    .WEXP(8), .WMAN(36), .K(-11), .STAGE_INPUT(0), .STAGE_DECODE(0), .LATENCY(1)
) u_fmul_ilog2_const_03d3dd98_0 (
    .clk(clk), .rst(rst), .in_valid(uc_issue_fmul_ilog2_const_03d3dd98_0),
    .a_sgnop(uc_fmul_ilog2_const_03d3dd98_0_asgn),
    .y_sgnop(uc_fmul_ilog2_const_03d3dd98_0_y0sgn),
    .a(s_fmul_ilog2_const_03d3dd98_0_a),
    .out_valid(),
    .y(s_fmul_ilog2_const_03d3dd98_0_y0)
);

assign err = 1'b0;

// Next-PC sequencer (combinational). The PC holds at the accept (pc==0) and present (pc==LASTPC) boundaries; bubble
// steps carry a NOP word and the PC keeps advancing. The executing step lags the fetch PC by FETCH_LAG. A block's
// terminator redirects the fetch PC at the block's boundary step (a branch reads its boolean register). Each branch
// also sets transacting_in -- 1 for a live accept/body word, 0 at the boundaries -- so each branch tags its own word.
always @* begin
    if (rst) begin
        next_pc        = 0;
        transacting_in = 1'b0;
    end else if (out_valid) begin  // present: hold until the result is taken
        next_pc        = out_ready ? 0 : LASTPC;
        transacting_in = 1'b0;
    end else if (in_ready) begin   // accept: hold until a transaction arrives
        next_pc        = in_valid ? 1 : 0;
        transacting_in = in_valid;
    end else begin                 // advance the fetch: the body of a live transaction
        transacting_in = 1'b1;
        next_pc        = pc + 1'b1;
    end
end

// Operand read muxes: a per-port case over the read codebook (registers and constants), driving the wrapper.
always @* begin
    s_fcmp_63b877a8_0_a = const_13;
    case (uc_fcmp_63b877a8_0_brd)
        1'd0: s_fcmp_63b877a8_0_b = regs[0];
        default: s_fcmp_63b877a8_0_b = regs[4];
    endcase
    case (uc_fadd_9eba50d4_0_ard)
        2'd0: s_fadd_9eba50d4_0_a = regs[0];
        2'd1: s_fadd_9eba50d4_0_a = regs[4];
        default: s_fadd_9eba50d4_0_a = const_1;
    endcase
    case (uc_fadd_9eba50d4_0_brd)
        4'd0: s_fadd_9eba50d4_0_b = regs[2];
        4'd1: s_fadd_9eba50d4_0_b = const_0;
        4'd2: s_fadd_9eba50d4_0_b = const_2;
        4'd3: s_fadd_9eba50d4_0_b = const_3;
        4'd4: s_fadd_9eba50d4_0_b = const_4;
        4'd5: s_fadd_9eba50d4_0_b = const_5;
        4'd6: s_fadd_9eba50d4_0_b = const_6;
        4'd7: s_fadd_9eba50d4_0_b = const_7;
        4'd8: s_fadd_9eba50d4_0_b = const_8;
        4'd9: s_fadd_9eba50d4_0_b = const_9;
        4'd10: s_fadd_9eba50d4_0_b = const_10;
        4'd11: s_fadd_9eba50d4_0_b = const_11;
        default: s_fadd_9eba50d4_0_b = const_12;
    endcase
    s_fmul_ilog2_const_98e5699d_0_a = regs[0];
    case (uc_fmul_ilog2_const_b971b71f_0_ard)
        1'd0: s_fmul_ilog2_const_b971b71f_0_a = regs[0];
        default: s_fmul_ilog2_const_b971b71f_0_a = regs[4];
    endcase
    case (uc_fmul_ilog2_const_91771f93_0_ard)
        1'd0: s_fmul_ilog2_const_91771f93_0_a = regs[0];
        default: s_fmul_ilog2_const_91771f93_0_a = regs[4];
    endcase
    case (uc_fmul_ilog2_const_72d9b6c9_0_ard)
        1'd0: s_fmul_ilog2_const_72d9b6c9_0_a = regs[0];
        default: s_fmul_ilog2_const_72d9b6c9_0_a = regs[4];
    endcase
    case (uc_fmul_ilog2_const_0436199d_0_ard)
        1'd0: s_fmul_ilog2_const_0436199d_0_a = regs[0];
        default: s_fmul_ilog2_const_0436199d_0_a = regs[4];
    endcase
    case (uc_fmul_ilog2_const_3fcbcfed_0_ard)
        1'd0: s_fmul_ilog2_const_3fcbcfed_0_a = regs[0];
        default: s_fmul_ilog2_const_3fcbcfed_0_a = regs[4];
    endcase
    case (uc_fmul_ilog2_const_9afe18ac_0_ard)
        1'd0: s_fmul_ilog2_const_9afe18ac_0_a = regs[0];
        default: s_fmul_ilog2_const_9afe18ac_0_a = regs[4];
    endcase
    case (uc_fmul_ilog2_const_1ee6091d_0_ard)
        1'd0: s_fmul_ilog2_const_1ee6091d_0_a = regs[0];
        default: s_fmul_ilog2_const_1ee6091d_0_a = regs[4];
    endcase
    case (uc_fmul_ilog2_const_c32f4dd0_0_ard)
        1'd0: s_fmul_ilog2_const_c32f4dd0_0_a = regs[0];
        default: s_fmul_ilog2_const_c32f4dd0_0_a = regs[4];
    endcase
    case (uc_fmul_ilog2_const_640a8f67_0_ard)
        1'd0: s_fmul_ilog2_const_640a8f67_0_a = regs[0];
        default: s_fmul_ilog2_const_640a8f67_0_a = regs[4];
    endcase
    case (uc_fmul_ilog2_const_03d3dd98_0_ard)
        1'd0: s_fmul_ilog2_const_03d3dd98_0_a = regs[0];
        default: s_fmul_ilog2_const_03d3dd98_0_a = regs[4];
    endcase
end

// All sequential logic in one clocked process. Reset gates only the control state (pc, err_pc_q, transacting_q) and the
// persistent state registers; every other register is reset-unconditional. Each is driven by exactly one statement.
always @(posedge clk) begin
    // Microcode fetch: PC latch; ucode_word pipelines ucode_q.
    ucode_addr_q <= next_pc;
    ucode_word   <= ucode_q;

    // Register writes (reset-unconditional): one opcode-selected statement per register.
    if (in_ready && in_valid) regs[0] <= in_theta;
    else case (uc_op_r0)
        2'd1: regs[0] <= (bregs[0] ? const_1 : holoso_fsgnop(const_1, 2'd1));
        2'd2: regs[0] <= (bregs[0] ? regs[1] : regs[3]);
    endcase
    if (uc_op_r1) regs[1] <= s_fadd_9eba50d4_0_y0;
    case (uc_op_r2)
        4'd1: regs[2] <= s_fmul_ilog2_const_98e5699d_0_y0;
        4'd2: regs[2] <= s_fmul_ilog2_const_b971b71f_0_y0;
        4'd3: regs[2] <= s_fmul_ilog2_const_91771f93_0_y0;
        4'd4: regs[2] <= s_fmul_ilog2_const_72d9b6c9_0_y0;
        4'd5: regs[2] <= s_fmul_ilog2_const_0436199d_0_y0;
        4'd6: regs[2] <= s_fmul_ilog2_const_3fcbcfed_0_y0;
        4'd7: regs[2] <= s_fmul_ilog2_const_9afe18ac_0_y0;
        4'd8: regs[2] <= s_fmul_ilog2_const_1ee6091d_0_y0;
        4'd9: regs[2] <= s_fmul_ilog2_const_c32f4dd0_0_y0;
        4'd10: regs[2] <= s_fmul_ilog2_const_640a8f67_0_y0;
        4'd11: regs[2] <= s_fmul_ilog2_const_03d3dd98_0_y0;
    endcase
    if (uc_op_r3) regs[3] <= s_fadd_9eba50d4_0_y0;
    if (uc_op_r4) regs[4] <= (bregs[0] ? regs[1] : regs[3]);
    if (uc_op_r5) regs[5] <= (bregs[0] ? regs[1] : regs[3]);
    if (uc_op_r6) regs[6] <= (bregs[0] ? regs[1] : regs[3]);
    if (uc_op_b0) bregs[0] <= ~s_fcmp_63b877a8_0_y0;

    // Control and persistent state: the reset-gated registers.
    if (rst) begin
        pc            <= 0;
        err_pc_q      <= 0;
        transacting_q <= 0;
    end else begin
        pc <= next_pc;
        transacting_q <= (transacting_q << 1) | transacting_in;
        if (err) err_pc_q <= pc - FETCH_LAG;  // err wins; execution lags the fetch PC by FETCH_LAG, so step is pc-lag
        else if (in_ready && in_valid) err_pc_q <= 0;  // clear the diagnostic when a new transaction is accepted
    end
end

assign in_ready  = (pc == 0);
assign out_valid = (pc == LASTPC);  // result valid on PRESENT; execution lags the fetch by FETCH_LAG
assign err_pc    = err_pc_q;
assign out_0 = regs[6];
assign out_1 = regs[5];

endmodule
