// Generated by Holoso v<VERSION> <https://holoso.digital>.
// This file is generated output and is unencumbered: no copyright is claimed over it and no license terms apply.
// You may use, modify, and redistribute it freely, in open-source or proprietary designs, without restrictions.

`timescale 1ns/1ps

// Float format: exponent 8 bits, significand 36 bits, total 44 bits.
module ekf1_stateful_shipped (
    // CONTROL PORTS
    // Clock/reset and ready/valid handshake for one scheduled invocation.
    input  wire clk,
    input  wire rst,
    input  wire in_valid,
    output wire in_ready,
    output wire out_valid,
    input  wire out_ready,
    // INPUT PORTS
    // Latched when in_valid && in_ready.
    input  wire [43:0] in_dt,
    input  wire [43:0] in_u_shunt,
    input  wire [43:0] in_di_dt,
    // OUTPUT/STATE PORTS
    // Valid when out_valid is pulsed. Publicly visible states are included here.
    output wire [43:0] state_x_0,
    output wire [43:0] state_x_1,
    output wire [43:0] state_x_2,
    output wire [43:0] state_P_urt_0,
    output wire [43:0] state_P_urt_1,
    output wire [43:0] state_P_urt_2,
    output wire [43:0] state_P_urt_3,
    output wire [43:0] state_P_urt_4,
    output wire [43:0] state_P_urt_5,
    // DIAGNOSTIC PORTS
    // Runtime diagnostics available while the module is running.
    output wire [6:0] err_pc
);

localparam           WEXP      =   8;  // Float exponent bits fixed by the static schedule
localparam           WMAN      =  36;  // Float mantissa bits fixed by the static schedule
localparam           W         = WEXP + WMAN;
localparam           NREG      =  40;
localparam           CYCW      =   7;  // err_pc width: enough for any executing step (0..present)
localparam           PCW       =   7;  // fetch-PC width: counts to LASTPC (execution lags the fetch by FETCH_LAG)
localparam           FETCH_LAG =   2;  // executing step = pc - FETCH_LAG (3-stage control fetch)
localparam [PCW-1:0] PRESENT   = 125;  // executing step on which the outputs are valid in the array
localparam [PCW-1:0] LASTPC    = 127;  // = PRESENT + FETCH_LAG; out_valid asserts here
localparam           UCW       =  83;  // microcode word width after lifting out constant control fields
// pc: 0 = idle/accept, present at executing step PRESENT; out_valid at pc==LASTPC (fetch leads execution).

// BEGIN holoso_support_inline.vh: the file is spliced into each generated module.

// Arithmetic shift by a constant. Positive shamt shifts left. For variable shamt use holoso_ashift.
function signed [W-1:0] holoso_ashiftc;
    input signed [W-1:0] x;
    input signed [W-1:0] shamt;
    reg signed [W:0] shamt_ext;
    reg [$clog2(W)-1:0] shamt_narrow;
    reg signed [W-1:0] shifted_left;
    reg signed [W-1:0] shifted_right;
    begin
        shamt_ext = {shamt[W-1], shamt};
        shamt_narrow = shamt[$clog2(W)-1:0];
        shifted_left = x << shamt_narrow;
        shifted_right = x >>> -shamt_narrow;
        if (shamt_ext >= W) begin
            holoso_ashiftc = {W{1'b0}};
        end else if (shamt_ext <= -W) begin
            holoso_ashiftc = {W{x[W-1]}};
        end else if (shamt[W-1]) begin
            holoso_ashiftc = shifted_right;
        end else begin
            holoso_ashiftc = shifted_left;
        end
    end
endfunction

// Combinational mapping from float to boolean: a zero or a subnormal (if supported) float is false, otherwise true.
// E.g., if IEEE 754 binary32 is used (with subnormals), values with magnitude under ~1e-38 are mapped to falsity.
function holoso_ftobool;
    input [W-1:0] x;
    holoso_ftobool = |x[W-2:WMAN-1];
endfunction

// Combinational mapping from boolean to float: falsity is zero, truth is one.
function [W-1:0] holoso_ffrombool;
    input b;
    holoso_ffrombool = b ? {2'b00, {(WEXP - 1) {1'b1}}, {(WMAN - 1) {1'b0}}} : {W{1'b0}};
endfunction

// Combinational predicate: y=1 iff x is finite (i.e., x is not an infinity).
function holoso_fisfinite;
    input [W-1:0] x;
    holoso_fisfinite = ~&x[W-2:WMAN-1];
endfunction

function holoso_fisposinf;
    input [W-1:0] x;
    holoso_fisposinf = ~holoso_fisfinite(x) & ~x[W-1];
endfunction

function holoso_fisneginf;
    input [W-1:0] x;
    holoso_fisneginf = ~holoso_fisfinite(x) & x[W-1];
endfunction

// Combinational saturator: replaces infinity with the largest finite value of the same sign; finite pass through.
function [W-1:0] holoso_fsaturate;
    input [W-1:0] x;
    holoso_fsaturate = (&x[W-2:WMAN-1]) ? {x[W-1], {(WEXP - 1) {1'b1}}, 1'b0, {(WMAN - 1) {1'b1}}} : x;
endfunction

// Combinational floating-point sign conditioner (absolute first, then optional negate): op[0]=negate, op[1]=absolute.
//      op=0: +x        op=1: -x        op=2: +|x|      op=3: -|x|
function [W-1:0] holoso_fsgnop;
    input [W-1:0] x;
    input [1:0]   op;
    holoso_fsgnop = {(x[W-1] & ~op[1]) ^ op[0], x[W-2:0]};
endfunction

// END of holoso_support_inline.vh

reg  [PCW-1:0]  pc;            // fetch program counter; the executing step lags it by FETCH_LAG
reg  [PCW-1:0]  next_pc;       // combinational next-state presented to the ROM each cycle
reg  [PCW-1:0]  ucode_addr_q;  // PC latch: splits pc -> next_pc -> ROM address for the case read
reg  [CYCW-1:0] err_pc_q;
wire            err;           // an operator error is detected on the current step

reg                 transacting_in;                           // per-branch tag: this pc's word is a live step
reg [FETCH_LAG-1:0] transacting_q;                            // delays the tag FETCH_LAG onto executing word
wire                transacting = transacting_q[FETCH_LAG-1]; // gates the executing word's effects

reg  [W-1:0] regs  [0:NREG-1];   // read-first: a write is visible next step

reg  [W-1:0] s_fmul_68b24f7b_0_a;
reg  [W-1:0] s_fmul_68b24f7b_0_b;
wire [W-1:0] s_fmul_68b24f7b_0_y0;
reg  [W-1:0] s_fmul_ilog2_const_50db4625_0_a;
wire [W-1:0] s_fmul_ilog2_const_50db4625_0_y0;
reg  [W-1:0] s_fadd_9eba50d4_0_a;
reg  [W-1:0] s_fadd_9eba50d4_0_b;
wire [W-1:0] s_fadd_9eba50d4_0_y0;
reg  [W-1:0] s_fdiv_56ea25b7_0_a;
reg  [W-1:0] s_fdiv_56ea25b7_0_b;
wire [W-1:0] s_fdiv_56ea25b7_0_y0;
wire         s_fdiv_56ea25b7_0_div0;

wire [W-1:0] const_0 = 44'h3a83126e979;  // 0.001
wire [W-1:0] const_1 = 44'h4e6e6b28000;  // 1000000000.0
wire [W-1:0] const_2 = 44'h3089705f413;  // 1e-09
wire [W-1:0] const_3 = 44'h358637bd05b;  // 1e-06
wire [W-1:0] const_4 = 44'h447a0000000;  // 1000.0
wire [W-1:0] const_5 = 44'h3f800000000;  // 1.0

// Microcode VLIW ROM.
reg [UCW-1:0] ucode_q;     // 2nd fetch stage
reg [UCW-1:0] ucode_word;  // 3rd fetch stage
// Microcode word field map:
//   [0]      uc_issue_fmul_68b24f7b_0
//   [2:1]    uc_fmul_68b24f7b_0_asgn
//   [7:3]    uc_fmul_68b24f7b_0_ard
//   [9:8]    uc_fmul_68b24f7b_0_bsgn
//   [14:10]  uc_fmul_68b24f7b_0_brd
//   [15]     uc_issue_fmul_ilog2_const_50db4625_0
//   [16]     uc_fmul_ilog2_const_50db4625_0_ard
//   [17]     uc_issue_fadd_9eba50d4_0
//   [22:18]  uc_fadd_9eba50d4_0_ard
//   [24:23]  uc_fadd_9eba50d4_0_bsgn
//   [28:25]  uc_fadd_9eba50d4_0_brd
//   [29]     uc_issue_fdiv_56ea25b7_0
//   [31:30]  uc_op_r1
//   [33:32]  uc_op_r7
//   [35:34]  uc_op_r12
//   [37:36]  uc_op_r6
//   [38]     uc_op_r13
//   [39]     uc_op_r5
//   [41:40]  uc_op_r0
//   [42]     uc_op_r9
//   [44:43]  uc_op_r11
//   [45]     uc_op_r8
//   [47:46]  uc_op_r14
//   [48]     uc_op_r16
//   [49]     uc_op_r18
//   [51:50]  uc_op_r2
//   [52]     uc_op_r15
//   [53]     uc_op_r20
//   [54]     uc_op_r17
//   [56:55]  uc_op_r21
//   [57]     uc_op_r19
//   [59:58]  uc_op_r22
//   [60]     uc_op_r23
//   [61]     uc_op_r24
//   [62]     uc_op_r25
//   [64:63]  uc_op_r26
//   [66:65]  uc_op_r27
//   [68:67]  uc_op_r28
//   [69]     uc_op_r30
//   [70]     uc_op_r29
//   [71]     uc_op_r31
//   [72]     uc_op_r32
//   [73]     uc_op_r33
//   [74]     uc_op_r34
//   [75]     uc_op_r35
//   [76]     uc_op_r36
//   [77]     uc_op_r37
//   [78]     uc_op_r38
//   [79]     uc_op_r39
//   [80]     uc_op_r4
//   [81]     uc_op_r3
//   [82]     uc_op_r10
(* rom_style = "block", syn_romstyle = "EBR" *)
always @(posedge clk)
    case (ucode_addr_q)
        0: ucode_q <= 83'h000000000000000839801;  // issue r7=r4+-r1, r1=r0×r7, r12=r10×2^1
        1: ucode_q <= 83'h000000000000440000c01;  // issue r6=r0×r4; commit r1, r12
        2: ucode_q <= 83'h000000000001000061c01;  // issue r6=r6+r1, r1=r0×r9; commit r6
        3: ucode_q <= 83'h0000000000000440600a9;  // issue r6=r6+r5, r1=c2×r0; commit r1
        4: ucode_q <= 83'h0000000000001400a0039;  // issue r13=r7+r1, r5=r10×r0; commit r7, r1
        5: ucode_q <= 83'h0000000000080000000b1;  // issue r5=c1×r0; commit r5
        6: ucode_q <= 83'h00000000000a0040e00b9;  // issue r0=r8+r5, r1=c0×r0; commit r6, r5
        7: ucode_q <= 83'h000000000002040060819;  // issue r11=r6+r1, r9=r3×r3; commit r6, r1
        8: ucode_q <= 83'h000000000044004120821;  // issue r1=r9+r5, r8=r6×r3; commit r13, r9
        9: ucode_q <= 83'h000000000200000162801;  // issue r14=r11+r1, r1=r0×r13; commit r8
        10: ucode_q <= 83'h0000000000100428e9421;  // issue r16=r8+-r2, r5=r6×r6, r14=r8×2^1; commit r0, r1
        11: ucode_q <= 83'h000000000888000000001;  // issue r11=r0×r0; commit r11, r5, r14
        12: ucode_q <= 83'h000000000100080160059;  // issue r18=r11+r1, r2=r14×r0; commit r1, r11
        13: ucode_q <= 83'h000000004400000422c51;  // issue r20=c4+r1, r15=r13×r14; commit r14, r2
        14: ucode_q <= 83'h000000011000002460411;  // issue r21=c3+r2, r17=r2×r1; commit r16, r15
        15: ucode_q <= 83'h000000040000000002161;  // issue r19=r15×-r10; commit r17
        16: ucode_q <= 83'h000000202000000001059;  // issue r17=r14×r5; commit r18, r19
        17: ucode_q <= 83'h0000000600000081a3831;  // issue r21=r17+r19, r19=r9×r18; commit r20, r17
        18: ucode_q <= 83'h000000280000000003409;  // issue r22=r1×r17; commit r21, r19
        19: ucode_q <= 83'h000000400000008223c09;  // issue r21=r21+r19, r23=r1×r19; commit r22
        20: ucode_q <= 83'h000001000000000002849;  // issue r12=r12×r13; commit r23
        21: ucode_q <= 83'h000000080000800001c49;  // issue r23=r12×r9; commit r21, r12
        22: ucode_q <= 83'h00000100000000e226051;  // issue r21=r21+r23, r24=r13×c3; commit r23
        23: ucode_q <= 83'h000002080000000002429;  // issue r12=r8×r11; commit r21, r24
        24: ucode_q <= 83'h00000000000080a1a1049;  // issue r25=r17+r21, r23=r12×r5; commit r12
        25: ucode_q <= 83'h000001000000000004451;  // issue r23=r13×r23; commit r23
        26: ucode_q <= 83'h000001080000000004401;  // issue r21=r0×r23; commit r21, r23
        27: ucode_q <= 83'h00000010000000c2238b9;  // issue r21=r21+r22, r22=c0×r18; commit r21
        28: ucode_q <= 83'h00000440000000000483b;  // issue r21=-r10×r24; commit r25, r22
        29: ucode_q <= 83'h00000010000000c226449;  // issue r22=r21+r22, r22=r12×c4; commit r21
        30: ucode_q <= 83'h000000400000000004401;  // issue r22=r0×r23; commit r22
        31: ucode_q <= 83'h00000048000000c226859;  // issue r26=r21+r22, r23=r14×c0; commit r21, r22
        32: ucode_q <= 83'h0000010000000000004c1;  // issue r2=c3×r1; commit r23
        33: ucode_q <= 83'h00000080400000e266411;  // issue r27=r22+r23, r21=r2×c4; commit r22, r2
        34: ucode_q <= 83'h000000100000002223cc9;  // issue r28=r21+r2, r23=c4×r19; commit r21
        35: ucode_q <= 83'h000009000000000003829;  // issue r23=r8×r18; commit r26, r23
        36: ucode_q <= 83'h00000100000000e2238c9;  // issue r30=r21+r23, r21=c4×r18; commit r23
        37: ucode_q <= 83'h000020100000000006431;  // issue r29=r9×c4; commit r27, r21
        38: ucode_q <= 83'h000480000000000004459;  // issue r21=r14×r23; commit r28, r29
        39: ucode_q <= 83'h000000100000000004059;  // issue r29=r14×r21; commit r21
        40: ucode_q <= 83'h000600000000000003889;  // issue r31=r29×r18; commit r30, r29
        41: ucode_q <= 83'h000800000000000002039;  // issue r29=r10×r10; commit r31
        42: ucode_q <= 83'h000400000000000001089;  // issue r32=r29×r5; commit r29
        43: ucode_q <= 83'h001000000000000006471;  // issue r22=r21×c4; commit r32
        44: ucode_q <= 83'h000000400000012265059;  // issue r26=r22+r32, r22=r14×r31; commit r22
        45: ucode_q <= 83'h00000040000000cae1089;  // issue r27=r26+-r22, r22=r29×r5; commit r22
        46: ucode_q <= 83'h00000040000000c3234c9;  // issue r28=r27+r22, r32=c4×r17; commit r22
        47: ucode_q <= 83'h00100000000000cb61041;  // issue r30=r28+-r22, r11=r11×r5; commit r32
        48: ucode_q <= 83'h0000080001000123a2431;  // issue r26=r30+r32, r31=r9×r11; commit r26, r11
        49: ucode_q <= 83'h000820000000000002851;  // issue r32=r13×r13; commit r27, r31
        50: ucode_q <= 83'h0010800000000000024c9;  // issue r33=c4×r11; commit r28, r32
        51: ucode_q <= 83'h002200000000000006801;  // issue r33=r0×c0; commit r30, r33
        52: ucode_q <= 83'h002008000000014ae50c9;  // issue r26=r26+-r33, r33=c4×r31; commit r26, r33
        53: ucode_q <= 83'h002000000000014321c91;  // issue r26=r27+r33, r33=r32×r9; commit r33
        54: ucode_q <= 83'h002000000000014b63811;  // issue r21=r28+-r33, r12=r2×r18; commit r33
        55: ucode_q <= 83'h000000000000814ba0449;  // issue r12=r30+-r33, r34=r12×r1; commit r12
        56: ucode_q <= 83'h00400800000001c2e2c11;  // issue r26=r26+c0, r12=r2×r14; commit r26, r34
        57: ucode_q <= 83'h0000080000008062e6091;  // issue r27=r26+r12, r34=r32×c3; commit r26, r12
        58: ucode_q <= 83'h0040000800000162e0471;  // issue r27=r26+r34, r21=r21×r1; commit r21, r34
        59: ucode_q <= 83'h000000100000c06226089;  // issue r27=r21+r12, r35=r29×c3; commit r12, r21
        60: ucode_q <= 83'h008008000000000001439;  // issue r26=r10×r6; commit r26, r35
        61: ucode_q <= 83'h0000300000000062e0851;  // issue r26=r26+r12, r34=r13×r3; commit r27, r26
        62: ucode_q <= 83'h004020000000016b23819;  // issue r28=r27+-r34, r21=r3×r18; commit r27, r34
        63: ucode_q <= 83'h00002010000000ab20021;  // issue r27=r27+-r21, r35=r6×r0; commit r27, r21
        64: ucode_q <= 83'h008000000000018b22c21;  // issue r30=r27+-r35, r27=r6×r14; commit r35
        65: ucode_q <= 83'h0000480000000162e0801;  // issue r21=r26+r34, r21=r0×r3; commit r26, r27
        66: ucode_q <= 83'h000080100000038223809;  // issue r36=r21+r35, r0=c5/r26, r21=r1×r18; commit r28, r21
        67: ucode_q <= 83'h00002010000000a320431;  // issue r37=r27+r21, r34=r9×r1; commit r27, r21
        68: ucode_q <= 83'h004200000000000000051;  // issue r35=r13×r0; commit r30, r34
        69: ucode_q <= 83'h008000080000000004059;  // issue r34=r14×r21; commit r21, r35
        70: ucode_q <= 83'h0140000000000000038a1;  // issue r34=r34×r18; commit r36, r34
        71: ucode_q <= 83'h0240000000000000010a1;  // issue r38=r34×r5; commit r37, r34
        72: ucode_q <= 83'h04000000000000000443b;  // issue r28=-r10×r23; commit r38
        73: ucode_q <= 83'h00010000000001a365429;  // issue r28=r28+r38, r2=r8×r35; commit r28
        74: ucode_q <= 83'h000000004000000000011;  // issue r2=r2×r0; commit r2
        75: ucode_q <= 83'h000000004000002366039;  // issue r30=r28+r2, r27=r10×c3; commit r2
        76: ucode_q <= 83'h000040000000002323c39;  // issue r39=r27+r2, r2=r10×r19; commit r27
        77: ucode_q <= 83'h000080004000000002ca1;  // issue r2=r34×r14; commit r28, r2
        78: ucode_q <= 83'h000000004000002324051;  // issue r11=r27+r2, r27=r13×r21; commit r2
        79: ucode_q <= 83'h0002400000000023a5869;  // issue r27=r30+r2, r2=r20×r36; commit r30, r27
        80: ucode_q <= 83'h080000004000000004039;  // issue r27=r10×r21; commit r39, r2
        81: ucode_q <= 83'h000040000000002b25c69;  // issue r2=r27+-r2, r2=r20×r37; commit r27
        82: ucode_q <= 83'h000000004080000002409;  // issue r2=r1×r11; commit r11, r2
        83: ucode_q <= 83'h000020004000002b23451;  // issue r11=r27+-r2, r2=r13×r17; commit r27, r2
        84: ucode_q <= 83'h000000004000002b64489;  // issue r27=r28+-r2, r23=r29×r23; commit r2
        85: ucode_q <= 83'h0000010080000023a5431;  // issue r28=r30+r2, r23=r9×r35; commit r2, r23
        86: ucode_q <= 83'h00000100000000e3e5009;  // issue r30=r39+r23, r23=r1×r31; commit r23
        87: ucode_q <= 83'h0000010000a000e960039;  // issue r39=r11+-r23, r9=r10×r0; commit r11, r0, r23
        88: ucode_q <= 83'h00002000004000eb22c29;  // issue r28=r27+-r23, r23=r8×r14; commit r27, r9
        89: ucode_q <= 83'h000081000000000004c51;  // issue r28=r13×r25; commit r28, r23
        90: ucode_q <= 83'h000300000000010365871;  // issue r20=r28+r24, r24=r21×r36; commit r30, r28
        91: ucode_q <= 83'h0800020000000000030cb;  // issue r1=-c4×r16; commit r39, r24
        92: ucode_q <= 83'h000080000000050b64c09;  // issue r6=r28+-r24, r24=r1×r25; commit r28, r1
        93: ucode_q <= 83'h000002000000000004071;  // issue r34=r21×r21; commit r24
        94: ucode_q <= 83'h004000020000000004c39;  // issue r24=r10×r25; commit r20, r34
        95: ucode_q <= 83'h000002000000016aa5c71;  // issue r1=r24+-r34, r34=r21×r37; commit r24
        96: ucode_q <= 83'h004000000002000001481;  // issue r24=r26×r6; commit r6, r34
        97: ucode_q <= 83'h000002000000016aa3011;  // issue r2=r24+-r34, r1=r2×r16; commit r24
        98: ucode_q <= 83'h000000000000040004009;  // issue r4=r1×r21; commit r1
        99: ucode_q <= 83'h1000000000000802a0c81;  // issue r11=r24+r1, r2=r26×r4; commit r1, r4
        100: ucode_q <= 83'h000000004000000000881;  // issue r4=r26×r3; commit r2
        101: ucode_q <= 83'h100000008000002023041;  // issue r21=r4+r2, r21=r11×r16; commit r2, r4
        102: ucode_q <= 83'h000000100000000003879;  // issue r21=r22×r18; commit r21
        103: ucode_q <= 83'h00000010008000a024491;  // issue r6=r4+r21, r21=r32×r23; commit r11, r21
        104: ucode_q <= 83'h00000010000000ab21c29;  // issue r7=r27+-r21, r19=r8×r9; commit r21
        105: ucode_q <= 83'h00000028000000a3a3c89;  // issue r11=r30+r21, r19=r29×r19; commit r21, r19
        106: ucode_q <= 83'h0000002000000083e1821;  // issue r6=r39+r19, r1=r6×r7; commit r19
        107: ucode_q <= 83'h000000000002048b61809;  // issue r7=r28+-r19, r1=r1×r7; commit r6, r1
        108: ucode_q <= 83'h000000000000140961811;  // issue r1=r11+-r1, r1=r2×r7; commit r7, r1
        109: ucode_q <= 83'h000000000080040a23491;  // issue r2=r21+-r1, r1=r32×r17; commit r11, r1
        110: ucode_q <= 83'h000000000002040861031;  // issue r6=r6+-r1, r1=r9×r5; commit r6, r1
        111: ucode_q <= 83'h0000000000001408a1c61;  // issue r11=r7+-r1, r2=r15×r9; commit r7, r1
        112: ucode_q <= 83'h0000000040000809e4451;  // issue r2=r20+-r1, r5=r13×r23; commit r1, r2
        113: ucode_q <= 83'h000000008008002962c99;  // issue r13=r11+-r2, r5=r33×r14; commit r2, r5
        114: ucode_q <= 83'h00000000000a0048600c9;  // issue r11=r6+-r5, r1=c4×r0; commit r6, r5
        115: ucode_q <= 83'h0000000000800448a0009;  // issue r2=r7+-r5, r3=r1×r0; commit r11, r1
        116: ucode_q <= 83'h200000008000000000011;  // issue r4=r2×r0; commit r2, r3
        117: ucode_q <= 83'h100000000004000001401;  // issue r5=r0×r6; commit r13, r4
        118: ucode_q <= 83'h000000000088000002401;  // issue r6=r0×r11; commit r11, r5
        119: ucode_q <= 83'h000000008001000000411;  // issue r7=r2×r1; commit r2, r6
        120: ucode_q <= 83'h000000000000200002801;  // issue r8=r0×r13; commit r7
        121: ucode_q <= 83'h000000000200000000449;  // issue r9=r12×r1; commit r8
        122: ucode_q <= 83'h000000000040000002409;  // issue r10=r1×r11; commit r9
        123: ucode_q <= 83'h400000000000000000011;  // issue r11=r2×r0; commit r10
        124: ucode_q <= 83'h000000000100000000000;  // commit r11
        125: ucode_q <= 83'h000000000000000000000;
        126: ucode_q <= 83'h000000000000000000000;
        127: ucode_q <= 83'h000000000000000000000;
        default: ucode_q <= 83'h0;  // unreached (PC bounded to LASTPC); NOP fill
    endcase

// Decoded control fields. A field constant across the whole program is driven by a constant net (so synthesis prunes
// the logic it feeds); a varying field is a slice of the instruction word. The effect-trigger fields -- the ``gated``
// ones (operator issue strobes and per-register write opcodes) -- are ANDed with `transacting` HERE, so a held
// ucode[0] dwell, a fill bubble, or a stale pre-reset word decodes to 0 (NOP): no issue and every register holds.
// The AND wraps the constant branch too, so the gate stays unconditional even if a trigger ever folds to a constant.
wire        uc_issue_fmul_68b24f7b_0 = transacting & ucode_word[0 +: 1];
wire [ 1:0] uc_fmul_68b24f7b_0_asgn = ucode_word[1 +: 2];
wire [ 4:0] uc_fmul_68b24f7b_0_ard = ucode_word[3 +: 5];
wire [ 1:0] uc_fmul_68b24f7b_0_bsgn = ucode_word[8 +: 2];
wire [ 4:0] uc_fmul_68b24f7b_0_brd = ucode_word[10 +: 5];
wire [ 1:0] uc_fmul_68b24f7b_0_y0sgn = 2'd0;
wire        uc_issue_fmul_ilog2_const_50db4625_0 = transacting & ucode_word[15 +: 1];
wire [ 1:0] uc_fmul_ilog2_const_50db4625_0_asgn = 2'd0;
wire        uc_fmul_ilog2_const_50db4625_0_ard = ucode_word[16 +: 1];
wire [ 1:0] uc_fmul_ilog2_const_50db4625_0_y0sgn = 2'd0;
wire        uc_issue_fadd_9eba50d4_0 = transacting & ucode_word[17 +: 1];
wire [ 1:0] uc_fadd_9eba50d4_0_asgn = 2'd0;
wire [ 4:0] uc_fadd_9eba50d4_0_ard = ucode_word[18 +: 5];
wire [ 1:0] uc_fadd_9eba50d4_0_bsgn = ucode_word[23 +: 2];
wire [ 3:0] uc_fadd_9eba50d4_0_brd = ucode_word[25 +: 4];
wire [ 1:0] uc_fadd_9eba50d4_0_y0sgn = 2'd0;
wire        uc_issue_fdiv_56ea25b7_0 = transacting & ucode_word[29 +: 1];
wire [ 1:0] uc_fdiv_56ea25b7_0_asgn = 2'd0;
wire [ 1:0] uc_fdiv_56ea25b7_0_bsgn = 2'd0;
wire [ 1:0] uc_fdiv_56ea25b7_0_y0sgn = 2'd0;
wire [ 1:0] uc_op_r1 = {2{transacting}} & ucode_word[30 +: 2];
wire [ 1:0] uc_op_r7 = {2{transacting}} & ucode_word[32 +: 2];
wire [ 1:0] uc_op_r12 = {2{transacting}} & ucode_word[34 +: 2];
wire [ 1:0] uc_op_r6 = {2{transacting}} & ucode_word[36 +: 2];
wire        uc_op_r13 = transacting & ucode_word[38 +: 1];
wire        uc_op_r5 = transacting & ucode_word[39 +: 1];
wire [ 1:0] uc_op_r0 = {2{transacting}} & ucode_word[40 +: 2];
wire        uc_op_r9 = transacting & ucode_word[42 +: 1];
wire [ 1:0] uc_op_r11 = {2{transacting}} & ucode_word[43 +: 2];
wire        uc_op_r8 = transacting & ucode_word[45 +: 1];
wire [ 1:0] uc_op_r14 = {2{transacting}} & ucode_word[46 +: 2];
wire        uc_op_r16 = transacting & ucode_word[48 +: 1];
wire        uc_op_r18 = transacting & ucode_word[49 +: 1];
wire [ 1:0] uc_op_r2 = {2{transacting}} & ucode_word[50 +: 2];
wire        uc_op_r15 = transacting & ucode_word[52 +: 1];
wire        uc_op_r20 = transacting & ucode_word[53 +: 1];
wire        uc_op_r17 = transacting & ucode_word[54 +: 1];
wire [ 1:0] uc_op_r21 = {2{transacting}} & ucode_word[55 +: 2];
wire        uc_op_r19 = transacting & ucode_word[57 +: 1];
wire [ 1:0] uc_op_r22 = {2{transacting}} & ucode_word[58 +: 2];
wire        uc_op_r23 = transacting & ucode_word[60 +: 1];
wire        uc_op_r24 = transacting & ucode_word[61 +: 1];
wire        uc_op_r25 = transacting & ucode_word[62 +: 1];
wire [ 1:0] uc_op_r26 = {2{transacting}} & ucode_word[63 +: 2];
wire [ 1:0] uc_op_r27 = {2{transacting}} & ucode_word[65 +: 2];
wire [ 1:0] uc_op_r28 = {2{transacting}} & ucode_word[67 +: 2];
wire        uc_op_r30 = transacting & ucode_word[69 +: 1];
wire        uc_op_r29 = transacting & ucode_word[70 +: 1];
wire        uc_op_r31 = transacting & ucode_word[71 +: 1];
wire        uc_op_r32 = transacting & ucode_word[72 +: 1];
wire        uc_op_r33 = transacting & ucode_word[73 +: 1];
wire        uc_op_r34 = transacting & ucode_word[74 +: 1];
wire        uc_op_r35 = transacting & ucode_word[75 +: 1];
wire        uc_op_r36 = transacting & ucode_word[76 +: 1];
wire        uc_op_r37 = transacting & ucode_word[77 +: 1];
wire        uc_op_r38 = transacting & ucode_word[78 +: 1];
wire        uc_op_r39 = transacting & ucode_word[79 +: 1];
wire        uc_op_r4 = transacting & ucode_word[80 +: 1];
wire        uc_op_r3 = transacting & ucode_word[81 +: 1];
wire        uc_op_r10 = transacting & ucode_word[82 +: 1];

holoso_fmul #(
    .WEXP(8), .WMAN(36), .WMULTIPLIER(0), .STAGE_INPUT(0), .STAGE_PRODUCT(0), .STAGE_PACK(0), .STAGE_OUTPUT(0), .LATENCY(1)
) u_fmul_68b24f7b_0 (
    .clk(clk), .rst(rst), .in_valid(uc_issue_fmul_68b24f7b_0),
    .a_sgnop(uc_fmul_68b24f7b_0_asgn),
    .b_sgnop(uc_fmul_68b24f7b_0_bsgn),
    .y_sgnop(uc_fmul_68b24f7b_0_y0sgn),
    .a(s_fmul_68b24f7b_0_a),
    .b(s_fmul_68b24f7b_0_b),
    .out_valid(),
    .y(s_fmul_68b24f7b_0_y0)
);

holoso_fmul_ilog2_const #(
    .WEXP(8), .WMAN(36), .K(1), .STAGE_INPUT(0), .STAGE_DECODE(0), .LATENCY(1)
) u_fmul_ilog2_const_50db4625_0 (
    .clk(clk), .rst(rst), .in_valid(uc_issue_fmul_ilog2_const_50db4625_0),
    .a_sgnop(uc_fmul_ilog2_const_50db4625_0_asgn),
    .y_sgnop(uc_fmul_ilog2_const_50db4625_0_y0sgn),
    .a(s_fmul_ilog2_const_50db4625_0_a),
    .out_valid(),
    .y(s_fmul_ilog2_const_50db4625_0_y0)
);

holoso_fadd #(
    .WEXP(8), .WMAN(36), .STAGE_INPUT(0), .STAGE_DECODE(0), .STAGE_ALIGN(0), .STAGE_NORMALIZE(0), .STAGE_PACK(0), .STAGE_OUTPUT(0), .LATENCY(4)
) u_fadd_9eba50d4_0 (
    .clk(clk), .rst(rst), .in_valid(uc_issue_fadd_9eba50d4_0),
    .a_sgnop(uc_fadd_9eba50d4_0_asgn),
    .b_sgnop(uc_fadd_9eba50d4_0_bsgn),
    .y_sgnop(uc_fadd_9eba50d4_0_y0sgn),
    .a(s_fadd_9eba50d4_0_a),
    .b(s_fadd_9eba50d4_0_b),
    .out_valid(),
    .y(s_fadd_9eba50d4_0_y0)
);

holoso_fdiv #(
    .WEXP(8), .WMAN(36), .STAGE_INPUT(0), .STAGE_PACK(0), .STAGE_OUTPUT(0), .LATENCY(21)
) u_fdiv_56ea25b7_0 (
    .clk(clk), .rst(rst), .in_valid(uc_issue_fdiv_56ea25b7_0),
    .a_sgnop(uc_fdiv_56ea25b7_0_asgn),
    .b_sgnop(uc_fdiv_56ea25b7_0_bsgn),
    .y_sgnop(uc_fdiv_56ea25b7_0_y0sgn),
    .a(s_fdiv_56ea25b7_0_a),
    .b(s_fdiv_56ea25b7_0_b),
    .out_valid(),
    .y(s_fdiv_56ea25b7_0_y0),
    .div0(s_fdiv_56ea25b7_0_div0)
);

assign err = ((uc_op_r0 == 2'd2) & s_fdiv_56ea25b7_0_div0);

// Next-PC sequencer (combinational). The PC holds at the accept (pc==0) and present (pc==LASTPC) boundaries; bubble
// steps carry a NOP word and the PC keeps advancing. The executing step lags the fetch PC by FETCH_LAG. A block's
// terminator redirects the fetch PC at the block's boundary step (a branch reads its boolean register). Each branch
// also sets transacting_in -- 1 for a live accept/body word, 0 at the boundaries -- so each branch tags its own word.
always @* begin
    if (rst) begin
        next_pc        = 0;
        transacting_in = 1'b0;
    end else if (out_valid) begin  // present: hold until the result is taken
        next_pc        = out_ready ? 0 : LASTPC;
        transacting_in = 1'b0;
    end else if (in_ready) begin   // accept: hold until a transaction arrives
        next_pc        = in_valid ? 1 : 0;
        transacting_in = in_valid;
    end else begin                 // advance the fetch: the body of a live transaction
        transacting_in = 1'b1;
        next_pc        = pc + 1'b1;
    end
end

// Operand read muxes: a per-port case over the read codebook (registers and constants), driving the wrapper.
always @* begin
    case (uc_fmul_68b24f7b_0_ard)
        5'd0: s_fmul_68b24f7b_0_a = regs[0];
        5'd1: s_fmul_68b24f7b_0_a = regs[1];
        5'd2: s_fmul_68b24f7b_0_a = regs[2];
        5'd3: s_fmul_68b24f7b_0_a = regs[3];
        5'd4: s_fmul_68b24f7b_0_a = regs[6];
        5'd5: s_fmul_68b24f7b_0_a = regs[8];
        5'd6: s_fmul_68b24f7b_0_a = regs[9];
        5'd7: s_fmul_68b24f7b_0_a = regs[10];
        5'd8: s_fmul_68b24f7b_0_a = regs[11];
        5'd9: s_fmul_68b24f7b_0_a = regs[12];
        5'd10: s_fmul_68b24f7b_0_a = regs[13];
        5'd11: s_fmul_68b24f7b_0_a = regs[14];
        5'd12: s_fmul_68b24f7b_0_a = regs[15];
        5'd13: s_fmul_68b24f7b_0_a = regs[20];
        5'd14: s_fmul_68b24f7b_0_a = regs[21];
        5'd15: s_fmul_68b24f7b_0_a = regs[22];
        5'd16: s_fmul_68b24f7b_0_a = regs[26];
        5'd17: s_fmul_68b24f7b_0_a = regs[29];
        5'd18: s_fmul_68b24f7b_0_a = regs[32];
        5'd19: s_fmul_68b24f7b_0_a = regs[33];
        5'd20: s_fmul_68b24f7b_0_a = regs[34];
        5'd21: s_fmul_68b24f7b_0_a = const_2;
        5'd22: s_fmul_68b24f7b_0_a = const_1;
        5'd23: s_fmul_68b24f7b_0_a = const_0;
        5'd24: s_fmul_68b24f7b_0_a = const_3;
        default: s_fmul_68b24f7b_0_a = const_4;
    endcase
    case (uc_fmul_68b24f7b_0_brd)
        5'd0: s_fmul_68b24f7b_0_b = regs[0];
        5'd1: s_fmul_68b24f7b_0_b = regs[1];
        5'd2: s_fmul_68b24f7b_0_b = regs[3];
        5'd3: s_fmul_68b24f7b_0_b = regs[4];
        5'd4: s_fmul_68b24f7b_0_b = regs[5];
        5'd5: s_fmul_68b24f7b_0_b = regs[6];
        5'd6: s_fmul_68b24f7b_0_b = regs[7];
        5'd7: s_fmul_68b24f7b_0_b = regs[9];
        5'd8: s_fmul_68b24f7b_0_b = regs[10];
        5'd9: s_fmul_68b24f7b_0_b = regs[11];
        5'd10: s_fmul_68b24f7b_0_b = regs[13];
        5'd11: s_fmul_68b24f7b_0_b = regs[14];
        5'd12: s_fmul_68b24f7b_0_b = regs[16];
        5'd13: s_fmul_68b24f7b_0_b = regs[17];
        5'd14: s_fmul_68b24f7b_0_b = regs[18];
        5'd15: s_fmul_68b24f7b_0_b = regs[19];
        5'd16: s_fmul_68b24f7b_0_b = regs[21];
        5'd17: s_fmul_68b24f7b_0_b = regs[23];
        5'd18: s_fmul_68b24f7b_0_b = regs[24];
        5'd19: s_fmul_68b24f7b_0_b = regs[25];
        5'd20: s_fmul_68b24f7b_0_b = regs[31];
        5'd21: s_fmul_68b24f7b_0_b = regs[35];
        5'd22: s_fmul_68b24f7b_0_b = regs[36];
        5'd23: s_fmul_68b24f7b_0_b = regs[37];
        5'd24: s_fmul_68b24f7b_0_b = const_3;
        5'd25: s_fmul_68b24f7b_0_b = const_4;
        default: s_fmul_68b24f7b_0_b = const_0;
    endcase
    case (uc_fmul_ilog2_const_50db4625_0_ard)
        1'd0: s_fmul_ilog2_const_50db4625_0_a = regs[8];
        default: s_fmul_ilog2_const_50db4625_0_a = regs[10];
    endcase
    case (uc_fadd_9eba50d4_0_ard)
        5'd0: s_fadd_9eba50d4_0_a = regs[4];
        5'd1: s_fadd_9eba50d4_0_a = regs[6];
        5'd2: s_fadd_9eba50d4_0_a = regs[7];
        5'd3: s_fadd_9eba50d4_0_a = regs[8];
        5'd4: s_fadd_9eba50d4_0_a = regs[9];
        5'd5: s_fadd_9eba50d4_0_a = regs[11];
        5'd6: s_fadd_9eba50d4_0_a = regs[17];
        5'd7: s_fadd_9eba50d4_0_a = regs[20];
        5'd8: s_fadd_9eba50d4_0_a = regs[21];
        5'd9: s_fadd_9eba50d4_0_a = regs[22];
        5'd10: s_fadd_9eba50d4_0_a = regs[24];
        5'd11: s_fadd_9eba50d4_0_a = regs[26];
        5'd12: s_fadd_9eba50d4_0_a = regs[27];
        5'd13: s_fadd_9eba50d4_0_a = regs[28];
        5'd14: s_fadd_9eba50d4_0_a = regs[30];
        5'd15: s_fadd_9eba50d4_0_a = regs[39];
        5'd16: s_fadd_9eba50d4_0_a = const_4;
        default: s_fadd_9eba50d4_0_a = const_3;
    endcase
    case (uc_fadd_9eba50d4_0_brd)
        4'd0: s_fadd_9eba50d4_0_b = regs[1];
        4'd1: s_fadd_9eba50d4_0_b = regs[2];
        4'd2: s_fadd_9eba50d4_0_b = regs[5];
        4'd3: s_fadd_9eba50d4_0_b = regs[12];
        4'd4: s_fadd_9eba50d4_0_b = regs[19];
        4'd5: s_fadd_9eba50d4_0_b = regs[21];
        4'd6: s_fadd_9eba50d4_0_b = regs[22];
        4'd7: s_fadd_9eba50d4_0_b = regs[23];
        4'd8: s_fadd_9eba50d4_0_b = regs[24];
        4'd9: s_fadd_9eba50d4_0_b = regs[32];
        4'd10: s_fadd_9eba50d4_0_b = regs[33];
        4'd11: s_fadd_9eba50d4_0_b = regs[34];
        4'd12: s_fadd_9eba50d4_0_b = regs[35];
        4'd13: s_fadd_9eba50d4_0_b = regs[38];
        default: s_fadd_9eba50d4_0_b = const_0;
    endcase
    s_fdiv_56ea25b7_0_a = const_5;
    s_fdiv_56ea25b7_0_b = regs[26];
end

// All sequential logic in one clocked process. Reset gates only the control state (pc, err_pc_q, transacting_q) and the
// persistent state registers; every other register is reset-unconditional. Each is driven by exactly one statement.
always @(posedge clk) begin
    // Microcode fetch: PC latch; ucode_word pipelines ucode_q.
    ucode_addr_q <= next_pc;
    ucode_word   <= ucode_q;

    // Register writes (reset-unconditional): one opcode-selected statement per register.
    if (in_ready && in_valid) regs[0] <= in_dt;
    else case (uc_op_r0)
        2'd1: regs[0] <= s_fadd_9eba50d4_0_y0;
        2'd2: regs[0] <= s_fdiv_56ea25b7_0_y0;
    endcase
    if (in_ready && in_valid) regs[1] <= in_u_shunt;
    else case (uc_op_r1)
        2'd1: regs[1] <= s_fmul_68b24f7b_0_y0;
        2'd2: regs[1] <= s_fadd_9eba50d4_0_y0;
    endcase
    if (in_ready && in_valid) regs[2] <= in_di_dt;
    else case (uc_op_r2)
        2'd1: regs[2] <= s_fmul_68b24f7b_0_y0;
        2'd2: regs[2] <= s_fadd_9eba50d4_0_y0;
    endcase
    case (uc_op_r12)
        2'd1: regs[12] <= s_fmul_ilog2_const_50db4625_0_y0;
        2'd2: regs[12] <= s_fmul_68b24f7b_0_y0;
        2'd3: regs[12] <= s_fadd_9eba50d4_0_y0;
    endcase
    if (uc_op_r13) regs[13] <= s_fadd_9eba50d4_0_y0;
    case (uc_op_r14)
        2'd1: regs[14] <= s_fadd_9eba50d4_0_y0;
        2'd2: regs[14] <= s_fmul_ilog2_const_50db4625_0_y0;
    endcase
    if (uc_op_r15) regs[15] <= s_fmul_68b24f7b_0_y0;
    if (uc_op_r16) regs[16] <= s_fadd_9eba50d4_0_y0;
    if (uc_op_r17) regs[17] <= s_fmul_68b24f7b_0_y0;
    if (uc_op_r18) regs[18] <= s_fadd_9eba50d4_0_y0;
    if (uc_op_r19) regs[19] <= s_fmul_68b24f7b_0_y0;
    if (uc_op_r20) regs[20] <= s_fadd_9eba50d4_0_y0;
    case (uc_op_r21)
        2'd1: regs[21] <= s_fadd_9eba50d4_0_y0;
        2'd2: regs[21] <= s_fmul_68b24f7b_0_y0;
    endcase
    case (uc_op_r22)
        2'd1: regs[22] <= s_fmul_68b24f7b_0_y0;
        2'd2: regs[22] <= s_fadd_9eba50d4_0_y0;
    endcase
    if (uc_op_r23) regs[23] <= s_fmul_68b24f7b_0_y0;
    if (uc_op_r24) regs[24] <= s_fmul_68b24f7b_0_y0;
    if (uc_op_r25) regs[25] <= s_fadd_9eba50d4_0_y0;
    case (uc_op_r26)
        2'd1: regs[26] <= s_fadd_9eba50d4_0_y0;
        2'd2: regs[26] <= s_fmul_68b24f7b_0_y0;
    endcase
    case (uc_op_r27)
        2'd1: regs[27] <= s_fadd_9eba50d4_0_y0;
        2'd2: regs[27] <= s_fmul_68b24f7b_0_y0;
    endcase
    case (uc_op_r28)
        2'd1: regs[28] <= s_fadd_9eba50d4_0_y0;
        2'd2: regs[28] <= s_fmul_68b24f7b_0_y0;
    endcase
    if (uc_op_r29) regs[29] <= s_fmul_68b24f7b_0_y0;
    if (uc_op_r30) regs[30] <= s_fadd_9eba50d4_0_y0;
    if (uc_op_r31) regs[31] <= s_fmul_68b24f7b_0_y0;
    if (uc_op_r32) regs[32] <= s_fmul_68b24f7b_0_y0;
    if (uc_op_r33) regs[33] <= s_fmul_68b24f7b_0_y0;
    if (uc_op_r34) regs[34] <= s_fmul_68b24f7b_0_y0;
    if (uc_op_r35) regs[35] <= s_fmul_68b24f7b_0_y0;
    if (uc_op_r36) regs[36] <= s_fadd_9eba50d4_0_y0;
    if (uc_op_r37) regs[37] <= s_fadd_9eba50d4_0_y0;
    if (uc_op_r38) regs[38] <= s_fmul_68b24f7b_0_y0;
    if (uc_op_r39) regs[39] <= s_fadd_9eba50d4_0_y0;

    // Control and persistent state: the reset-gated registers.
    if (rst) begin
        pc            <= 0;
        err_pc_q      <= 0;
        transacting_q <= 0;
        regs[3] <= 44'h38d1b71758e;  // x_0 reset snapshot
        regs[4] <= 44'h00000000000;  // x_1 reset snapshot
        regs[5] <= 44'h00000000000;  // x_2 reset snapshot
        regs[6] <= 44'h447a0000000;  // P_urt_0 reset snapshot
        regs[7] <= 44'h00000000000;  // P_urt_1 reset snapshot
        regs[8] <= 44'h00000000000;  // P_urt_2 reset snapshot
        regs[9] <= 44'h49742400000;  // P_urt_3 reset snapshot
        regs[10] <= 44'h00000000000;  // P_urt_4 reset snapshot
        regs[11] <= 44'h3a83126e979;  // P_urt_5 reset snapshot
    end else begin
        pc <= next_pc;
        transacting_q <= (transacting_q << 1) | transacting_in;
        if (err) err_pc_q <= pc - FETCH_LAG;  // err wins; execution lags the fetch PC by FETCH_LAG, so step is pc-lag
        else if (in_ready && in_valid) err_pc_q <= 0;  // clear the diagnostic when a new transaction is accepted
        if (uc_op_r3) regs[3] <= s_fmul_68b24f7b_0_y0;
        if (uc_op_r4) regs[4] <= s_fmul_68b24f7b_0_y0;
        if (uc_op_r5) regs[5] <= s_fmul_68b24f7b_0_y0;
        case (uc_op_r6)
            2'd1: regs[6] <= s_fmul_68b24f7b_0_y0;
            2'd2: regs[6] <= s_fadd_9eba50d4_0_y0;
        endcase
        case (uc_op_r7)
            2'd1: regs[7] <= s_fadd_9eba50d4_0_y0;
            2'd2: regs[7] <= s_fmul_68b24f7b_0_y0;
        endcase
        if (uc_op_r8) regs[8] <= s_fmul_68b24f7b_0_y0;
        if (uc_op_r9) regs[9] <= s_fmul_68b24f7b_0_y0;
        if (uc_op_r10) regs[10] <= s_fmul_68b24f7b_0_y0;
        case (uc_op_r11)
            2'd1: regs[11] <= s_fadd_9eba50d4_0_y0;
            2'd2: regs[11] <= s_fmul_68b24f7b_0_y0;
        endcase
    end
end

assign in_ready  = (pc == 0);
assign out_valid = (pc == LASTPC);  // result valid on PRESENT; execution lags the fetch by FETCH_LAG
assign err_pc    = err_pc_q;
assign state_x_0 = regs[3];
assign state_x_1 = regs[4];
assign state_x_2 = regs[5];
assign state_P_urt_0 = regs[6];
assign state_P_urt_1 = regs[7];
assign state_P_urt_2 = regs[8];
assign state_P_urt_3 = regs[9];
assign state_P_urt_4 = regs[10];
assign state_P_urt_5 = regs[11];

endmodule
