// Generated by Holoso v<VERSION> <https://holoso.digital>.
// This file is generated output and is unencumbered: no copyright is claimed over it and no license terms apply.
// You may use, modify, and redistribute it freely, in open-source or proprietary designs, without restrictions.

`timescale 1ns/1ps

// Float format: exponent 8 bits, significand 36 bits, total 44 bits.
module from_polar (
    // CONTROL PORTS
    // Clock/reset and ready/valid handshake for one scheduled invocation.
    input  wire clk,
    input  wire rst,
    input  wire in_valid,
    output wire in_ready,
    output wire out_valid,
    input  wire out_ready,
    // INPUT PORTS
    // Latched when in_valid && in_ready.
    input  wire [43:0] in_v_0,
    input  wire [43:0] in_v_1,
    // OUTPUT/STATE PORTS
    // Valid when out_valid is pulsed. Publicly visible states are included here.
    output wire [43:0] out_0,
    output wire [43:0] out_1,
    // DIAGNOSTIC PORTS
    // Runtime diagnostics available while the module is running.
    output wire [5:0] err_pc
);

localparam           WEXP      =   8;  // Float exponent bits fixed by the static schedule
localparam           WMAN      =  36;  // Float mantissa bits fixed by the static schedule
localparam           W         = WEXP + WMAN;
localparam           NREG      =   4;
localparam           CYCW      =   6;  // err_pc width: enough for any executing step (0..present)
localparam           PCW       =   6;  // fetch-PC width: counts to LASTPC (execution lags the fetch by FETCH_LAG)
localparam           FETCH_LAG =   2;  // executing step = pc - FETCH_LAG (3-stage control fetch)
localparam [PCW-1:0] PRESENT   =  36;  // executing step on which the outputs are valid in the array
localparam [PCW-1:0] LASTPC    =  38;  // = PRESENT + FETCH_LAG; out_valid asserts here
localparam           UCW       =   9;  // microcode word width after lifting out constant control fields
// pc: 0 = idle/accept, present at executing step PRESENT; out_valid at pc==LASTPC (fetch leads execution).

// BEGIN holoso_support_inline.vh: the file is spliced into each generated module.

// Arithmetic shift by a constant. Positive shamt shifts left. For variable shamt use holoso_ashift.
function signed [W-1:0] holoso_ashiftc;
    input signed [W-1:0] x;
    input signed [W-1:0] shamt;
    reg signed [W:0] shamt_ext;
    reg [$clog2(W)-1:0] shamt_narrow;
    reg signed [W-1:0] shifted_left;
    reg signed [W-1:0] shifted_right;
    begin
        shamt_ext = {shamt[W-1], shamt};
        shamt_narrow = shamt[$clog2(W)-1:0];
        shifted_left = x << shamt_narrow;
        shifted_right = x >>> -shamt_narrow;
        if (shamt_ext >= W) begin
            holoso_ashiftc = {W{1'b0}};
        end else if (shamt_ext <= -W) begin
            holoso_ashiftc = {W{x[W-1]}};
        end else if (shamt[W-1]) begin
            holoso_ashiftc = shifted_right;
        end else begin
            holoso_ashiftc = shifted_left;
        end
    end
endfunction

// Combinational mapping from float to boolean: a zero or a subnormal (if supported) float is false, otherwise true.
// E.g., if IEEE 754 binary32 is used (with subnormals), values with magnitude under ~1e-38 are mapped to falsity.
function holoso_ftobool;
    input [W-1:0] x;
    holoso_ftobool = |x[W-2:WMAN-1];
endfunction

// Combinational mapping from boolean to float: falsity is zero, truth is one.
function [W-1:0] holoso_ffrombool;
    input b;
    holoso_ffrombool = b ? {2'b00, {(WEXP - 1) {1'b1}}, {(WMAN - 1) {1'b0}}} : {W{1'b0}};
endfunction

// Combinational predicate: y=1 iff x is finite (i.e., x is not an infinity).
function holoso_fisfinite;
    input [W-1:0] x;
    holoso_fisfinite = ~&x[W-2:WMAN-1];
endfunction

function holoso_fisposinf;
    input [W-1:0] x;
    holoso_fisposinf = ~holoso_fisfinite(x) & ~x[W-1];
endfunction

function holoso_fisneginf;
    input [W-1:0] x;
    holoso_fisneginf = ~holoso_fisfinite(x) & x[W-1];
endfunction

// Combinational saturator: replaces infinity with the largest finite value of the same sign; finite pass through.
function [W-1:0] holoso_fsaturate;
    input [W-1:0] x;
    holoso_fsaturate = (&x[W-2:WMAN-1]) ? {x[W-1], {(WEXP - 1) {1'b1}}, 1'b0, {(WMAN - 1) {1'b1}}} : x;
endfunction

// Combinational floating-point sign conditioner (absolute first, then optional negate): op[0]=negate, op[1]=absolute.
//      op=0: +x        op=1: -x        op=2: +|x|      op=3: -|x|
function [W-1:0] holoso_fsgnop;
    input [W-1:0] x;
    input [1:0]   op;
    holoso_fsgnop = {(x[W-1] & ~op[1]) ^ op[0], x[W-2:0]};
endfunction

// END of holoso_support_inline.vh

reg  [PCW-1:0]  pc;            // fetch program counter; the executing step lags it by FETCH_LAG
reg  [PCW-1:0]  next_pc;       // combinational next-state presented to the ROM each cycle
reg  [PCW-1:0]  ucode_addr_q;  // PC latch: splits pc -> next_pc -> ROM address for the case read
reg  [CYCW-1:0] err_pc_q;
wire            err;           // an operator error is detected on the current step

reg                 transacting_in;                           // per-branch tag: this pc's word is a live step
reg [FETCH_LAG-1:0] transacting_q;                            // delays the tag FETCH_LAG onto executing word
wire                transacting = transacting_q[FETCH_LAG-1]; // gates the executing word's effects

reg  [W-1:0] regs  [0:NREG-1];   // read-first: a write is visible next step

reg  [W-1:0] s_fmul_68b24f7b_0_a;
reg  [W-1:0] s_fmul_68b24f7b_0_b;
wire [W-1:0] s_fmul_68b24f7b_0_y0;
reg  [W-1:0] s_fsincos_47997380_0_a;
wire [W-1:0] s_fsincos_47997380_0_y0;
wire [W-1:0] s_fsincos_47997380_0_y1;

wire [W-1:0] const_0 = 44'h3e22f9836e5;  // 0.15915494309189535

// Microcode VLIW ROM.
reg [UCW-1:0] ucode_q;     // 2nd fetch stage
reg [UCW-1:0] ucode_word;  // 3rd fetch stage
// Microcode word field map:
//   [0]    uc_issue_fmul_68b24f7b_0
//   [1]    uc_fmul_68b24f7b_0_ard
//   [3:2]  uc_fmul_68b24f7b_0_brd
//   [4]    uc_issue_fsincos_47997380_0
//   [5]    uc_op_r1
//   [6]    uc_op_r3
//   [7]    uc_op_r2
//   [8]    uc_op_r0
(* rom_style = "block", syn_romstyle = "EBR" *)
always @(posedge clk)
    case (ucode_addr_q)
        0: ucode_q <= 9'h00b;  // issue r1=r1×c0
        1: ucode_q <= 9'h020;  // commit r1
        2: ucode_q <= 9'h010;  // issue r3/r2=sincos(r1)
        3: ucode_q <= 9'h000;
        4: ucode_q <= 9'h000;
        5: ucode_q <= 9'h000;
        6: ucode_q <= 9'h000;
        7: ucode_q <= 9'h000;
        8: ucode_q <= 9'h000;
        9: ucode_q <= 9'h000;
        10: ucode_q <= 9'h000;
        11: ucode_q <= 9'h000;
        12: ucode_q <= 9'h000;
        13: ucode_q <= 9'h000;
        14: ucode_q <= 9'h000;
        15: ucode_q <= 9'h000;
        16: ucode_q <= 9'h000;
        17: ucode_q <= 9'h000;
        18: ucode_q <= 9'h000;
        19: ucode_q <= 9'h000;
        20: ucode_q <= 9'h000;
        21: ucode_q <= 9'h000;
        22: ucode_q <= 9'h000;
        23: ucode_q <= 9'h000;
        24: ucode_q <= 9'h000;
        25: ucode_q <= 9'h000;
        26: ucode_q <= 9'h000;
        27: ucode_q <= 9'h000;
        28: ucode_q <= 9'h000;
        29: ucode_q <= 9'h000;
        30: ucode_q <= 9'h000;
        31: ucode_q <= 9'h000;
        32: ucode_q <= 9'h0c0;  // commit r3/r2
        33: ucode_q <= 9'h001;  // issue r1=r0×r2
        34: ucode_q <= 9'h025;  // issue r0=r0×r3; commit r1
        35: ucode_q <= 9'h100;  // commit r0
        36: ucode_q <= 9'h000;
        37: ucode_q <= 9'h000;
        38: ucode_q <= 9'h000;
        default: ucode_q <= 9'h0;  // unreached (PC bounded to LASTPC); NOP fill
    endcase

// Decoded control fields. A field constant across the whole program is driven by a constant net (so synthesis prunes
// the logic it feeds); a varying field is a slice of the instruction word. The effect-trigger fields -- the ``gated``
// ones (operator issue strobes and per-register write opcodes) -- are ANDed with `transacting` HERE, so a held
// ucode[0] dwell, a fill bubble, or a stale pre-reset word decodes to 0 (NOP): no issue and every register holds.
// The AND wraps the constant branch too, so the gate stays unconditional even if a trigger ever folds to a constant.
wire        uc_issue_fmul_68b24f7b_0 = transacting & ucode_word[0 +: 1];
wire [ 1:0] uc_fmul_68b24f7b_0_asgn = 2'd0;
wire        uc_fmul_68b24f7b_0_ard = ucode_word[1 +: 1];
wire [ 1:0] uc_fmul_68b24f7b_0_bsgn = 2'd0;
wire [ 1:0] uc_fmul_68b24f7b_0_brd = ucode_word[2 +: 2];
wire [ 1:0] uc_fmul_68b24f7b_0_y0sgn = 2'd0;
wire        uc_issue_fsincos_47997380_0 = transacting & ucode_word[4 +: 1];
wire [ 1:0] uc_fsincos_47997380_0_asgn = 2'd0;
wire [ 1:0] uc_fsincos_47997380_0_y0sgn = 2'd0;
wire [ 1:0] uc_fsincos_47997380_0_y1sgn = 2'd0;
wire        uc_op_r1 = transacting & ucode_word[5 +: 1];
wire        uc_op_r3 = transacting & ucode_word[6 +: 1];
wire        uc_op_r2 = transacting & ucode_word[7 +: 1];
wire        uc_op_r0 = transacting & ucode_word[8 +: 1];

holoso_fmul #(
    .WEXP(8), .WMAN(36), .WMULTIPLIER(0), .STAGE_INPUT(0), .STAGE_PRODUCT(0), .STAGE_PACK(0), .STAGE_OUTPUT(0), .LATENCY(1)
) u_fmul_68b24f7b_0 (
    .clk(clk), .rst(rst), .in_valid(uc_issue_fmul_68b24f7b_0),
    .a_sgnop(uc_fmul_68b24f7b_0_asgn),
    .b_sgnop(uc_fmul_68b24f7b_0_bsgn),
    .y_sgnop(uc_fmul_68b24f7b_0_y0sgn),
    .a(s_fmul_68b24f7b_0_a),
    .b(s_fmul_68b24f7b_0_b),
    .out_valid(),
    .y(s_fmul_68b24f7b_0_y0)
);

holoso_fsincos #(
    .WEXP(8), .WMAN(36), .WMULTIPLIER(0), .UNROLL100(100), .STAGE_INPUT(0), .STAGE_PRODUCT(0), .STAGE_NORMALIZE(0), .STAGE_PACK(0), .STAGE_OUTPUT(0), .LATENCY(30)
) u_fsincos_47997380_0 (
    .clk(clk), .rst(rst), .in_valid(uc_issue_fsincos_47997380_0),
    .a_sgnop(uc_fsincos_47997380_0_asgn),
    .sin_sgnop(uc_fsincos_47997380_0_y0sgn),
    .cos_sgnop(uc_fsincos_47997380_0_y1sgn),
    .a(s_fsincos_47997380_0_a),
    .out_valid(),
    .sin(s_fsincos_47997380_0_y0),
    .cos(s_fsincos_47997380_0_y1)
);

assign err = 1'b0;

// Next-PC sequencer (combinational). The PC holds at the accept (pc==0) and present (pc==LASTPC) boundaries; bubble
// steps carry a NOP word and the PC keeps advancing. The executing step lags the fetch PC by FETCH_LAG. A block's
// terminator redirects the fetch PC at the block's boundary step (a branch reads its boolean register). Each branch
// also sets transacting_in -- 1 for a live accept/body word, 0 at the boundaries -- so each branch tags its own word.
always @* begin
    if (rst) begin
        next_pc        = 0;
        transacting_in = 1'b0;
    end else if (out_valid) begin  // present: hold until the result is taken
        next_pc        = out_ready ? 0 : LASTPC;
        transacting_in = 1'b0;
    end else if (in_ready) begin   // accept: hold until a transaction arrives
        next_pc        = in_valid ? 1 : 0;
        transacting_in = in_valid;
    end else begin                 // advance the fetch: the body of a live transaction
        transacting_in = 1'b1;
        next_pc        = pc + 1'b1;
    end
end

// Operand read muxes: a per-port case over the read codebook (registers and constants), driving the wrapper.
always @* begin
    case (uc_fmul_68b24f7b_0_ard)
        1'd0: s_fmul_68b24f7b_0_a = regs[0];
        default: s_fmul_68b24f7b_0_a = regs[1];
    endcase
    case (uc_fmul_68b24f7b_0_brd)
        2'd0: s_fmul_68b24f7b_0_b = regs[2];
        2'd1: s_fmul_68b24f7b_0_b = regs[3];
        default: s_fmul_68b24f7b_0_b = const_0;
    endcase
    s_fsincos_47997380_0_a = regs[1];
end

// All sequential logic in one clocked process. Reset gates only the control state (pc, err_pc_q, transacting_q) and the
// persistent state registers; every other register is reset-unconditional. Each is driven by exactly one statement.
always @(posedge clk) begin
    // Microcode fetch: PC latch; ucode_word pipelines ucode_q.
    ucode_addr_q <= next_pc;
    ucode_word   <= ucode_q;

    // Register writes (reset-unconditional): one opcode-selected statement per register.
    if (in_ready && in_valid) regs[0] <= in_v_0;
    else if (uc_op_r0) regs[0] <= s_fmul_68b24f7b_0_y0;
    if (in_ready && in_valid) regs[1] <= in_v_1;
    else if (uc_op_r1) regs[1] <= s_fmul_68b24f7b_0_y0;
    if (uc_op_r2) regs[2] <= s_fsincos_47997380_0_y1;
    if (uc_op_r3) regs[3] <= s_fsincos_47997380_0_y0;

    // Control and persistent state: the reset-gated registers.
    if (rst) begin
        pc            <= 0;
        err_pc_q      <= 0;
        transacting_q <= 0;
    end else begin
        pc <= next_pc;
        transacting_q <= (transacting_q << 1) | transacting_in;
        if (err) err_pc_q <= pc - FETCH_LAG;  // err wins; execution lags the fetch PC by FETCH_LAG, so step is pc-lag
        else if (in_ready && in_valid) err_pc_q <= 0;  // clear the diagnostic when a new transaction is accepted
    end
end

assign in_ready  = (pc == 0);
assign out_valid = (pc == LASTPC);  // result valid on PRESENT; execution lags the fetch by FETCH_LAG
assign err_pc    = err_pc_q;
assign out_0 = regs[1];
assign out_1 = regs[0];

endmodule
