// Generated by Holoso v<VERSION> <https://holoso.digital>.
// This file is generated output and is unencumbered: no copyright is claimed over it and no license terms apply.
// You may use, modify, and redistribute it freely, in open-source or proprietary designs, without restrictions.

`timescale 1ns/1ps

// Float format: exponent 8 bits, significand 36 bits, total 44 bits.
module imu_frame_transform (
    // CONTROL PORTS
    // Clock/reset and ready/valid handshake for one scheduled invocation.
    input  wire clk,
    input  wire rst,
    input  wire in_valid,
    output wire in_ready,
    output wire out_valid,
    input  wire out_ready,
    // INPUT PORTS
    // Latched when in_valid && in_ready.
    input  wire [43:0] in_R_0_0,
    input  wire [43:0] in_R_0_1,
    input  wire [43:0] in_R_0_2,
    input  wire [43:0] in_R_1_0,
    input  wire [43:0] in_R_1_1,
    input  wire [43:0] in_R_1_2,
    input  wire [43:0] in_R_2_0,
    input  wire [43:0] in_R_2_1,
    input  wire [43:0] in_R_2_2,
    input  wire [43:0] in_t_0,
    input  wire [43:0] in_t_1,
    input  wire [43:0] in_t_2,
    input  wire [43:0] in_a_meas_0,
    input  wire [43:0] in_a_meas_1,
    input  wire [43:0] in_a_meas_2,
    input  wire [43:0] in_p_sensor_0,
    input  wire [43:0] in_p_sensor_1,
    input  wire [43:0] in_p_sensor_2,
    // OUTPUT/STATE PORTS
    // Valid when out_valid is pulsed. Publicly visible states are included here.
    output wire [43:0] out_0_0,
    output wire [43:0] out_0_1,
    output wire [43:0] out_0_2,
    output wire [43:0] out_1_0,
    output wire [43:0] out_1_1,
    output wire [43:0] out_1_2,
    output wire [43:0] out_2_0,
    output wire [43:0] out_2_1,
    output wire [43:0] out_2_2,
    // DIAGNOSTIC PORTS
    // Runtime diagnostics available while the module is running.
    output wire [5:0] err_pc
);

localparam           WEXP      =   8;  // Float exponent bits fixed by the static schedule
localparam           WMAN      =  36;  // Float mantissa bits fixed by the static schedule
localparam           W         = WEXP + WMAN;
localparam           NREG      =  20;
localparam           CYCW      =   6;  // err_pc width: enough for any executing step (0..present)
localparam           PCW       =   6;  // fetch-PC width: counts to LASTPC (execution lags the fetch by FETCH_LAG)
localparam           FETCH_LAG =   2;  // executing step = pc - FETCH_LAG (3-stage control fetch)
localparam [PCW-1:0] PRESENT   =  40;  // executing step on which the outputs are valid in the array
localparam [PCW-1:0] LASTPC    =  42;  // = PRESENT + FETCH_LAG; out_valid asserts here
localparam           UCW       =  34;  // microcode word width after lifting out constant control fields
// pc: 0 = idle/accept, present at executing step PRESENT; out_valid at pc==LASTPC (fetch leads execution).

// BEGIN holoso_support_inline.vh: the file is spliced into each generated module.

// Arithmetic shift by a constant. Positive shamt shifts left. For variable shamt use holoso_ashift.
function signed [W-1:0] holoso_ashiftc;
    input signed [W-1:0] x;
    input signed [W-1:0] shamt;
    reg signed [W:0] shamt_ext;
    reg [$clog2(W)-1:0] shamt_narrow;
    reg signed [W-1:0] shifted_left;
    reg signed [W-1:0] shifted_right;
    begin
        shamt_ext = {shamt[W-1], shamt};
        shamt_narrow = shamt[$clog2(W)-1:0];
        shifted_left = x << shamt_narrow;
        shifted_right = x >>> -shamt_narrow;
        if (shamt_ext >= W) begin
            holoso_ashiftc = {W{1'b0}};
        end else if (shamt_ext <= -W) begin
            holoso_ashiftc = {W{x[W-1]}};
        end else if (shamt[W-1]) begin
            holoso_ashiftc = shifted_right;
        end else begin
            holoso_ashiftc = shifted_left;
        end
    end
endfunction

// Combinational mapping from float to boolean: a zero or a subnormal (if supported) float is false, otherwise true.
// E.g., if IEEE 754 binary32 is used (with subnormals), values with magnitude under ~1e-38 are mapped to falsity.
function holoso_ftobool;
    input [W-1:0] x;
    holoso_ftobool = |x[W-2:WMAN-1];
endfunction

// Combinational mapping from boolean to float: falsity is zero, truth is one.
function [W-1:0] holoso_ffrombool;
    input b;
    holoso_ffrombool = b ? {2'b00, {(WEXP - 1) {1'b1}}, {(WMAN - 1) {1'b0}}} : {W{1'b0}};
endfunction

// Combinational predicate: y=1 iff x is finite (i.e., x is not an infinity).
function holoso_fisfinite;
    input [W-1:0] x;
    holoso_fisfinite = ~&x[W-2:WMAN-1];
endfunction

function holoso_fisposinf;
    input [W-1:0] x;
    holoso_fisposinf = ~holoso_fisfinite(x) & ~x[W-1];
endfunction

function holoso_fisneginf;
    input [W-1:0] x;
    holoso_fisneginf = ~holoso_fisfinite(x) & x[W-1];
endfunction

// Combinational saturator: replaces infinity with the largest finite value of the same sign; finite pass through.
function [W-1:0] holoso_fsaturate;
    input [W-1:0] x;
    holoso_fsaturate = (&x[W-2:WMAN-1]) ? {x[W-1], {(WEXP - 1) {1'b1}}, 1'b0, {(WMAN - 1) {1'b1}}} : x;
endfunction

// Combinational floating-point sign conditioner (absolute first, then optional negate): op[0]=negate, op[1]=absolute.
//      op=0: +x        op=1: -x        op=2: +|x|      op=3: -|x|
function [W-1:0] holoso_fsgnop;
    input [W-1:0] x;
    input [1:0]   op;
    holoso_fsgnop = {(x[W-1] & ~op[1]) ^ op[0], x[W-2:0]};
endfunction

// END of holoso_support_inline.vh

reg  [PCW-1:0]  pc;            // fetch program counter; the executing step lags it by FETCH_LAG
reg  [PCW-1:0]  next_pc;       // combinational next-state presented to the ROM each cycle
reg  [PCW-1:0]  ucode_addr_q;  // PC latch: splits pc -> next_pc -> ROM address for the case read
reg  [CYCW-1:0] err_pc_q;
wire            err;           // an operator error is detected on the current step

reg                 transacting_in;                           // per-branch tag: this pc's word is a live step
reg [FETCH_LAG-1:0] transacting_q;                            // delays the tag FETCH_LAG onto executing word
wire                transacting = transacting_q[FETCH_LAG-1]; // gates the executing word's effects

reg  [W-1:0] regs  [0:NREG-1];   // read-first: a write is visible next step

reg  [W-1:0] s_fmul_68b24f7b_0_a;
reg  [W-1:0] s_fmul_68b24f7b_0_b;
wire [W-1:0] s_fmul_68b24f7b_0_y0;
reg  [W-1:0] s_fadd_9eba50d4_0_a;
reg  [W-1:0] s_fadd_9eba50d4_0_b;
wire [W-1:0] s_fadd_9eba50d4_0_y0;

wire [W-1:0] const_0 = 44'h411ce809d49;  // 9.80665

// Microcode VLIW ROM.
reg [UCW-1:0] ucode_q;     // 2nd fetch stage
reg [UCW-1:0] ucode_word;  // 3rd fetch stage
// Microcode word field map:
//   [0]      uc_issue_fmul_68b24f7b_0
//   [2:1]    uc_fmul_68b24f7b_0_asgn
//   [6:3]    uc_fmul_68b24f7b_0_ard
//   [9:7]    uc_fmul_68b24f7b_0_brd
//   [10]     uc_issue_fadd_9eba50d4_0
//   [12:11]  uc_fadd_9eba50d4_0_asgn
//   [15:13]  uc_fadd_9eba50d4_0_ard
//   [17:16]  uc_fadd_9eba50d4_0_bsgn
//   [20:18]  uc_fadd_9eba50d4_0_brd
//   [22:21]  uc_op_r18
//   [23]     uc_op_r19
//   [24]     uc_op_r15
//   [25]     uc_op_r16
//   [26]     uc_op_r17
//   [27]     uc_op_r12
//   [28]     uc_op_r13
//   [29]     uc_op_r9
//   [30]     uc_op_r10
//   [31]     uc_op_r14
//   [32]     uc_op_r11
//   [33]     uc_op_r8
(* rom_style = "block", syn_romstyle = "EBR" *)
always @(posedge clk)
    case (ucode_addr_q)
        0: ucode_q <= 34'h000000189;  // issue r18=r1×r15
        1: ucode_q <= 34'h000200203;  // issue r19=-r0×r16; commit r18
        2: ucode_q <= 34'h0008001a1;  // issue r18=r4×r15; commit r19
        3: ucode_q <= 34'h00034c61b;  // issue r15=r18+r19, r19=-r3×r16; commit r18
        4: ucode_q <= 34'h000800291;  // issue r18=r2×r17; commit r19
        5: ucode_q <= 34'h00034c6a9;  // issue r15=r18+r19, r19=r5×r17; commit r18
        6: ucode_q <= 34'h0008001b9;  // issue r16=r7×r15; commit r19
        7: ucode_q <= 34'h003000233;  // issue r17=-r6×r16; commit r15, r16
        8: ucode_q <= 34'h0041086c1;  // issue r15=r15+r18, r16=r8×r17; commit r17
        9: ucode_q <= 34'h0030ca439;  // issue r12=r16+r17, r17=r7×r12; commit r15, r16
        10: ucode_q <= 34'h0041484b3;  // issue r13=r15+r19, r18=-r6×r13; commit r17
        11: ucode_q <= 34'h000200009;  // issue r17=r1×r12; commit r18
        12: ucode_q <= 34'h0050cc483;  // issue r18=r18+r17, r18=-r0×r13; commit r15, r17
        13: ucode_q <= 34'h008208421;  // issue r12=r15+r9, r16=r4×r12; commit r12, r18
        14: ucode_q <= 34'h01208449b;  // issue r9=r12+r16, r19=-r3×r13; commit r13, r16
        15: ucode_q <= 34'h000846541;  // issue r9=r13+r10, r17=r8×r14; commit r19
        16: ucode_q <= 34'h0044cc511;  // issue r10=r18+r17, r16=r2×r14; commit r18, r17
        17: ucode_q <= 34'h00a14a529;  // issue r13=r16+r19, r19=r5×r14; commit r12, r16
        18: ucode_q <= 34'h020814400;  // issue r14=r12+-r9; commit r9, r19
        19: ucode_q <= 34'h020002400;  // issue r10=r11+r9; commit r9
        20: ucode_q <= 34'h040050400;  // issue r13=r9+-r10; commit r10
        21: ucode_q <= 34'h0100cc400;  // issue r15=r18+r17; commit r13
        22: ucode_q <= 34'h08004a400;  // issue r11=r16+r10; commit r14
        23: ucode_q <= 34'h040146509;  // issue r14=r13+r19, r16=r1×r14; commit r10
        24: ucode_q <= 34'h012042d03;  // issue r15=-r11+r10, r18=-r0×r14; commit r13, r16
        25: ucode_q <= 34'h0012000a1;  // issue r17=r4×r13; commit r15, r18
        26: ucode_q <= 34'h10419849b;  // issue r13=r15+-c0, r16=-r3×r13; commit r11, r17
        27: ucode_q <= 34'h0820ca511;  // issue r15=r16+r17, r16=r2×r14; commit r14, r16
        28: ucode_q <= 34'h00308c4a9;  // issue r15=r18+r16, r17=r5×r13; commit r15, r16
        29: ucode_q <= 34'h0040001b9;  // issue r16=r7×r15; commit r17
        30: ucode_q <= 34'h0120ca5b3;  // issue r15=r16+r17, r17=-r6×r15; commit r13, r16
        31: ucode_q <= 34'h0050001c1;  // issue r16=r8×r15; commit r15, r17
        32: ucode_q <= 34'h003088400;  // issue r8=r15+r16; commit r15, r16
        33: ucode_q <= 34'h0000c8400;  // issue r18=r15+r17
        34: ucode_q <= 34'h001000000;  // commit r15
        35: ucode_q <= 34'h000088400;  // issue r15=r15+r16
        36: ucode_q <= 34'h200000000;  // commit r8
        37: ucode_q <= 34'h000400000;  // commit r18
        38: ucode_q <= 34'h000000000;
        39: ucode_q <= 34'h001000000;  // commit r15
        40: ucode_q <= 34'h000000000;
        41: ucode_q <= 34'h000000000;
        42: ucode_q <= 34'h000000000;
        default: ucode_q <= 34'h0;  // unreached (PC bounded to LASTPC); NOP fill
    endcase

// Decoded control fields. A field constant across the whole program is driven by a constant net (so synthesis prunes
// the logic it feeds); a varying field is a slice of the instruction word. The effect-trigger fields -- the ``gated``
// ones (operator issue strobes and per-register write opcodes) -- are ANDed with `transacting` HERE, so a held
// ucode[0] dwell, a fill bubble, or a stale pre-reset word decodes to 0 (NOP): no issue and every register holds.
// The AND wraps the constant branch too, so the gate stays unconditional even if a trigger ever folds to a constant.
wire        uc_issue_fmul_68b24f7b_0 = transacting & ucode_word[0 +: 1];
wire [ 1:0] uc_fmul_68b24f7b_0_asgn = ucode_word[1 +: 2];
wire [ 3:0] uc_fmul_68b24f7b_0_ard = ucode_word[3 +: 4];
wire [ 1:0] uc_fmul_68b24f7b_0_bsgn = 2'd0;
wire [ 2:0] uc_fmul_68b24f7b_0_brd = ucode_word[7 +: 3];
wire [ 1:0] uc_fmul_68b24f7b_0_y0sgn = 2'd0;
wire        uc_issue_fadd_9eba50d4_0 = transacting & ucode_word[10 +: 1];
wire [ 1:0] uc_fadd_9eba50d4_0_asgn = ucode_word[11 +: 2];
wire [ 2:0] uc_fadd_9eba50d4_0_ard = ucode_word[13 +: 3];
wire [ 1:0] uc_fadd_9eba50d4_0_bsgn = ucode_word[16 +: 2];
wire [ 2:0] uc_fadd_9eba50d4_0_brd = ucode_word[18 +: 3];
wire [ 1:0] uc_fadd_9eba50d4_0_y0sgn = 2'd0;
wire [ 1:0] uc_op_r18 = {2{transacting}} & ucode_word[21 +: 2];
wire        uc_op_r19 = transacting & ucode_word[23 +: 1];
wire        uc_op_r15 = transacting & ucode_word[24 +: 1];
wire        uc_op_r16 = transacting & ucode_word[25 +: 1];
wire        uc_op_r17 = transacting & ucode_word[26 +: 1];
wire        uc_op_r12 = transacting & ucode_word[27 +: 1];
wire        uc_op_r13 = transacting & ucode_word[28 +: 1];
wire        uc_op_r9 = transacting & ucode_word[29 +: 1];
wire        uc_op_r10 = transacting & ucode_word[30 +: 1];
wire        uc_op_r14 = transacting & ucode_word[31 +: 1];
wire        uc_op_r11 = transacting & ucode_word[32 +: 1];
wire        uc_op_r8 = transacting & ucode_word[33 +: 1];

holoso_fmul #(
    .WEXP(8), .WMAN(36), .WMULTIPLIER(0), .STAGE_INPUT(0), .STAGE_PRODUCT(0), .STAGE_PACK(0), .STAGE_OUTPUT(0), .LATENCY(1)
) u_fmul_68b24f7b_0 (
    .clk(clk), .rst(rst), .in_valid(uc_issue_fmul_68b24f7b_0),
    .a_sgnop(uc_fmul_68b24f7b_0_asgn),
    .b_sgnop(uc_fmul_68b24f7b_0_bsgn),
    .y_sgnop(uc_fmul_68b24f7b_0_y0sgn),
    .a(s_fmul_68b24f7b_0_a),
    .b(s_fmul_68b24f7b_0_b),
    .out_valid(),
    .y(s_fmul_68b24f7b_0_y0)
);

holoso_fadd #(
    .WEXP(8), .WMAN(36), .STAGE_INPUT(0), .STAGE_DECODE(0), .STAGE_ALIGN(0), .STAGE_NORMALIZE(0), .STAGE_PACK(0), .STAGE_OUTPUT(0), .LATENCY(4)
) u_fadd_9eba50d4_0 (
    .clk(clk), .rst(rst), .in_valid(uc_issue_fadd_9eba50d4_0),
    .a_sgnop(uc_fadd_9eba50d4_0_asgn),
    .b_sgnop(uc_fadd_9eba50d4_0_bsgn),
    .y_sgnop(uc_fadd_9eba50d4_0_y0sgn),
    .a(s_fadd_9eba50d4_0_a),
    .b(s_fadd_9eba50d4_0_b),
    .out_valid(),
    .y(s_fadd_9eba50d4_0_y0)
);

assign err = 1'b0;

// Next-PC sequencer (combinational). The PC holds at the accept (pc==0) and present (pc==LASTPC) boundaries; bubble
// steps carry a NOP word and the PC keeps advancing. The executing step lags the fetch PC by FETCH_LAG. A block's
// terminator redirects the fetch PC at the block's boundary step (a branch reads its boolean register). Each branch
// also sets transacting_in -- 1 for a live accept/body word, 0 at the boundaries -- so each branch tags its own word.
always @* begin
    if (rst) begin
        next_pc        = 0;
        transacting_in = 1'b0;
    end else if (out_valid) begin  // present: hold until the result is taken
        next_pc        = out_ready ? 0 : LASTPC;
        transacting_in = 1'b0;
    end else if (in_ready) begin   // accept: hold until a transaction arrives
        next_pc        = in_valid ? 1 : 0;
        transacting_in = in_valid;
    end else begin                 // advance the fetch: the body of a live transaction
        transacting_in = 1'b1;
        next_pc        = pc + 1'b1;
    end
end

// Operand read muxes: a per-port case over the read codebook (registers and constants), driving the wrapper.
always @* begin
    case (uc_fmul_68b24f7b_0_ard)
        4'd0: s_fmul_68b24f7b_0_a = regs[0];
        4'd1: s_fmul_68b24f7b_0_a = regs[1];
        4'd2: s_fmul_68b24f7b_0_a = regs[2];
        4'd3: s_fmul_68b24f7b_0_a = regs[3];
        4'd4: s_fmul_68b24f7b_0_a = regs[4];
        4'd5: s_fmul_68b24f7b_0_a = regs[5];
        4'd6: s_fmul_68b24f7b_0_a = regs[6];
        4'd7: s_fmul_68b24f7b_0_a = regs[7];
        default: s_fmul_68b24f7b_0_a = regs[8];
    endcase
    case (uc_fmul_68b24f7b_0_brd)
        3'd0: s_fmul_68b24f7b_0_b = regs[12];
        3'd1: s_fmul_68b24f7b_0_b = regs[13];
        3'd2: s_fmul_68b24f7b_0_b = regs[14];
        3'd3: s_fmul_68b24f7b_0_b = regs[15];
        3'd4: s_fmul_68b24f7b_0_b = regs[16];
        default: s_fmul_68b24f7b_0_b = regs[17];
    endcase
    case (uc_fadd_9eba50d4_0_ard)
        3'd0: s_fadd_9eba50d4_0_a = regs[9];
        3'd1: s_fadd_9eba50d4_0_a = regs[11];
        3'd2: s_fadd_9eba50d4_0_a = regs[12];
        3'd3: s_fadd_9eba50d4_0_a = regs[13];
        3'd4: s_fadd_9eba50d4_0_a = regs[15];
        3'd5: s_fadd_9eba50d4_0_a = regs[16];
        default: s_fadd_9eba50d4_0_a = regs[18];
    endcase
    case (uc_fadd_9eba50d4_0_brd)
        3'd0: s_fadd_9eba50d4_0_b = regs[9];
        3'd1: s_fadd_9eba50d4_0_b = regs[10];
        3'd2: s_fadd_9eba50d4_0_b = regs[16];
        3'd3: s_fadd_9eba50d4_0_b = regs[17];
        3'd4: s_fadd_9eba50d4_0_b = regs[18];
        3'd5: s_fadd_9eba50d4_0_b = regs[19];
        default: s_fadd_9eba50d4_0_b = const_0;
    endcase
end

// All sequential logic in one clocked process. Reset gates only the control state (pc, err_pc_q, transacting_q) and the
// persistent state registers; every other register is reset-unconditional. Each is driven by exactly one statement.
always @(posedge clk) begin
    // Microcode fetch: PC latch; ucode_word pipelines ucode_q.
    ucode_addr_q <= next_pc;
    ucode_word   <= ucode_q;

    // Register writes (reset-unconditional): one opcode-selected statement per register.
    if (in_ready && in_valid) regs[0] <= in_R_0_0;
    if (in_ready && in_valid) regs[1] <= in_R_0_1;
    if (in_ready && in_valid) regs[2] <= in_R_0_2;
    if (in_ready && in_valid) regs[3] <= in_R_1_0;
    if (in_ready && in_valid) regs[4] <= in_R_1_1;
    if (in_ready && in_valid) regs[5] <= in_R_1_2;
    if (in_ready && in_valid) regs[6] <= in_R_2_0;
    if (in_ready && in_valid) regs[7] <= in_R_2_1;
    if (in_ready && in_valid) regs[8] <= in_R_2_2;
    else if (uc_op_r8) regs[8] <= s_fadd_9eba50d4_0_y0;
    if (in_ready && in_valid) regs[9] <= in_t_0;
    else if (uc_op_r9) regs[9] <= s_fadd_9eba50d4_0_y0;
    if (in_ready && in_valid) regs[10] <= in_t_1;
    else if (uc_op_r10) regs[10] <= s_fadd_9eba50d4_0_y0;
    if (in_ready && in_valid) regs[11] <= in_t_2;
    else if (uc_op_r11) regs[11] <= s_fadd_9eba50d4_0_y0;
    if (in_ready && in_valid) regs[12] <= in_a_meas_0;
    else if (uc_op_r12) regs[12] <= s_fadd_9eba50d4_0_y0;
    if (in_ready && in_valid) regs[13] <= in_a_meas_1;
    else if (uc_op_r13) regs[13] <= s_fadd_9eba50d4_0_y0;
    if (in_ready && in_valid) regs[14] <= in_a_meas_2;
    else if (uc_op_r14) regs[14] <= s_fadd_9eba50d4_0_y0;
    if (in_ready && in_valid) regs[15] <= in_p_sensor_0;
    else if (uc_op_r15) regs[15] <= s_fadd_9eba50d4_0_y0;
    if (in_ready && in_valid) regs[16] <= in_p_sensor_1;
    else if (uc_op_r16) regs[16] <= s_fmul_68b24f7b_0_y0;
    if (in_ready && in_valid) regs[17] <= in_p_sensor_2;
    else if (uc_op_r17) regs[17] <= s_fmul_68b24f7b_0_y0;
    case (uc_op_r18)
        2'd1: regs[18] <= s_fmul_68b24f7b_0_y0;
        2'd2: regs[18] <= s_fadd_9eba50d4_0_y0;
    endcase
    if (uc_op_r19) regs[19] <= s_fmul_68b24f7b_0_y0;

    // Control and persistent state: the reset-gated registers.
    if (rst) begin
        pc            <= 0;
        err_pc_q      <= 0;
        transacting_q <= 0;
    end else begin
        pc <= next_pc;
        transacting_q <= (transacting_q << 1) | transacting_in;
        if (err) err_pc_q <= pc - FETCH_LAG;  // err wins; execution lags the fetch PC by FETCH_LAG, so step is pc-lag
        else if (in_ready && in_valid) err_pc_q <= 0;  // clear the diagnostic when a new transaction is accepted
    end
end

assign in_ready  = (pc == 0);
assign out_valid = (pc == LASTPC);  // result valid on PRESENT; execution lags the fetch by FETCH_LAG
assign err_pc    = err_pc_q;
assign out_0_0 = regs[12];
assign out_0_1 = regs[9];
assign out_0_2 = regs[10];
assign out_1_0 = regs[11];
assign out_1_1 = regs[14];
assign out_1_2 = regs[13];
assign out_2_0 = regs[8];
assign out_2_1 = regs[18];
assign out_2_2 = regs[15];

endmodule
