// Generated by Holoso v<VERSION> <https://holoso.digital>.
// This file is generated output and is unencumbered: no copyright is claimed over it and no license terms apply.
// You may use, modify, and redistribute it freely, in open-source or proprietary designs, without restrictions.

`timescale 1ns/1ps

// Float format: exponent 8 bits, significand 36 bits, total 44 bits.
module kepler (
    // CONTROL PORTS
    // Clock/reset and ready/valid handshake for one scheduled invocation.
    input  wire clk,
    input  wire rst,
    input  wire in_valid,
    output wire in_ready,
    output wire out_valid,
    input  wire out_ready,
    // INPUT PORTS
    // Latched when in_valid && in_ready.
    input  wire [43:0] in_mean_anomaly,
    input  wire [43:0] in_eccentricity,
    // OUTPUT/STATE PORTS
    // Valid when out_valid is pulsed. Publicly visible states are included here.
    output wire [43:0] out_0,
    // DIAGNOSTIC PORTS
    // Runtime diagnostics available while the module is running.
    output wire [6:0] err_pc
);

localparam           WEXP      =   8;  // Float exponent bits fixed by the static schedule
localparam           WMAN      =  36;  // Float mantissa bits fixed by the static schedule
localparam           W         = WEXP + WMAN;
localparam           NREG      =   7;
localparam           CYCW      =   7;  // err_pc width: enough for any executing step (0..present)
localparam           PCW       =   7;  // fetch-PC width: counts to LASTPC (execution lags the fetch by FETCH_LAG)
localparam           FETCH_LAG =   2;  // executing step = pc - FETCH_LAG (3-stage control fetch)
localparam [PCW-1:0] PRESENT   =  82;  // executing step on which the outputs are valid in the array
localparam [PCW-1:0] LASTPC    =  84;  // = PRESENT + FETCH_LAG; out_valid asserts here
localparam           UCW       =  22;  // microcode word width after lifting out constant control fields
localparam           NBREG     =   1;
// pc: 0 = idle/accept, present at executing step PRESENT; out_valid at pc==LASTPC (fetch leads execution).

// BEGIN holoso_support_inline.vh: the file is spliced into each generated module.

// Arithmetic shift by a constant. Positive shamt shifts left. For variable shamt use holoso_ashift.
function signed [W-1:0] holoso_ashiftc;
    input signed [W-1:0] x;
    input signed [W-1:0] shamt;
    reg signed [W:0] shamt_ext;
    reg [$clog2(W)-1:0] shamt_narrow;
    reg signed [W-1:0] shifted_left;
    reg signed [W-1:0] shifted_right;
    begin
        shamt_ext = {shamt[W-1], shamt};
        shamt_narrow = shamt[$clog2(W)-1:0];
        shifted_left = x << shamt_narrow;
        shifted_right = x >>> -shamt_narrow;
        if (shamt_ext >= W) begin
            holoso_ashiftc = {W{1'b0}};
        end else if (shamt_ext <= -W) begin
            holoso_ashiftc = {W{x[W-1]}};
        end else if (shamt[W-1]) begin
            holoso_ashiftc = shifted_right;
        end else begin
            holoso_ashiftc = shifted_left;
        end
    end
endfunction

// Combinational mapping from float to boolean: a zero or a subnormal (if supported) float is false, otherwise true.
// E.g., if IEEE 754 binary32 is used (with subnormals), values with magnitude under ~1e-38 are mapped to falsity.
function holoso_ftobool;
    input [W-1:0] x;
    holoso_ftobool = |x[W-2:WMAN-1];
endfunction

// Combinational mapping from boolean to float: falsity is zero, truth is one.
function [W-1:0] holoso_ffrombool;
    input b;
    holoso_ffrombool = b ? {2'b00, {(WEXP - 1) {1'b1}}, {(WMAN - 1) {1'b0}}} : {W{1'b0}};
endfunction

// Combinational predicate: y=1 iff x is finite (i.e., x is not an infinity).
function holoso_fisfinite;
    input [W-1:0] x;
    holoso_fisfinite = ~&x[W-2:WMAN-1];
endfunction

function holoso_fisposinf;
    input [W-1:0] x;
    holoso_fisposinf = ~holoso_fisfinite(x) & ~x[W-1];
endfunction

function holoso_fisneginf;
    input [W-1:0] x;
    holoso_fisneginf = ~holoso_fisfinite(x) & x[W-1];
endfunction

// Combinational saturator: replaces infinity with the largest finite value of the same sign; finite pass through.
function [W-1:0] holoso_fsaturate;
    input [W-1:0] x;
    holoso_fsaturate = (&x[W-2:WMAN-1]) ? {x[W-1], {(WEXP - 1) {1'b1}}, 1'b0, {(WMAN - 1) {1'b1}}} : x;
endfunction

// Combinational floating-point sign conditioner (absolute first, then optional negate): op[0]=negate, op[1]=absolute.
//      op=0: +x        op=1: -x        op=2: +|x|      op=3: -|x|
function [W-1:0] holoso_fsgnop;
    input [W-1:0] x;
    input [1:0]   op;
    holoso_fsgnop = {(x[W-1] & ~op[1]) ^ op[0], x[W-2:0]};
endfunction

// END of holoso_support_inline.vh

reg  [PCW-1:0]  pc;            // fetch program counter; the executing step lags it by FETCH_LAG
reg  [PCW-1:0]  next_pc;       // combinational next-state presented to the ROM each cycle
reg  [PCW-1:0]  ucode_addr_q;  // PC latch: splits pc -> next_pc -> ROM address for the case read
reg  [CYCW-1:0] err_pc_q;
wire            err;           // an operator error is detected on the current step

reg                 transacting_in;                           // per-branch tag: this pc's word is a live step
reg [FETCH_LAG-1:0] transacting_q;                            // delays the tag FETCH_LAG onto executing word
wire                transacting = transacting_q[FETCH_LAG-1]; // gates the executing word's effects

reg  [W-1:0] regs  [0:NREG-1];   // read-first: a write is visible next step
reg          bregs [0:NBREG-1];

reg  [W-1:0] s_fcmp_63b877a8_0_a;
reg  [W-1:0] s_fcmp_63b877a8_0_b;
wire         s_fcmp_63b877a8_0_y0;
reg  [W-1:0] s_fmul_68b24f7b_0_a;
reg  [W-1:0] s_fmul_68b24f7b_0_b;
wire [W-1:0] s_fmul_68b24f7b_0_y0;
reg  [W-1:0] s_fsincos_47997380_0_a;
wire [W-1:0] s_fsincos_47997380_0_y0;
wire [W-1:0] s_fsincos_47997380_0_y1;
reg  [W-1:0] s_fadd_9eba50d4_0_a;
reg  [W-1:0] s_fadd_9eba50d4_0_b;
wire [W-1:0] s_fadd_9eba50d4_0_y0;
reg  [W-1:0] s_fdiv_56ea25b7_0_a;
reg  [W-1:0] s_fdiv_56ea25b7_0_b;
wire [W-1:0] s_fdiv_56ea25b7_0_y0;
wire         s_fdiv_56ea25b7_0_div0;

wire [W-1:0] const_0 = 44'h3f800000000;  // 1.0
wire [W-1:0] const_1 = 44'h3e22f9836e5;  // 0.15915494309189535
wire [W-1:0] const_2 = 44'h39800000000;  // 0.000244140625

// Microcode VLIW ROM.
reg [UCW-1:0] ucode_q;     // 2nd fetch stage
reg [UCW-1:0] ucode_word;  // 3rd fetch stage
// Microcode word field map:
//   [0]      uc_issue_fcmp_63b877a8_0
//   [1]      uc_issue_fmul_68b24f7b_0
//   [2]      uc_fmul_68b24f7b_0_ard
//   [4:3]    uc_fmul_68b24f7b_0_brd
//   [5]      uc_issue_fsincos_47997380_0
//   [6]      uc_issue_fadd_9eba50d4_0
//   [8:7]    uc_fadd_9eba50d4_0_ard
//   [10:9]   uc_fadd_9eba50d4_0_brd
//   [11]     uc_issue_fdiv_56ea25b7_0
//   [12]     uc_op_b0
//   [14:13]  uc_op_r4
//   [16:15]  uc_op_r5
//   [17]     uc_op_r6
//   [19:18]  uc_op_r2
//   [21:20]  uc_op_r3
(* rom_style = "block", syn_romstyle = "EBR" *)
always @(posedge clk)
    case (ucode_addr_q)
        0: ucode_q <= 22'h280000;  // land r2=c0, r3=r0
        1: ucode_q <= 22'h000000;
        2: ucode_q <= 22'h000000;
        3: ucode_q <= 22'h000000;
        4: ucode_q <= 22'h000001;  // issue b0=cmp(|r2|,c2)
        5: ucode_q <= 22'h001000;  // commit b0
        6: ucode_q <= 22'h000000;
        7: ucode_q <= 22'h000000;
        8: ucode_q <= 22'h000000;
        9: ucode_q <= 22'h000016;  // issue r4=r3×c1
        10: ucode_q <= 22'h002000;  // commit r4
        11: ucode_q <= 22'h000020;  // issue r4/r5=sincos(r4)
        12: ucode_q <= 22'h000000;
        13: ucode_q <= 22'h000000;
        14: ucode_q <= 22'h000000;
        15: ucode_q <= 22'h000000;
        16: ucode_q <= 22'h000000;
        17: ucode_q <= 22'h000000;
        18: ucode_q <= 22'h000000;
        19: ucode_q <= 22'h000000;
        20: ucode_q <= 22'h000000;
        21: ucode_q <= 22'h000000;
        22: ucode_q <= 22'h000000;
        23: ucode_q <= 22'h000000;
        24: ucode_q <= 22'h000000;
        25: ucode_q <= 22'h000000;
        26: ucode_q <= 22'h000000;
        27: ucode_q <= 22'h000000;
        28: ucode_q <= 22'h000000;
        29: ucode_q <= 22'h000000;
        30: ucode_q <= 22'h000000;
        31: ucode_q <= 22'h000000;
        32: ucode_q <= 22'h000000;
        33: ucode_q <= 22'h000000;
        34: ucode_q <= 22'h000000;
        35: ucode_q <= 22'h000000;
        36: ucode_q <= 22'h000000;
        37: ucode_q <= 22'h000000;
        38: ucode_q <= 22'h000000;
        39: ucode_q <= 22'h000000;
        40: ucode_q <= 22'h000000;
        41: ucode_q <= 22'h00c000;  // commit r4/r5
        42: ucode_q <= 22'h000002;  // issue r4=r1×r4
        43: ucode_q <= 22'h00200a;  // issue r4=r1×r5; commit r4
        44: ucode_q <= 22'h002440;  // issue r5=r3+-r4; commit r4
        45: ucode_q <= 22'h000540;  // issue r5=c0+-r4
        46: ucode_q <= 22'h000000;
        47: ucode_q <= 22'h000000;
        48: ucode_q <= 22'h010000;  // commit r5
        49: ucode_q <= 22'h0100c0;  // issue r6=r5+-r0; commit r5
        50: ucode_q <= 22'h000000;
        51: ucode_q <= 22'h000000;
        52: ucode_q <= 22'h000000;
        53: ucode_q <= 22'h020000;  // commit r6
        54: ucode_q <= 22'h000800;  // issue r2=r6/r5
        55: ucode_q <= 22'h000000;
        56: ucode_q <= 22'h000000;
        57: ucode_q <= 22'h000000;
        58: ucode_q <= 22'h000000;
        59: ucode_q <= 22'h000000;
        60: ucode_q <= 22'h000000;
        61: ucode_q <= 22'h000000;
        62: ucode_q <= 22'h000000;
        63: ucode_q <= 22'h000000;
        64: ucode_q <= 22'h000000;
        65: ucode_q <= 22'h000000;
        66: ucode_q <= 22'h000000;
        67: ucode_q <= 22'h000000;
        68: ucode_q <= 22'h000000;
        69: ucode_q <= 22'h000000;
        70: ucode_q <= 22'h000000;
        71: ucode_q <= 22'h000000;
        72: ucode_q <= 22'h000000;
        73: ucode_q <= 22'h000000;
        74: ucode_q <= 22'h000000;
        75: ucode_q <= 22'h040000;  // commit r2
        76: ucode_q <= 22'h000240;  // issue r3=r3+-r2
        77: ucode_q <= 22'h000000;
        78: ucode_q <= 22'h000000;
        79: ucode_q <= 22'h000000;
        80: ucode_q <= 22'h100000;  // commit r3
        81: ucode_q <= 22'h000000;
        82: ucode_q <= 22'h000000;
        83: ucode_q <= 22'h000000;
        84: ucode_q <= 22'h000000;
        default: ucode_q <= 22'h0;  // unreached (PC bounded to LASTPC); NOP fill
    endcase

// Decoded control fields. A field constant across the whole program is driven by a constant net (so synthesis prunes
// the logic it feeds); a varying field is a slice of the instruction word. The effect-trigger fields -- the ``gated``
// ones (operator issue strobes and per-register write opcodes) -- are ANDed with `transacting` HERE, so a held
// ucode[0] dwell, a fill bubble, or a stale pre-reset word decodes to 0 (NOP): no issue and every register holds.
// The AND wraps the constant branch too, so the gate stays unconditional even if a trigger ever folds to a constant.
wire        uc_issue_fcmp_63b877a8_0 = transacting & ucode_word[0 +: 1];
wire [ 1:0] uc_fcmp_63b877a8_0_asgn = 2'd2;
wire [ 1:0] uc_fcmp_63b877a8_0_bsgn = 2'd0;
wire        uc_issue_fmul_68b24f7b_0 = transacting & ucode_word[1 +: 1];
wire [ 1:0] uc_fmul_68b24f7b_0_asgn = 2'd0;
wire        uc_fmul_68b24f7b_0_ard = ucode_word[2 +: 1];
wire [ 1:0] uc_fmul_68b24f7b_0_bsgn = 2'd0;
wire [ 1:0] uc_fmul_68b24f7b_0_brd = ucode_word[3 +: 2];
wire [ 1:0] uc_fmul_68b24f7b_0_y0sgn = 2'd0;
wire        uc_issue_fsincos_47997380_0 = transacting & ucode_word[5 +: 1];
wire [ 1:0] uc_fsincos_47997380_0_asgn = 2'd0;
wire [ 1:0] uc_fsincos_47997380_0_y0sgn = 2'd0;
wire [ 1:0] uc_fsincos_47997380_0_y1sgn = 2'd0;
wire        uc_issue_fadd_9eba50d4_0 = transacting & ucode_word[6 +: 1];
wire [ 1:0] uc_fadd_9eba50d4_0_asgn = 2'd0;
wire [ 1:0] uc_fadd_9eba50d4_0_ard = ucode_word[7 +: 2];
wire [ 1:0] uc_fadd_9eba50d4_0_bsgn = 2'd1;
wire [ 1:0] uc_fadd_9eba50d4_0_brd = ucode_word[9 +: 2];
wire [ 1:0] uc_fadd_9eba50d4_0_y0sgn = 2'd0;
wire        uc_issue_fdiv_56ea25b7_0 = transacting & ucode_word[11 +: 1];
wire [ 1:0] uc_fdiv_56ea25b7_0_asgn = 2'd0;
wire [ 1:0] uc_fdiv_56ea25b7_0_bsgn = 2'd0;
wire [ 1:0] uc_fdiv_56ea25b7_0_y0sgn = 2'd0;
wire        uc_op_b0 = transacting & ucode_word[12 +: 1];
wire [ 1:0] uc_op_r4 = {2{transacting}} & ucode_word[13 +: 2];
wire [ 1:0] uc_op_r5 = {2{transacting}} & ucode_word[15 +: 2];
wire        uc_op_r6 = transacting & ucode_word[17 +: 1];
wire [ 1:0] uc_op_r2 = {2{transacting}} & ucode_word[18 +: 2];
wire [ 1:0] uc_op_r3 = {2{transacting}} & ucode_word[20 +: 2];

holoso_fcmp #(
    .WEXP(8), .WMAN(36), .STAGE_INPUT(0), .LATENCY(1)
) u_fcmp_63b877a8_0 (
    .clk(clk), .rst(rst), .in_valid(uc_issue_fcmp_63b877a8_0),
    .a_sgnop(uc_fcmp_63b877a8_0_asgn),
    .b_sgnop(uc_fcmp_63b877a8_0_bsgn),
    .a(s_fcmp_63b877a8_0_a),
    .b(s_fcmp_63b877a8_0_b),
    .out_valid(),
    .a_gt_b(s_fcmp_63b877a8_0_y0),
    .a_eq_b(),
    .a_lt_b()
);

holoso_fmul #(
    .WEXP(8), .WMAN(36), .WMULTIPLIER(0), .STAGE_INPUT(0), .STAGE_PRODUCT(0), .STAGE_PACK(0), .STAGE_OUTPUT(0), .LATENCY(1)
) u_fmul_68b24f7b_0 (
    .clk(clk), .rst(rst), .in_valid(uc_issue_fmul_68b24f7b_0),
    .a_sgnop(uc_fmul_68b24f7b_0_asgn),
    .b_sgnop(uc_fmul_68b24f7b_0_bsgn),
    .y_sgnop(uc_fmul_68b24f7b_0_y0sgn),
    .a(s_fmul_68b24f7b_0_a),
    .b(s_fmul_68b24f7b_0_b),
    .out_valid(),
    .y(s_fmul_68b24f7b_0_y0)
);

holoso_fsincos #(
    .WEXP(8), .WMAN(36), .WMULTIPLIER(0), .UNROLL100(100), .STAGE_INPUT(0), .STAGE_PRODUCT(0), .STAGE_NORMALIZE(0), .STAGE_PACK(0), .STAGE_OUTPUT(0), .LATENCY(30)
) u_fsincos_47997380_0 (
    .clk(clk), .rst(rst), .in_valid(uc_issue_fsincos_47997380_0),
    .a_sgnop(uc_fsincos_47997380_0_asgn),
    .sin_sgnop(uc_fsincos_47997380_0_y0sgn),
    .cos_sgnop(uc_fsincos_47997380_0_y1sgn),
    .a(s_fsincos_47997380_0_a),
    .out_valid(),
    .sin(s_fsincos_47997380_0_y0),
    .cos(s_fsincos_47997380_0_y1)
);

holoso_fadd #(
    .WEXP(8), .WMAN(36), .STAGE_INPUT(0), .STAGE_DECODE(0), .STAGE_ALIGN(0), .STAGE_NORMALIZE(0), .STAGE_PACK(0), .STAGE_OUTPUT(0), .LATENCY(4)
) u_fadd_9eba50d4_0 (
    .clk(clk), .rst(rst), .in_valid(uc_issue_fadd_9eba50d4_0),
    .a_sgnop(uc_fadd_9eba50d4_0_asgn),
    .b_sgnop(uc_fadd_9eba50d4_0_bsgn),
    .y_sgnop(uc_fadd_9eba50d4_0_y0sgn),
    .a(s_fadd_9eba50d4_0_a),
    .b(s_fadd_9eba50d4_0_b),
    .out_valid(),
    .y(s_fadd_9eba50d4_0_y0)
);

holoso_fdiv #(
    .WEXP(8), .WMAN(36), .STAGE_INPUT(0), .STAGE_PACK(0), .STAGE_OUTPUT(0), .LATENCY(21)
) u_fdiv_56ea25b7_0 (
    .clk(clk), .rst(rst), .in_valid(uc_issue_fdiv_56ea25b7_0),
    .a_sgnop(uc_fdiv_56ea25b7_0_asgn),
    .b_sgnop(uc_fdiv_56ea25b7_0_bsgn),
    .y_sgnop(uc_fdiv_56ea25b7_0_y0sgn),
    .a(s_fdiv_56ea25b7_0_a),
    .b(s_fdiv_56ea25b7_0_b),
    .out_valid(),
    .y(s_fdiv_56ea25b7_0_y0),
    .div0(s_fdiv_56ea25b7_0_div0)
);

assign err = ((uc_op_r2 == 2'd1) & s_fdiv_56ea25b7_0_div0);

// Next-PC sequencer (combinational). The PC holds at the accept (pc==0) and present (pc==LASTPC) boundaries; bubble
// steps carry a NOP word and the PC keeps advancing. The executing step lags the fetch PC by FETCH_LAG. A block's
// terminator redirects the fetch PC at the block's boundary step (a branch reads its boolean register). Each branch
// also sets transacting_in -- 1 for a live accept/body word, 0 at the boundaries -- so each branch tags its own word.
always @* begin
    if (rst) begin
        next_pc        = 0;
        transacting_in = 1'b0;
    end else if (out_valid) begin  // present: hold until the result is taken
        next_pc        = out_ready ? 0 : LASTPC;
        transacting_in = 1'b0;
    end else if (in_ready) begin   // accept: hold until a transaction arrives
        next_pc        = in_valid ? 1 : 0;
        transacting_in = in_valid;
    end else begin                 // advance the fetch: the body of a live transaction
        transacting_in = 1'b1;
        case (pc)
            8: next_pc = bregs[0] ? 9 : 84;
            83: next_pc = 4;
            default: next_pc = pc + 1'b1;
        endcase
    end
end

// Operand read muxes: a per-port case over the read codebook (registers and constants), driving the wrapper.
always @* begin
    s_fcmp_63b877a8_0_a = regs[2];
    s_fcmp_63b877a8_0_b = const_2;
    case (uc_fmul_68b24f7b_0_ard)
        1'd0: s_fmul_68b24f7b_0_a = regs[1];
        default: s_fmul_68b24f7b_0_a = regs[3];
    endcase
    case (uc_fmul_68b24f7b_0_brd)
        2'd0: s_fmul_68b24f7b_0_b = regs[4];
        2'd1: s_fmul_68b24f7b_0_b = regs[5];
        default: s_fmul_68b24f7b_0_b = const_1;
    endcase
    s_fsincos_47997380_0_a = regs[4];
    case (uc_fadd_9eba50d4_0_ard)
        2'd0: s_fadd_9eba50d4_0_a = regs[3];
        2'd1: s_fadd_9eba50d4_0_a = regs[5];
        default: s_fadd_9eba50d4_0_a = const_0;
    endcase
    case (uc_fadd_9eba50d4_0_brd)
        2'd0: s_fadd_9eba50d4_0_b = regs[0];
        2'd1: s_fadd_9eba50d4_0_b = regs[2];
        default: s_fadd_9eba50d4_0_b = regs[4];
    endcase
    s_fdiv_56ea25b7_0_a = regs[6];
    s_fdiv_56ea25b7_0_b = regs[5];
end

// All sequential logic in one clocked process. Reset gates only the control state (pc, err_pc_q, transacting_q) and the
// persistent state registers; every other register is reset-unconditional. Each is driven by exactly one statement.
always @(posedge clk) begin
    // Microcode fetch: PC latch; ucode_word pipelines ucode_q.
    ucode_addr_q <= next_pc;
    ucode_word   <= ucode_q;

    // Register writes (reset-unconditional): one opcode-selected statement per register.
    if (in_ready && in_valid) regs[0] <= in_mean_anomaly;
    if (in_ready && in_valid) regs[1] <= in_eccentricity;
    case (uc_op_r2)
        2'd1: regs[2] <= s_fdiv_56ea25b7_0_y0;
        2'd2: regs[2] <= const_0;
    endcase
    case (uc_op_r3)
        2'd1: regs[3] <= s_fadd_9eba50d4_0_y0;
        2'd2: regs[3] <= regs[0];
    endcase
    case (uc_op_r4)
        2'd1: regs[4] <= s_fmul_68b24f7b_0_y0;
        2'd2: regs[4] <= s_fsincos_47997380_0_y0;
    endcase
    case (uc_op_r5)
        2'd1: regs[5] <= s_fsincos_47997380_0_y1;
        2'd2: regs[5] <= s_fadd_9eba50d4_0_y0;
    endcase
    if (uc_op_r6) regs[6] <= s_fadd_9eba50d4_0_y0;
    if (uc_op_b0) bregs[0] <= s_fcmp_63b877a8_0_y0;

    // Control and persistent state: the reset-gated registers.
    if (rst) begin
        pc            <= 0;
        err_pc_q      <= 0;
        transacting_q <= 0;
    end else begin
        pc <= next_pc;
        transacting_q <= (transacting_q << 1) | transacting_in;
        if (err) err_pc_q <= pc - FETCH_LAG;  // err wins; execution lags the fetch PC by FETCH_LAG, so step is pc-lag
        else if (in_ready && in_valid) err_pc_q <= 0;  // clear the diagnostic when a new transaction is accepted
    end
end

assign in_ready  = (pc == 0);
assign out_valid = (pc == LASTPC);  // result valid on PRESENT; execution lags the fetch by FETCH_LAG
assign err_pc    = err_pc_q;
assign out_0 = regs[3];

endmodule
