// Generated by Holoso v<VERSION> <https://holoso.digital>.
// This file is generated output and is unencumbered: no copyright is claimed over it and no license terms apply.
// You may use, modify, and redistribute it freely, in open-source or proprietary designs, without restrictions.

`timescale 1ns/1ps

// Float format: exponent 8 bits, significand 36 bits, total 44 bits.
module majority_voter (
    // CONTROL PORTS
    // Clock/reset and ready/valid handshake for one scheduled invocation.
    input  wire clk,
    input  wire rst,
    input  wire in_valid,
    output wire in_ready,
    output wire out_valid,
    input  wire out_ready,
    // INPUT PORTS
    // Latched when in_valid && in_ready.
    input  wire in_enabled,
    input  wire in_a,
    input  wire in_b,
    input  wire in_c,
    input  wire in_d,
    input  wire in_e,
    // OUTPUT/STATE PORTS
    // Valid when out_valid is pulsed. Publicly visible states are included here.
    output wire out_0,
    output wire out_1,
    output wire out_2,
    output wire out_3,
    output wire out_4,
    output wire out_5,
    // DIAGNOSTIC PORTS
    // Runtime diagnostics available while the module is running.
    output wire [4:0] err_pc
);

localparam           WEXP      =   8;  // Float exponent bits fixed by the static schedule
localparam           WMAN      =  36;  // Float mantissa bits fixed by the static schedule
localparam           W         = WEXP + WMAN;
localparam           CYCW      =   5;  // err_pc width: enough for any executing step (0..present)
localparam           PCW       =   5;  // fetch-PC width: counts to LASTPC (execution lags the fetch by FETCH_LAG)
localparam           FETCH_LAG =   2;  // executing step = pc - FETCH_LAG (3-stage control fetch)
localparam [PCW-1:0] PRESENT   =  17;  // executing step on which the outputs are valid in the array
localparam [PCW-1:0] LASTPC    =  19;  // = PRESENT + FETCH_LAG; out_valid asserts here
localparam           UCW       =  29;  // microcode word width after lifting out constant control fields
localparam           NBREG     =  21;
// pc: 0 = idle/accept, present at executing step PRESENT; out_valid at pc==LASTPC (fetch leads execution).

// BEGIN holoso_support_inline.vh: the file is spliced into each generated module.

// Arithmetic shift by a constant. Positive shamt shifts left. For variable shamt use holoso_ashift.
function signed [W-1:0] holoso_ashiftc;
    input signed [W-1:0] x;
    input signed [W-1:0] shamt;
    reg signed [W:0] shamt_ext;
    reg [$clog2(W)-1:0] shamt_narrow;
    reg signed [W-1:0] shifted_left;
    reg signed [W-1:0] shifted_right;
    begin
        shamt_ext = {shamt[W-1], shamt};
        shamt_narrow = shamt[$clog2(W)-1:0];
        shifted_left = x << shamt_narrow;
        shifted_right = x >>> -shamt_narrow;
        if (shamt_ext >= W) begin
            holoso_ashiftc = {W{1'b0}};
        end else if (shamt_ext <= -W) begin
            holoso_ashiftc = {W{x[W-1]}};
        end else if (shamt[W-1]) begin
            holoso_ashiftc = shifted_right;
        end else begin
            holoso_ashiftc = shifted_left;
        end
    end
endfunction

// Combinational mapping from float to boolean: a zero or a subnormal (if supported) float is false, otherwise true.
// E.g., if IEEE 754 binary32 is used (with subnormals), values with magnitude under ~1e-38 are mapped to falsity.
function holoso_ftobool;
    input [W-1:0] x;
    holoso_ftobool = |x[W-2:WMAN-1];
endfunction

// Combinational mapping from boolean to float: falsity is zero, truth is one.
function [W-1:0] holoso_ffrombool;
    input b;
    holoso_ffrombool = b ? {2'b00, {(WEXP - 1) {1'b1}}, {(WMAN - 1) {1'b0}}} : {W{1'b0}};
endfunction

// Combinational predicate: y=1 iff x is finite (i.e., x is not an infinity).
function holoso_fisfinite;
    input [W-1:0] x;
    holoso_fisfinite = ~&x[W-2:WMAN-1];
endfunction

function holoso_fisposinf;
    input [W-1:0] x;
    holoso_fisposinf = ~holoso_fisfinite(x) & ~x[W-1];
endfunction

function holoso_fisneginf;
    input [W-1:0] x;
    holoso_fisneginf = ~holoso_fisfinite(x) & x[W-1];
endfunction

// Combinational saturator: replaces infinity with the largest finite value of the same sign; finite pass through.
function [W-1:0] holoso_fsaturate;
    input [W-1:0] x;
    holoso_fsaturate = (&x[W-2:WMAN-1]) ? {x[W-1], {(WEXP - 1) {1'b1}}, 1'b0, {(WMAN - 1) {1'b1}}} : x;
endfunction

// Combinational floating-point sign conditioner (absolute first, then optional negate): op[0]=negate, op[1]=absolute.
//      op=0: +x        op=1: -x        op=2: +|x|      op=3: -|x|
function [W-1:0] holoso_fsgnop;
    input [W-1:0] x;
    input [1:0]   op;
    holoso_fsgnop = {(x[W-1] & ~op[1]) ^ op[0], x[W-2:0]};
endfunction

// END of holoso_support_inline.vh

reg  [PCW-1:0]  pc;            // fetch program counter; the executing step lags it by FETCH_LAG
reg  [PCW-1:0]  next_pc;       // combinational next-state presented to the ROM each cycle
reg  [PCW-1:0]  ucode_addr_q;  // PC latch: splits pc -> next_pc -> ROM address for the case read
reg  [CYCW-1:0] err_pc_q;
wire            err;           // an operator error is detected on the current step

reg                 transacting_in;                           // per-branch tag: this pc's word is a live step
reg [FETCH_LAG-1:0] transacting_q;                            // delays the tag FETCH_LAG onto executing word
wire                transacting = transacting_q[FETCH_LAG-1]; // gates the executing word's effects

reg          bregs [0:NBREG-1];


// Microcode VLIW ROM.
reg [UCW-1:0] ucode_q;     // 2nd fetch stage
reg [UCW-1:0] ucode_word;  // 3rd fetch stage
// Microcode word field map:
//   [3:0]    uc_op_b11
//   [5:4]    uc_op_b12
//   [7:6]    uc_op_b13
//   [9:8]    uc_op_b14
//   [11:10]  uc_op_b15
//   [13:12]  uc_op_b16
//   [14]     uc_op_b17
//   [15]     uc_op_b18
//   [16]     uc_op_b19
//   [17]     uc_op_b20
//   [18]     uc_op_b0
//   [19]     uc_op_b1
//   [20]     uc_op_b2
//   [21]     uc_op_b3
//   [22]     uc_op_b4
//   [23]     uc_op_b5
//   [24]     uc_op_b6
//   [25]     uc_op_b7
//   [26]     uc_op_b8
//   [27]     uc_op_b9
//   [28]     uc_op_b10
(* rom_style = "block", syn_romstyle = "EBR" *)
always @(posedge clk)
    case (ucode_addr_q)
        0: ucode_q <= 29'h00001551;  // land b11=b1&b2, b12=b1&b3, b13=b1&b4, b14=b2&b3, b15=b2&b4, b16=b3&b4
        1: ucode_q <= 29'h0003eaa2;  // land b11=b11&b3, b12=b11&b4, b13=b11&b5, b14=b12&b4, b15=b12&b5, b16=b13&b5, b17=b14&b4, b18=b14&b5, b19=b15&b5, b20=b16&b5
        2: ucode_q <= 29'h00000003;  // land b11=b11|b12
        3: ucode_q <= 29'h00000004;  // land b11=b11|b13
        4: ucode_q <= 29'h00000005;  // land b11=b11|b14
        5: ucode_q <= 29'h00000006;  // land b11=b11|b15
        6: ucode_q <= 29'h00000007;  // land b11=b11|b16
        7: ucode_q <= 29'h00000008;  // land b11=b11|b17
        8: ucode_q <= 29'h00000009;  // land b11=b11|b18
        9: ucode_q <= 29'h0000000a;  // land b11=b11|b19
        10: ucode_q <= 29'h00040000;  // land b0=b11|b20
        11: ucode_q <= 29'h00000000;
        12: ucode_q <= 29'h00000000;
        13: ucode_q <= 29'h00000000;
        14: ucode_q <= 29'h00f80000;  // land b1=b1^b0, b2=b2^b0, b3=b3^b0, b4=b4^b0, b5=b5^b0
        15: ucode_q <= 29'h1f000000;  // land b6=b6|b1, b7=b7|b2, b8=b8|b3, b9=b9|b4, b10=b10|b5
        16: ucode_q <= 29'h00000000;
        17: ucode_q <= 29'h00000000;
        18: ucode_q <= 29'h00000000;
        19: ucode_q <= 29'h00000000;
        default: ucode_q <= 29'h0;  // unreached (PC bounded to LASTPC); NOP fill
    endcase

// Decoded control fields. A field constant across the whole program is driven by a constant net (so synthesis prunes
// the logic it feeds); a varying field is a slice of the instruction word. The effect-trigger fields -- the ``gated``
// ones (operator issue strobes and per-register write opcodes) -- are ANDed with `transacting` HERE, so a held
// ucode[0] dwell, a fill bubble, or a stale pre-reset word decodes to 0 (NOP): no issue and every register holds.
// The AND wraps the constant branch too, so the gate stays unconditional even if a trigger ever folds to a constant.
wire [ 3:0] uc_op_b11 = {4{transacting}} & ucode_word[0 +: 4];
wire [ 1:0] uc_op_b12 = {2{transacting}} & ucode_word[4 +: 2];
wire [ 1:0] uc_op_b13 = {2{transacting}} & ucode_word[6 +: 2];
wire [ 1:0] uc_op_b14 = {2{transacting}} & ucode_word[8 +: 2];
wire [ 1:0] uc_op_b15 = {2{transacting}} & ucode_word[10 +: 2];
wire [ 1:0] uc_op_b16 = {2{transacting}} & ucode_word[12 +: 2];
wire        uc_op_b17 = transacting & ucode_word[14 +: 1];
wire        uc_op_b18 = transacting & ucode_word[15 +: 1];
wire        uc_op_b19 = transacting & ucode_word[16 +: 1];
wire        uc_op_b20 = transacting & ucode_word[17 +: 1];
wire        uc_op_b0 = transacting & ucode_word[18 +: 1];
wire        uc_op_b1 = transacting & ucode_word[19 +: 1];
wire        uc_op_b2 = transacting & ucode_word[20 +: 1];
wire        uc_op_b3 = transacting & ucode_word[21 +: 1];
wire        uc_op_b4 = transacting & ucode_word[22 +: 1];
wire        uc_op_b5 = transacting & ucode_word[23 +: 1];
wire        uc_op_b6 = transacting & ucode_word[24 +: 1];
wire        uc_op_b7 = transacting & ucode_word[25 +: 1];
wire        uc_op_b8 = transacting & ucode_word[26 +: 1];
wire        uc_op_b9 = transacting & ucode_word[27 +: 1];
wire        uc_op_b10 = transacting & ucode_word[28 +: 1];

assign err = 1'b0;

// Next-PC sequencer (combinational). The PC holds at the accept (pc==0) and present (pc==LASTPC) boundaries; bubble
// steps carry a NOP word and the PC keeps advancing. The executing step lags the fetch PC by FETCH_LAG. A block's
// terminator redirects the fetch PC at the block's boundary step (a branch reads its boolean register). Each branch
// also sets transacting_in -- 1 for a live accept/body word, 0 at the boundaries -- so each branch tags its own word.
always @* begin
    if (rst) begin
        next_pc        = 0;
        transacting_in = 1'b0;
    end else if (out_valid) begin  // present: hold until the result is taken
        next_pc        = out_ready ? 0 : LASTPC;
        transacting_in = 1'b0;
    end else if (in_ready) begin   // accept: hold until a transaction arrives
        next_pc        = in_valid ? 1 : 0;
        transacting_in = in_valid;
    end else begin                 // advance the fetch: the body of a live transaction
        transacting_in = 1'b1;
        case (pc)
            12: next_pc = bregs[0] ? 14 : 13;
            13: next_pc = 19;
            default: next_pc = pc + 1'b1;
        endcase
    end
end

// All sequential logic in one clocked process. Reset gates only the control state (pc, err_pc_q, transacting_q) and the
// persistent state registers; every other register is reset-unconditional. Each is driven by exactly one statement.
always @(posedge clk) begin
    // Microcode fetch: PC latch; ucode_word pipelines ucode_q.
    ucode_addr_q <= next_pc;
    ucode_word   <= ucode_q;

    // Register writes (reset-unconditional): one opcode-selected statement per register.
    if (in_ready && in_valid) bregs[0] <= in_enabled;
    else if (uc_op_b0) bregs[0] <= bregs[11] | bregs[20];
    if (in_ready && in_valid) bregs[1] <= in_a;
    else if (uc_op_b1) bregs[1] <= bregs[1] ^ bregs[0];
    if (in_ready && in_valid) bregs[2] <= in_b;
    else if (uc_op_b2) bregs[2] <= bregs[2] ^ bregs[0];
    if (in_ready && in_valid) bregs[3] <= in_c;
    else if (uc_op_b3) bregs[3] <= bregs[3] ^ bregs[0];
    if (in_ready && in_valid) bregs[4] <= in_d;
    else if (uc_op_b4) bregs[4] <= bregs[4] ^ bregs[0];
    if (in_ready && in_valid) bregs[5] <= in_e;
    else if (uc_op_b5) bregs[5] <= bregs[5] ^ bregs[0];
    case (uc_op_b11)
        4'd1: bregs[11] <= bregs[1] & bregs[2];
        4'd2: bregs[11] <= bregs[11] & bregs[3];
        4'd3: bregs[11] <= bregs[11] | bregs[12];
        4'd4: bregs[11] <= bregs[11] | bregs[13];
        4'd5: bregs[11] <= bregs[11] | bregs[14];
        4'd6: bregs[11] <= bregs[11] | bregs[15];
        4'd7: bregs[11] <= bregs[11] | bregs[16];
        4'd8: bregs[11] <= bregs[11] | bregs[17];
        4'd9: bregs[11] <= bregs[11] | bregs[18];
        4'd10: bregs[11] <= bregs[11] | bregs[19];
    endcase
    case (uc_op_b12)
        2'd1: bregs[12] <= bregs[1] & bregs[3];
        2'd2: bregs[12] <= bregs[11] & bregs[4];
    endcase
    case (uc_op_b13)
        2'd1: bregs[13] <= bregs[1] & bregs[4];
        2'd2: bregs[13] <= bregs[11] & bregs[5];
    endcase
    case (uc_op_b14)
        2'd1: bregs[14] <= bregs[2] & bregs[3];
        2'd2: bregs[14] <= bregs[12] & bregs[4];
    endcase
    case (uc_op_b15)
        2'd1: bregs[15] <= bregs[2] & bregs[4];
        2'd2: bregs[15] <= bregs[12] & bregs[5];
    endcase
    case (uc_op_b16)
        2'd1: bregs[16] <= bregs[3] & bregs[4];
        2'd2: bregs[16] <= bregs[13] & bregs[5];
    endcase
    if (uc_op_b17) bregs[17] <= bregs[14] & bregs[4];
    if (uc_op_b18) bregs[18] <= bregs[14] & bregs[5];
    if (uc_op_b19) bregs[19] <= bregs[15] & bregs[5];
    if (uc_op_b20) bregs[20] <= bregs[16] & bregs[5];

    // Control and persistent state: the reset-gated registers.
    if (rst) begin
        pc            <= 0;
        err_pc_q      <= 0;
        transacting_q <= 0;
        bregs[6] <= 1'b0;  // _fault_a reset snapshot
        bregs[7] <= 1'b0;  // _fault_b reset snapshot
        bregs[8] <= 1'b0;  // _fault_c reset snapshot
        bregs[9] <= 1'b0;  // _fault_d reset snapshot
        bregs[10] <= 1'b0;  // _fault_e reset snapshot
    end else begin
        pc <= next_pc;
        transacting_q <= (transacting_q << 1) | transacting_in;
        if (err) err_pc_q <= pc - FETCH_LAG;  // err wins; execution lags the fetch PC by FETCH_LAG, so step is pc-lag
        else if (in_ready && in_valid) err_pc_q <= 0;  // clear the diagnostic when a new transaction is accepted
        if (uc_op_b6) bregs[6] <= bregs[6] | bregs[1];
        if (uc_op_b7) bregs[7] <= bregs[7] | bregs[2];
        if (uc_op_b8) bregs[8] <= bregs[8] | bregs[3];
        if (uc_op_b9) bregs[9] <= bregs[9] | bregs[4];
        if (uc_op_b10) bregs[10] <= bregs[10] | bregs[5];
    end
end

assign in_ready  = (pc == 0);
assign out_valid = (pc == LASTPC);  // result valid on PRESENT; execution lags the fetch by FETCH_LAG
assign err_pc    = err_pc_q;
assign out_0 = bregs[0];
assign out_1 = bregs[6];
assign out_2 = bregs[7];
assign out_3 = bregs[8];
assign out_4 = bregs[9];
assign out_5 = bregs[10];

endmodule
