// Generated by Holoso v<VERSION> <https://holoso.digital>.
// This file is generated output and is unencumbered: no copyright is claimed over it and no license terms apply.
// You may use, modify, and redistribute it freely, in open-source or proprietary designs, without restrictions.

`timescale 1ns/1ps

// Float format: exponent 8 bits, significand 36 bits, total 44 bits.
module pid (
    // CONTROL PORTS
    // Clock/reset and ready/valid handshake for one scheduled invocation.
    input  wire clk,
    input  wire rst,
    input  wire in_valid,
    output wire in_ready,
    output wire out_valid,
    input  wire out_ready,
    // INPUT PORTS
    // Latched when in_valid && in_ready.
    input  wire [43:0] in_setpoint,
    input  wire [43:0] in_measurement,
    input  wire [43:0] in_dt,
    // OUTPUT/STATE PORTS
    // Valid when out_valid is pulsed. Publicly visible states are included here.
    output wire [43:0] out_0,
    output wire [43:0] state_prev_error,
    output wire [43:0] state_integral,
    // DIAGNOSTIC PORTS
    // Runtime diagnostics available while the module is running.
    output wire [6:0] err_pc
);

localparam           WEXP      =   8;  // Float exponent bits fixed by the static schedule
localparam           WMAN      =  36;  // Float mantissa bits fixed by the static schedule
localparam           W         = WEXP + WMAN;
localparam           NREG      =  10;
localparam           CYCW      =   7;  // err_pc width: enough for any executing step (0..present)
localparam           PCW       =   7;  // fetch-PC width: counts to LASTPC (execution lags the fetch by FETCH_LAG)
localparam           FETCH_LAG =   2;  // executing step = pc - FETCH_LAG (3-stage control fetch)
localparam [PCW-1:0] PRESENT   =  66;  // executing step on which the outputs are valid in the array
localparam [PCW-1:0] LASTPC    =  68;  // = PRESENT + FETCH_LAG; out_valid asserts here
localparam           UCW       =  30;  // microcode word width after lifting out constant control fields
localparam           NBREG     =   2;
// pc: 0 = idle/accept, present at executing step PRESENT; out_valid at pc==LASTPC (fetch leads execution).

// BEGIN holoso_support_inline.vh: the file is spliced into each generated module.

// Arithmetic shift by a constant. Positive shamt shifts left. For variable shamt use holoso_ashift.
function signed [W-1:0] holoso_ashiftc;
    input signed [W-1:0] x;
    input signed [W-1:0] shamt;
    reg signed [W:0] shamt_ext;
    reg [$clog2(W)-1:0] shamt_narrow;
    reg signed [W-1:0] shifted_left;
    reg signed [W-1:0] shifted_right;
    begin
        shamt_ext = {shamt[W-1], shamt};
        shamt_narrow = shamt[$clog2(W)-1:0];
        shifted_left = x << shamt_narrow;
        shifted_right = x >>> -shamt_narrow;
        if (shamt_ext >= W) begin
            holoso_ashiftc = {W{1'b0}};
        end else if (shamt_ext <= -W) begin
            holoso_ashiftc = {W{x[W-1]}};
        end else if (shamt[W-1]) begin
            holoso_ashiftc = shifted_right;
        end else begin
            holoso_ashiftc = shifted_left;
        end
    end
endfunction

// Combinational mapping from float to boolean: a zero or a subnormal (if supported) float is false, otherwise true.
// E.g., if IEEE 754 binary32 is used (with subnormals), values with magnitude under ~1e-38 are mapped to falsity.
function holoso_ftobool;
    input [W-1:0] x;
    holoso_ftobool = |x[W-2:WMAN-1];
endfunction

// Combinational mapping from boolean to float: falsity is zero, truth is one.
function [W-1:0] holoso_ffrombool;
    input b;
    holoso_ffrombool = b ? {2'b00, {(WEXP - 1) {1'b1}}, {(WMAN - 1) {1'b0}}} : {W{1'b0}};
endfunction

// Combinational predicate: y=1 iff x is finite (i.e., x is not an infinity).
function holoso_fisfinite;
    input [W-1:0] x;
    holoso_fisfinite = ~&x[W-2:WMAN-1];
endfunction

function holoso_fisposinf;
    input [W-1:0] x;
    holoso_fisposinf = ~holoso_fisfinite(x) & ~x[W-1];
endfunction

function holoso_fisneginf;
    input [W-1:0] x;
    holoso_fisneginf = ~holoso_fisfinite(x) & x[W-1];
endfunction

// Combinational saturator: replaces infinity with the largest finite value of the same sign; finite pass through.
function [W-1:0] holoso_fsaturate;
    input [W-1:0] x;
    holoso_fsaturate = (&x[W-2:WMAN-1]) ? {x[W-1], {(WEXP - 1) {1'b1}}, 1'b0, {(WMAN - 1) {1'b1}}} : x;
endfunction

// Combinational floating-point sign conditioner (absolute first, then optional negate): op[0]=negate, op[1]=absolute.
//      op=0: +x        op=1: -x        op=2: +|x|      op=3: -|x|
function [W-1:0] holoso_fsgnop;
    input [W-1:0] x;
    input [1:0]   op;
    holoso_fsgnop = {(x[W-1] & ~op[1]) ^ op[0], x[W-2:0]};
endfunction

// END of holoso_support_inline.vh

reg  [PCW-1:0]  pc;            // fetch program counter; the executing step lags it by FETCH_LAG
reg  [PCW-1:0]  next_pc;       // combinational next-state presented to the ROM each cycle
reg  [PCW-1:0]  ucode_addr_q;  // PC latch: splits pc -> next_pc -> ROM address for the case read
reg  [CYCW-1:0] err_pc_q;
wire            err;           // an operator error is detected on the current step

reg                 transacting_in;                           // per-branch tag: this pc's word is a live step
reg [FETCH_LAG-1:0] transacting_q;                            // delays the tag FETCH_LAG onto executing word
wire                transacting = transacting_q[FETCH_LAG-1]; // gates the executing word's effects

reg  [W-1:0] regs  [0:NREG-1];   // read-first: a write is visible next step
reg          bregs [0:NBREG-1];

reg  [W-1:0] s_fadd_9eba50d4_0_a;
reg  [W-1:0] s_fadd_9eba50d4_0_b;
wire [W-1:0] s_fadd_9eba50d4_0_y0;
reg  [W-1:0] s_fmul_ilog2_const_72d9b6c9_0_a;
wire [W-1:0] s_fmul_ilog2_const_72d9b6c9_0_y0;
reg  [W-1:0] s_fmul_68b24f7b_0_a;
reg  [W-1:0] s_fmul_68b24f7b_0_b;
wire [W-1:0] s_fmul_68b24f7b_0_y0;
reg  [W-1:0] s_fmul_ilog2_const_b971b71f_0_a;
wire [W-1:0] s_fmul_ilog2_const_b971b71f_0_y0;
reg  [W-1:0] s_fdiv_56ea25b7_0_a;
reg  [W-1:0] s_fdiv_56ea25b7_0_b;
wire [W-1:0] s_fdiv_56ea25b7_0_y0;
wire         s_fdiv_56ea25b7_0_div0;
reg  [W-1:0] s_fmul_ilog2_const_98e5699d_0_a;
wire [W-1:0] s_fmul_ilog2_const_98e5699d_0_y0;
reg  [W-1:0] s_fcmp_63b877a8_0_a;
reg  [W-1:0] s_fcmp_63b877a8_0_b;
wire         s_fcmp_63b877a8_0_y0;
wire         s_fcmp_63b877a8_0_y2;

wire [W-1:0] const_0 = 44'h00000000000;  // 0.0
wire [W-1:0] const_1 = 44'h40800000000;  // 4.0

// Microcode VLIW ROM.
reg [UCW-1:0] ucode_q;     // 2nd fetch stage
reg [UCW-1:0] ucode_word;  // 3rd fetch stage
// Microcode word field map:
//   [0]      uc_issue_fadd_9eba50d4_0
//   [2:1]    uc_fadd_9eba50d4_0_ard
//   [4:3]    uc_fadd_9eba50d4_0_bsgn
//   [6:5]    uc_fadd_9eba50d4_0_brd
//   [7]      uc_issue_fmul_ilog2_const_72d9b6c9_0
//   [8]      uc_issue_fmul_68b24f7b_0
//   [9]      uc_issue_fmul_ilog2_const_b971b71f_0
//   [10]     uc_issue_fdiv_56ea25b7_0
//   [11]     uc_issue_fmul_ilog2_const_98e5699d_0
//   [12]     uc_issue_fcmp_63b877a8_0
//   [14:13]  uc_fcmp_63b877a8_0_asgn
//   [15]     uc_op_r0
//   [17:16]  uc_op_r7
//   [19:18]  uc_op_r5
//   [21:20]  uc_op_r6
//   [22]     uc_op_r1
//   [24:23]  uc_op_r8
//   [26:25]  uc_op_b1
//   [27]     uc_op_r2
//   [28]     uc_op_r9
//   [29]     uc_op_r4
(* rom_style = "block", syn_romstyle = "EBR" *)
always @(posedge clk)
    case (ucode_addr_q)
        0: ucode_q <= 30'h00000009;  // issue r0=r0+-r1
        1: ucode_q <= 30'h00000000;
        2: ucode_q <= 30'h00000000;
        3: ucode_q <= 30'h00000000;
        4: ucode_q <= 30'h00008000;  // commit r0
        5: ucode_q <= 30'h00000080;  // issue r7=r0×2^-4
        6: ucode_q <= 30'h00010000;  // commit r7
        7: ucode_q <= 30'h00000100;  // issue r5=r7×r2
        8: ucode_q <= 30'h00040000;  // commit r5
        9: ucode_q <= 30'h00000043;  // issue r5=r4+r5
        10: ucode_q <= 30'h00000000;
        11: ucode_q <= 30'h00000000;
        12: ucode_q <= 30'h00000000;
        13: ucode_q <= 30'h00080000;  // commit r5
        14: ucode_q <= 30'h01000000;  // land r8=c0
        15: ucode_q <= 30'h00000000;
        16: ucode_q <= 30'h00000000;
        17: ucode_q <= 30'h00000000;
        18: ucode_q <= 30'h00000029;  // issue r6=r0+-r3
        19: ucode_q <= 30'h00000000;
        20: ucode_q <= 30'h00000000;
        21: ucode_q <= 30'h00000000;
        22: ucode_q <= 30'h00100000;  // commit r6
        23: ucode_q <= 30'h00000200;  // issue r1=r6×2^-2
        24: ucode_q <= 30'h00400000;  // commit r1
        25: ucode_q <= 30'h00000400;  // issue r8=r1/r2
        26: ucode_q <= 30'h00000000;
        27: ucode_q <= 30'h00000000;
        28: ucode_q <= 30'h00000000;
        29: ucode_q <= 30'h00000000;
        30: ucode_q <= 30'h00000000;
        31: ucode_q <= 30'h00000000;
        32: ucode_q <= 30'h00000000;
        33: ucode_q <= 30'h00000000;
        34: ucode_q <= 30'h00000000;
        35: ucode_q <= 30'h00000000;
        36: ucode_q <= 30'h00000000;
        37: ucode_q <= 30'h00000000;
        38: ucode_q <= 30'h00000000;
        39: ucode_q <= 30'h00000000;
        40: ucode_q <= 30'h00000000;
        41: ucode_q <= 30'h00000000;
        42: ucode_q <= 30'h00000000;
        43: ucode_q <= 30'h00000000;
        44: ucode_q <= 30'h00000000;
        45: ucode_q <= 30'h00000000;
        46: ucode_q <= 30'h00800000;  // commit r8
        47: ucode_q <= 30'h00000000;
        48: ucode_q <= 30'h00000000;
        49: ucode_q <= 30'h00000000;
        50: ucode_q <= 30'h00000800;  // issue r6=r0×2^-1
        51: ucode_q <= 30'h00200000;  // commit r6
        52: ucode_q <= 30'h00000045;  // issue r6=r6+r5
        53: ucode_q <= 30'h00000000;
        54: ucode_q <= 30'h00000000;
        55: ucode_q <= 30'h00000000;
        56: ucode_q <= 30'h00100000;  // commit r6
        57: ucode_q <= 30'h00000065;  // issue r6=r6+r8
        58: ucode_q <= 30'h00000000;
        59: ucode_q <= 30'h00000000;
        60: ucode_q <= 30'h00000000;
        61: ucode_q <= 30'h00100000;  // commit r6
        62: ucode_q <= 30'h00003000;  // issue b1=cmp(-c1,r6)
        63: ucode_q <= 30'h02001000;  // issue b1=cmp(c1,r6); commit b1
        64: ucode_q <= 30'h1c000000;  // commit b1; land r2=b1?-c1:r6, r9=b1?r4:r5
        65: ucode_q <= 30'h20020000;  // land r7=b1?c1:r2, r4=b1?r4:r9
        66: ucode_q <= 30'h00000000;
        67: ucode_q <= 30'h00000000;
        68: ucode_q <= 30'h00000000;
        default: ucode_q <= 30'h0;  // unreached (PC bounded to LASTPC); NOP fill
    endcase

// Decoded control fields. A field constant across the whole program is driven by a constant net (so synthesis prunes
// the logic it feeds); a varying field is a slice of the instruction word. The effect-trigger fields -- the ``gated``
// ones (operator issue strobes and per-register write opcodes) -- are ANDed with `transacting` HERE, so a held
// ucode[0] dwell, a fill bubble, or a stale pre-reset word decodes to 0 (NOP): no issue and every register holds.
// The AND wraps the constant branch too, so the gate stays unconditional even if a trigger ever folds to a constant.
wire        uc_issue_fadd_9eba50d4_0 = transacting & ucode_word[0 +: 1];
wire [ 1:0] uc_fadd_9eba50d4_0_asgn = 2'd0;
wire [ 1:0] uc_fadd_9eba50d4_0_ard = ucode_word[1 +: 2];
wire [ 1:0] uc_fadd_9eba50d4_0_bsgn = ucode_word[3 +: 2];
wire [ 1:0] uc_fadd_9eba50d4_0_brd = ucode_word[5 +: 2];
wire [ 1:0] uc_fadd_9eba50d4_0_y0sgn = 2'd0;
wire        uc_issue_fmul_ilog2_const_72d9b6c9_0 = transacting & ucode_word[7 +: 1];
wire [ 1:0] uc_fmul_ilog2_const_72d9b6c9_0_asgn = 2'd0;
wire [ 1:0] uc_fmul_ilog2_const_72d9b6c9_0_y0sgn = 2'd0;
wire        uc_issue_fmul_68b24f7b_0 = transacting & ucode_word[8 +: 1];
wire [ 1:0] uc_fmul_68b24f7b_0_asgn = 2'd0;
wire [ 1:0] uc_fmul_68b24f7b_0_bsgn = 2'd0;
wire [ 1:0] uc_fmul_68b24f7b_0_y0sgn = 2'd0;
wire        uc_issue_fmul_ilog2_const_b971b71f_0 = transacting & ucode_word[9 +: 1];
wire [ 1:0] uc_fmul_ilog2_const_b971b71f_0_asgn = 2'd0;
wire [ 1:0] uc_fmul_ilog2_const_b971b71f_0_y0sgn = 2'd0;
wire        uc_issue_fdiv_56ea25b7_0 = transacting & ucode_word[10 +: 1];
wire [ 1:0] uc_fdiv_56ea25b7_0_asgn = 2'd0;
wire [ 1:0] uc_fdiv_56ea25b7_0_bsgn = 2'd0;
wire [ 1:0] uc_fdiv_56ea25b7_0_y0sgn = 2'd0;
wire        uc_issue_fmul_ilog2_const_98e5699d_0 = transacting & ucode_word[11 +: 1];
wire [ 1:0] uc_fmul_ilog2_const_98e5699d_0_asgn = 2'd0;
wire [ 1:0] uc_fmul_ilog2_const_98e5699d_0_y0sgn = 2'd0;
wire        uc_issue_fcmp_63b877a8_0 = transacting & ucode_word[12 +: 1];
wire [ 1:0] uc_fcmp_63b877a8_0_asgn = ucode_word[13 +: 2];
wire [ 1:0] uc_fcmp_63b877a8_0_bsgn = 2'd0;
wire        uc_op_r0 = transacting & ucode_word[15 +: 1];
wire [ 1:0] uc_op_r7 = {2{transacting}} & ucode_word[16 +: 2];
wire [ 1:0] uc_op_r5 = {2{transacting}} & ucode_word[18 +: 2];
wire [ 1:0] uc_op_r6 = {2{transacting}} & ucode_word[20 +: 2];
wire        uc_op_r1 = transacting & ucode_word[22 +: 1];
wire [ 1:0] uc_op_r8 = {2{transacting}} & ucode_word[23 +: 2];
wire [ 1:0] uc_op_b1 = {2{transacting}} & ucode_word[25 +: 2];
wire        uc_op_r2 = transacting & ucode_word[27 +: 1];
wire        uc_op_r9 = transacting & ucode_word[28 +: 1];
wire        uc_op_r4 = transacting & ucode_word[29 +: 1];

holoso_fadd #(
    .WEXP(8), .WMAN(36), .STAGE_INPUT(0), .STAGE_DECODE(0), .STAGE_ALIGN(0), .STAGE_NORMALIZE(0), .STAGE_PACK(0), .STAGE_OUTPUT(0), .LATENCY(4)
) u_fadd_9eba50d4_0 (
    .clk(clk), .rst(rst), .in_valid(uc_issue_fadd_9eba50d4_0),
    .a_sgnop(uc_fadd_9eba50d4_0_asgn),
    .b_sgnop(uc_fadd_9eba50d4_0_bsgn),
    .y_sgnop(uc_fadd_9eba50d4_0_y0sgn),
    .a(s_fadd_9eba50d4_0_a),
    .b(s_fadd_9eba50d4_0_b),
    .out_valid(),
    .y(s_fadd_9eba50d4_0_y0)
);

holoso_fmul_ilog2_const #(
    .WEXP(8), .WMAN(36), .K(-4), .STAGE_INPUT(0), .STAGE_DECODE(0), .LATENCY(1)
) u_fmul_ilog2_const_72d9b6c9_0 (
    .clk(clk), .rst(rst), .in_valid(uc_issue_fmul_ilog2_const_72d9b6c9_0),
    .a_sgnop(uc_fmul_ilog2_const_72d9b6c9_0_asgn),
    .y_sgnop(uc_fmul_ilog2_const_72d9b6c9_0_y0sgn),
    .a(s_fmul_ilog2_const_72d9b6c9_0_a),
    .out_valid(),
    .y(s_fmul_ilog2_const_72d9b6c9_0_y0)
);

holoso_fmul #(
    .WEXP(8), .WMAN(36), .WMULTIPLIER(0), .STAGE_INPUT(0), .STAGE_PRODUCT(0), .STAGE_PACK(0), .STAGE_OUTPUT(0), .LATENCY(1)
) u_fmul_68b24f7b_0 (
    .clk(clk), .rst(rst), .in_valid(uc_issue_fmul_68b24f7b_0),
    .a_sgnop(uc_fmul_68b24f7b_0_asgn),
    .b_sgnop(uc_fmul_68b24f7b_0_bsgn),
    .y_sgnop(uc_fmul_68b24f7b_0_y0sgn),
    .a(s_fmul_68b24f7b_0_a),
    .b(s_fmul_68b24f7b_0_b),
    .out_valid(),
    .y(s_fmul_68b24f7b_0_y0)
);

holoso_fmul_ilog2_const #(
    .WEXP(8), .WMAN(36), .K(-2), .STAGE_INPUT(0), .STAGE_DECODE(0), .LATENCY(1)
) u_fmul_ilog2_const_b971b71f_0 (
    .clk(clk), .rst(rst), .in_valid(uc_issue_fmul_ilog2_const_b971b71f_0),
    .a_sgnop(uc_fmul_ilog2_const_b971b71f_0_asgn),
    .y_sgnop(uc_fmul_ilog2_const_b971b71f_0_y0sgn),
    .a(s_fmul_ilog2_const_b971b71f_0_a),
    .out_valid(),
    .y(s_fmul_ilog2_const_b971b71f_0_y0)
);

holoso_fdiv #(
    .WEXP(8), .WMAN(36), .STAGE_INPUT(0), .STAGE_PACK(0), .STAGE_OUTPUT(0), .LATENCY(21)
) u_fdiv_56ea25b7_0 (
    .clk(clk), .rst(rst), .in_valid(uc_issue_fdiv_56ea25b7_0),
    .a_sgnop(uc_fdiv_56ea25b7_0_asgn),
    .b_sgnop(uc_fdiv_56ea25b7_0_bsgn),
    .y_sgnop(uc_fdiv_56ea25b7_0_y0sgn),
    .a(s_fdiv_56ea25b7_0_a),
    .b(s_fdiv_56ea25b7_0_b),
    .out_valid(),
    .y(s_fdiv_56ea25b7_0_y0),
    .div0(s_fdiv_56ea25b7_0_div0)
);

holoso_fmul_ilog2_const #(
    .WEXP(8), .WMAN(36), .K(-1), .STAGE_INPUT(0), .STAGE_DECODE(0), .LATENCY(1)
) u_fmul_ilog2_const_98e5699d_0 (
    .clk(clk), .rst(rst), .in_valid(uc_issue_fmul_ilog2_const_98e5699d_0),
    .a_sgnop(uc_fmul_ilog2_const_98e5699d_0_asgn),
    .y_sgnop(uc_fmul_ilog2_const_98e5699d_0_y0sgn),
    .a(s_fmul_ilog2_const_98e5699d_0_a),
    .out_valid(),
    .y(s_fmul_ilog2_const_98e5699d_0_y0)
);

holoso_fcmp #(
    .WEXP(8), .WMAN(36), .STAGE_INPUT(0), .LATENCY(1)
) u_fcmp_63b877a8_0 (
    .clk(clk), .rst(rst), .in_valid(uc_issue_fcmp_63b877a8_0),
    .a_sgnop(uc_fcmp_63b877a8_0_asgn),
    .b_sgnop(uc_fcmp_63b877a8_0_bsgn),
    .a(s_fcmp_63b877a8_0_a),
    .b(s_fcmp_63b877a8_0_b),
    .out_valid(),
    .a_gt_b(s_fcmp_63b877a8_0_y0),
    .a_eq_b(),
    .a_lt_b(s_fcmp_63b877a8_0_y2)
);

assign err = ((uc_op_r8 == 2'd1) & s_fdiv_56ea25b7_0_div0);

// Next-PC sequencer (combinational). The PC holds at the accept (pc==0) and present (pc==LASTPC) boundaries; bubble
// steps carry a NOP word and the PC keeps advancing. The executing step lags the fetch PC by FETCH_LAG. A block's
// terminator redirects the fetch PC at the block's boundary step (a branch reads its boolean register). Each branch
// also sets transacting_in -- 1 for a live accept/body word, 0 at the boundaries -- so each branch tags its own word.
always @* begin
    if (rst) begin
        next_pc        = 0;
        transacting_in = 1'b0;
    end else if (out_valid) begin  // present: hold until the result is taken
        next_pc        = out_ready ? 0 : LASTPC;
        transacting_in = 1'b0;
    end else if (in_ready) begin   // accept: hold until a transaction arrives
        next_pc        = in_valid ? 1 : 0;
        transacting_in = in_valid;
    end else begin                 // advance the fetch: the body of a live transaction
        transacting_in = 1'b1;
        case (pc)
            13: next_pc = bregs[0] ? 18 : 14;
            17: next_pc = 50;
            default: next_pc = pc + 1'b1;
        endcase
    end
end

// Operand read muxes: a per-port case over the read codebook (registers and constants), driving the wrapper.
always @* begin
    case (uc_fadd_9eba50d4_0_ard)
        2'd0: s_fadd_9eba50d4_0_a = regs[0];
        2'd1: s_fadd_9eba50d4_0_a = regs[4];
        default: s_fadd_9eba50d4_0_a = regs[6];
    endcase
    case (uc_fadd_9eba50d4_0_brd)
        2'd0: s_fadd_9eba50d4_0_b = regs[1];
        2'd1: s_fadd_9eba50d4_0_b = regs[3];
        2'd2: s_fadd_9eba50d4_0_b = regs[5];
        default: s_fadd_9eba50d4_0_b = regs[8];
    endcase
    s_fmul_ilog2_const_72d9b6c9_0_a = regs[0];
    s_fmul_68b24f7b_0_a = regs[7];
    s_fmul_68b24f7b_0_b = regs[2];
    s_fmul_ilog2_const_b971b71f_0_a = regs[6];
    s_fdiv_56ea25b7_0_a = regs[1];
    s_fdiv_56ea25b7_0_b = regs[2];
    s_fmul_ilog2_const_98e5699d_0_a = regs[0];
    s_fcmp_63b877a8_0_a = const_1;
    s_fcmp_63b877a8_0_b = regs[6];
end

// All sequential logic in one clocked process. Reset gates only the control state (pc, err_pc_q, transacting_q) and the
// persistent state registers; every other register is reset-unconditional. Each is driven by exactly one statement.
always @(posedge clk) begin
    // Microcode fetch: PC latch; ucode_word pipelines ucode_q.
    ucode_addr_q <= next_pc;
    ucode_word   <= ucode_q;

    // Register writes (reset-unconditional): one opcode-selected statement per register.
    if (in_ready && in_valid) regs[0] <= in_setpoint;
    else if (uc_op_r0) regs[0] <= s_fadd_9eba50d4_0_y0;
    if (in_ready && in_valid) regs[1] <= in_measurement;
    else if (uc_op_r1) regs[1] <= s_fmul_ilog2_const_b971b71f_0_y0;
    if (in_ready && in_valid) regs[2] <= in_dt;
    else if (uc_op_r2) regs[2] <= (bregs[1] ? holoso_fsgnop(const_1, 2'd1) : regs[6]);
    case (uc_op_r5)
        2'd1: regs[5] <= s_fmul_68b24f7b_0_y0;
        2'd2: regs[5] <= s_fadd_9eba50d4_0_y0;
    endcase
    case (uc_op_r6)
        2'd1: regs[6] <= s_fadd_9eba50d4_0_y0;
        2'd2: regs[6] <= s_fmul_ilog2_const_98e5699d_0_y0;
    endcase
    case (uc_op_r7)
        2'd1: regs[7] <= s_fmul_ilog2_const_72d9b6c9_0_y0;
        2'd2: regs[7] <= (bregs[1] ? const_1 : regs[2]);
    endcase
    case (uc_op_r8)
        2'd1: regs[8] <= s_fdiv_56ea25b7_0_y0;
        2'd2: regs[8] <= const_0;
    endcase
    if (uc_op_r9) regs[9] <= (bregs[1] ? regs[4] : regs[5]);
    case (uc_op_b1)
        2'd1: bregs[1] <= s_fcmp_63b877a8_0_y0;
        2'd2: bregs[1] <= s_fcmp_63b877a8_0_y2;
    endcase

    // Control and persistent state: the reset-gated registers.
    if (rst) begin
        pc            <= 0;
        err_pc_q      <= 0;
        transacting_q <= 0;
        regs[3] <= 44'h00000000000;  // prev_error reset snapshot
        regs[4] <= 44'h00000000000;  // integral reset snapshot
        bregs[0] <= 1'b0;  // _started reset snapshot
    end else begin
        pc <= next_pc;
        transacting_q <= (transacting_q << 1) | transacting_in;
        if (err) err_pc_q <= pc - FETCH_LAG;  // err wins; execution lags the fetch PC by FETCH_LAG, so step is pc-lag
        else if (in_ready && in_valid) err_pc_q <= 0;  // clear the diagnostic when a new transaction is accepted
        if (out_valid && out_ready) regs[3] <= regs[0];
        if (uc_op_r4) regs[4] <= (bregs[1] ? regs[4] : regs[9]);
        if (out_valid && out_ready) bregs[0] <= 1'b1;
    end
end

assign in_ready  = (pc == 0);
assign out_valid = (pc == LASTPC);  // result valid on PRESENT; execution lags the fetch by FETCH_LAG
assign err_pc    = err_pc_q;
assign out_0 = regs[7];
assign state_prev_error = regs[0];
assign state_integral = regs[4];

endmodule
