// Generated by Holoso v<VERSION> <https://holoso.digital>.
// This file is generated output and is unencumbered: no copyright is claimed over it and no license terms apply.
// You may use, modify, and redistribute it freely, in open-source or proprietary designs, without restrictions.

`timescale 1ns/1ps

// Float format: exponent 4 bits, significand 8 bits, total 12 bits.
module uart_tx (
    // CONTROL PORTS
    // Clock/reset and ready/valid handshake for one scheduled invocation.
    input  wire clk,
    input  wire rst,
    input  wire in_valid,
    output wire in_ready,
    output wire out_valid,
    input  wire out_ready,
    // INPUT PORTS
    // Latched when in_valid && in_ready.
    input  wire in_start,
    input  wire [11:0] in_char,
    // OUTPUT/STATE PORTS
    // Valid when out_valid is pulsed. Publicly visible states are included here.
    output wire out_0,
    output wire out_1,
    // DIAGNOSTIC PORTS
    // Runtime diagnostics available while the module is running.
    output wire [6:0] err_pc
);

localparam           WEXP      =   4;  // Float exponent bits fixed by the static schedule
localparam           WMAN      =   8;  // Float mantissa bits fixed by the static schedule
localparam           W         = WEXP + WMAN;
localparam           NREG      =   8;
localparam           CYCW      =   7;  // err_pc width: enough for any executing step (0..present)
localparam           PCW       =   7;  // fetch-PC width: counts to LASTPC (execution lags the fetch by FETCH_LAG)
localparam           FETCH_LAG =   2;  // executing step = pc - FETCH_LAG (3-stage control fetch)
localparam [PCW-1:0] PRESENT   = 101;  // executing step on which the outputs are valid in the array
localparam [PCW-1:0] LASTPC    = 103;  // = PRESENT + FETCH_LAG; out_valid asserts here
localparam           UCW       =  42;  // microcode word width after lifting out constant control fields
localparam           NBREG     =   6;
// pc: 0 = idle/accept, present at executing step PRESENT; out_valid at pc==LASTPC (fetch leads execution).

// BEGIN holoso_support_inline.vh: the file is spliced into each generated module.

// Arithmetic shift by a constant. Positive shamt shifts left. For variable shamt use holoso_ashift.
function signed [W-1:0] holoso_ashiftc;
    input signed [W-1:0] x;
    input signed [W-1:0] shamt;
    reg signed [W:0] shamt_ext;
    reg [$clog2(W)-1:0] shamt_narrow;
    reg signed [W-1:0] shifted_left;
    reg signed [W-1:0] shifted_right;
    begin
        shamt_ext = {shamt[W-1], shamt};
        shamt_narrow = shamt[$clog2(W)-1:0];
        shifted_left = x << shamt_narrow;
        shifted_right = x >>> -shamt_narrow;
        if (shamt_ext >= W) begin
            holoso_ashiftc = {W{1'b0}};
        end else if (shamt_ext <= -W) begin
            holoso_ashiftc = {W{x[W-1]}};
        end else if (shamt[W-1]) begin
            holoso_ashiftc = shifted_right;
        end else begin
            holoso_ashiftc = shifted_left;
        end
    end
endfunction

// Combinational mapping from float to boolean: a zero or a subnormal (if supported) float is false, otherwise true.
// E.g., if IEEE 754 binary32 is used (with subnormals), values with magnitude under ~1e-38 are mapped to falsity.
function holoso_ftobool;
    input [W-1:0] x;
    holoso_ftobool = |x[W-2:WMAN-1];
endfunction

// Combinational mapping from boolean to float: falsity is zero, truth is one.
function [W-1:0] holoso_ffrombool;
    input b;
    holoso_ffrombool = b ? {2'b00, {(WEXP - 1) {1'b1}}, {(WMAN - 1) {1'b0}}} : {W{1'b0}};
endfunction

// Combinational predicate: y=1 iff x is finite (i.e., x is not an infinity).
function holoso_fisfinite;
    input [W-1:0] x;
    holoso_fisfinite = ~&x[W-2:WMAN-1];
endfunction

function holoso_fisposinf;
    input [W-1:0] x;
    holoso_fisposinf = ~holoso_fisfinite(x) & ~x[W-1];
endfunction

function holoso_fisneginf;
    input [W-1:0] x;
    holoso_fisneginf = ~holoso_fisfinite(x) & x[W-1];
endfunction

// Combinational saturator: replaces infinity with the largest finite value of the same sign; finite pass through.
function [W-1:0] holoso_fsaturate;
    input [W-1:0] x;
    holoso_fsaturate = (&x[W-2:WMAN-1]) ? {x[W-1], {(WEXP - 1) {1'b1}}, 1'b0, {(WMAN - 1) {1'b1}}} : x;
endfunction

// Combinational floating-point sign conditioner (absolute first, then optional negate): op[0]=negate, op[1]=absolute.
//      op=0: +x        op=1: -x        op=2: +|x|      op=3: -|x|
function [W-1:0] holoso_fsgnop;
    input [W-1:0] x;
    input [1:0]   op;
    holoso_fsgnop = {(x[W-1] & ~op[1]) ^ op[0], x[W-2:0]};
endfunction

// END of holoso_support_inline.vh

reg  [PCW-1:0]  pc;            // fetch program counter; the executing step lags it by FETCH_LAG
reg  [PCW-1:0]  next_pc;       // combinational next-state presented to the ROM each cycle
reg  [PCW-1:0]  ucode_addr_q;  // PC latch: splits pc -> next_pc -> ROM address for the case read
reg  [CYCW-1:0] err_pc_q;
wire            err;           // an operator error is detected on the current step

reg                 transacting_in;                           // per-branch tag: this pc's word is a live step
reg [FETCH_LAG-1:0] transacting_q;                            // delays the tag FETCH_LAG onto executing word
wire                transacting = transacting_q[FETCH_LAG-1]; // gates the executing word's effects

reg  [W-1:0] regs  [0:NREG-1];   // read-first: a write is visible next step
reg          bregs [0:NBREG-1];

reg  [W-1:0] s_fadd_bc41e5c3_0_a;
reg  [W-1:0] s_fadd_bc41e5c3_0_b;
wire [W-1:0] s_fadd_bc41e5c3_0_y0;
reg  [W-1:0] s_fcmp_46863199_0_a;
reg  [W-1:0] s_fcmp_46863199_0_b;
wire         s_fcmp_46863199_0_y0;
wire         s_fcmp_46863199_0_y2;
reg  [W-1:0] s_fmul_ilog2_const_6b5098c4_0_a;
wire [W-1:0] s_fmul_ilog2_const_6b5098c4_0_y0;
reg  [W-1:0] s_fmul_ilog2_const_085a5e09_0_a;
wire [W-1:0] s_fmul_ilog2_const_085a5e09_0_y0;

wire [W-1:0] const_0 = 12'h380;  // 1.0
wire [W-1:0] const_1 = 12'h700;  // 128.0
wire [W-1:0] const_2 = 12'h570;  // 15.0
wire [W-1:0] const_3 = 12'h000;  // 0.0
wire [W-1:0] const_4 = 12'h500;  // 8.0
wire [W-1:0] const_5 = 12'h510;  // 9.0
wire [W-1:0] const_6 = 12'h520;  // 10.0

// Microcode VLIW ROM.
reg [UCW-1:0] ucode_q;     // 2nd fetch stage
reg [UCW-1:0] ucode_word;  // 3rd fetch stage
// Microcode word field map:
//   [0]      uc_issue_fadd_bc41e5c3_0
//   [2:1]    uc_fadd_bc41e5c3_0_asgn
//   [4:3]    uc_fadd_bc41e5c3_0_ard
//   [6:5]    uc_fadd_bc41e5c3_0_bsgn
//   [8:7]    uc_fadd_bc41e5c3_0_brd
//   [9]      uc_issue_fcmp_46863199_0
//   [12:10]  uc_fcmp_46863199_0_ard
//   [14:13]  uc_fcmp_46863199_0_brd
//   [15]     uc_issue_fmul_ilog2_const_6b5098c4_0
//   [16]     uc_fmul_ilog2_const_6b5098c4_0_ard
//   [17]     uc_issue_fmul_ilog2_const_085a5e09_0
//   [20:18]  uc_op_b0
//   [22:21]  uc_op_b4
//   [24:23]  uc_op_b3
//   [26:25]  uc_op_r1
//   [27]     uc_op_r7
//   [29:28]  uc_op_b5
//   [30]     uc_op_r0
//   [32:31]  uc_op_r2
//   [34:33]  uc_op_b1
//   [36:35]  uc_op_r3
//   [38:37]  uc_op_r5
//   [39]     uc_op_r4
//   [40]     uc_op_r6
//   [41]     uc_op_b2
(* rom_style = "block", syn_romstyle = "EBR" *)
always @(posedge clk)
    case (ucode_addr_q)
        0: ucode_q <= 42'h00000000000;
        1: ucode_q <= 42'h00000000000;
        2: ucode_q <= 42'h00000000000;
        3: ucode_q <= 42'h00000100000;  // land b0=1
        4: ucode_q <= 42'h00000000000;
        5: ucode_q <= 42'h00000000000;
        6: ucode_q <= 42'h00000000000;
        7: ucode_q <= 42'h00000000e1b;  // issue r1=-c1+r0, ~b0=cmp(c1,r0)
        8: ucode_q <= 42'h00000080000;  // commit b0
        9: ucode_q <= 42'h08000000000;  // land r4=b0?c1:c3
        10: ucode_q <= 42'h00000018000;  // issue r2=r4×2^-1
        11: ucode_q <= 42'h00082000000;  // commit r1, r2
        12: ucode_q <= 42'h04000000000;  // land r5=b0?r1:r0
        13: ucode_q <= 42'h00000020000;  // issue r0=r5×2^1
        14: ucode_q <= 42'h00040000000;  // commit r0
        15: ucode_q <= 42'h00000000e1b;  // issue r1=-c1+r0, ~b1=cmp(c1,r0)
        16: ucode_q <= 42'h00200000000;  // commit b1
        17: ucode_q <= 42'h10000140000;  // land r6=b1?c1:c3, b0=b0^b1
        18: ucode_q <= 42'h00000000089;  // issue r1=r2+r6
        19: ucode_q <= 42'h00002000000;  // commit r1
        20: ucode_q <= 42'h06000000000;  // land r5=b1?r1:r0
        21: ucode_q <= 42'h00000020000;  // issue r0=r5×2^1
        22: ucode_q <= 42'h00042000000;  // commit r1, r0
        23: ucode_q <= 42'h00000008e1b;  // issue r1=-c1+r0, ~b1=cmp(c1,r0), r2=r1×2^-1
        24: ucode_q <= 42'h00280000000;  // commit b1, r2
        25: ucode_q <= 42'h10000140000;  // land r6=b1?c1:c3, b0=b0^b1
        26: ucode_q <= 42'h00000000089;  // issue r1=r2+r6
        27: ucode_q <= 42'h00002000000;  // commit r1
        28: ucode_q <= 42'h06000000000;  // land r5=b1?r1:r0
        29: ucode_q <= 42'h00000020000;  // issue r0=r5×2^1
        30: ucode_q <= 42'h00042000000;  // commit r1, r0
        31: ucode_q <= 42'h00000008e1b;  // issue r1=-c1+r0, ~b1=cmp(c1,r0), r2=r1×2^-1
        32: ucode_q <= 42'h00280000000;  // commit b1, r2
        33: ucode_q <= 42'h10000140000;  // land r6=b1?c1:c3, b0=b0^b1
        34: ucode_q <= 42'h00000000089;  // issue r1=r2+r6
        35: ucode_q <= 42'h00002000000;  // commit r1
        36: ucode_q <= 42'h06000000000;  // land r5=b1?r1:r0
        37: ucode_q <= 42'h00000020000;  // issue r0=r5×2^1
        38: ucode_q <= 42'h00042000000;  // commit r1, r0
        39: ucode_q <= 42'h00000008e1b;  // issue r1=-c1+r0, ~b1=cmp(c1,r0), r2=r1×2^-1
        40: ucode_q <= 42'h00280000000;  // commit b1, r2
        41: ucode_q <= 42'h10000140000;  // land r6=b1?c1:c3, b0=b0^b1
        42: ucode_q <= 42'h00000000089;  // issue r1=r2+r6
        43: ucode_q <= 42'h00002000000;  // commit r1
        44: ucode_q <= 42'h06000000000;  // land r5=b1?r1:r0
        45: ucode_q <= 42'h00000020000;  // issue r0=r5×2^1
        46: ucode_q <= 42'h00042000000;  // commit r1, r0
        47: ucode_q <= 42'h00000008e1b;  // issue r1=-c1+r0, ~b1=cmp(c1,r0), r2=r1×2^-1
        48: ucode_q <= 42'h00280000000;  // commit b1, r2
        49: ucode_q <= 42'h10000140000;  // land r6=b1?c1:c3, b0=b0^b1
        50: ucode_q <= 42'h00000000089;  // issue r1=r2+r6
        51: ucode_q <= 42'h00002000000;  // commit r1
        52: ucode_q <= 42'h06000000000;  // land r5=b1?r1:r0
        53: ucode_q <= 42'h00000020000;  // issue r0=r5×2^1
        54: ucode_q <= 42'h00042000000;  // commit r1, r0
        55: ucode_q <= 42'h00000008e1b;  // issue r1=-c1+r0, ~b1=cmp(c1,r0), r2=r1×2^-1
        56: ucode_q <= 42'h00280000000;  // commit b1, r2
        57: ucode_q <= 42'h10000140000;  // land r6=b1?c1:c3, b0=b0^b1
        58: ucode_q <= 42'h00000000089;  // issue r1=r2+r6
        59: ucode_q <= 42'h00002000000;  // commit r1
        60: ucode_q <= 42'h06000000000;  // land r5=b1?r1:r0
        61: ucode_q <= 42'h00000020000;  // issue r0=r5×2^1
        62: ucode_q <= 42'h00042000000;  // commit r1, r0
        63: ucode_q <= 42'h00000008e00;  // issue ~b1=cmp(c1,r0), r2=r1×2^-1
        64: ucode_q <= 42'h00280000000;  // commit b1, r2
        65: ucode_q <= 42'h30000000000;  // land r6=b1?c1:c3, b2=b0^b1
        66: ucode_q <= 42'h00000000089;  // issue r3=r2+r6
        67: ucode_q <= 42'h00000000000;
        68: ucode_q <= 42'h00000000000;
        69: ucode_q <= 42'h00000000000;
        70: ucode_q <= 42'h00f86100000;  // commit r3; land r1=c2, r2=c3, b0=1, b1=1
        71: ucode_q <= 42'h00000000000;
        72: ucode_q <= 42'h00000000000;
        73: ucode_q <= 42'h00000000000;
        74: ucode_q <= 42'h00000002600;  // issue ~b0=cmp(c5,r2)
        75: ucode_q <= 42'h00000042a00;  // issue ~b0=cmp(c4,r2); commit b0
        76: ucode_q <= 42'h00001044e00;  // issue ~b4=cmp(c1,r3); commit b0; land b3=~b0|b2
        77: ucode_q <= 42'h00000203200;  // issue ~b0=cmp(c3,r2); commit b4
        78: ucode_q <= 42'h00001846200;  // issue ~b3=cmp(r1,c3); commit b0; land b3=b0?b4:b3
        79: ucode_q <= 42'h000008c0000;  // commit b3; land b0=~b0&b3
        80: ucode_q <= 42'h00000000000;
        81: ucode_q <= 42'h00000000000;
        82: ucode_q <= 42'h00000000000;
        83: ucode_q <= 42'h00000000121;  // issue r1=r1+-c0
        84: ucode_q <= 42'h00000000000;
        85: ucode_q <= 42'h00000000000;
        86: ucode_q <= 42'h00000000000;
        87: ucode_q <= 42'h00002000000;  // commit r1
        88: ucode_q <= 42'h00000000000;
        89: ucode_q <= 42'h00000000000;
        90: ucode_q <= 42'h00000000000;
        91: ucode_q <= 42'h00000004fb1;  // issue r7=r3+-c1, ~b3=cmp(c1,r3)
        92: ucode_q <= 42'h00000803709;  // issue r7=r2+c0, ~b4=cmp(c0,r2); commit b3
        93: ucode_q <= 42'h00000202a00;  // issue ~b5=cmp(c4,r2); commit b4
        94: ucode_q <= 42'h00010003a00;  // issue ~b5=cmp(c6,r2); commit b5
        95: ucode_q <= 42'h00028400000;  // commit r7, b5; land b4=b4&b5
        96: ucode_q <= 42'h0240c000000;  // commit r7; land r5=b3?r7:r3, b1=~b5&b1, r1=b5?r1:c2
        97: ucode_q <= 42'h00100020000;  // issue r0=r5×2^1; land r2=b5?r2:r7
        98: ucode_q <= 42'h00040000000;  // commit r0
        99: ucode_q <= 42'h01000000000;  // land r3=b4?r0:r3
        100: ucode_q <= 42'h00000000000;
        101: ucode_q <= 42'h00000000000;
        102: ucode_q <= 42'h00000000000;
        103: ucode_q <= 42'h00000000000;
        default: ucode_q <= 42'h0;  // unreached (PC bounded to LASTPC); NOP fill
    endcase

// Decoded control fields. A field constant across the whole program is driven by a constant net (so synthesis prunes
// the logic it feeds); a varying field is a slice of the instruction word. The effect-trigger fields -- the ``gated``
// ones (operator issue strobes and per-register write opcodes) -- are ANDed with `transacting` HERE, so a held
// ucode[0] dwell, a fill bubble, or a stale pre-reset word decodes to 0 (NOP): no issue and every register holds.
// The AND wraps the constant branch too, so the gate stays unconditional even if a trigger ever folds to a constant.
wire        uc_issue_fadd_bc41e5c3_0 = transacting & ucode_word[0 +: 1];
wire [ 1:0] uc_fadd_bc41e5c3_0_asgn = ucode_word[1 +: 2];
wire [ 1:0] uc_fadd_bc41e5c3_0_ard = ucode_word[3 +: 2];
wire [ 1:0] uc_fadd_bc41e5c3_0_bsgn = ucode_word[5 +: 2];
wire [ 1:0] uc_fadd_bc41e5c3_0_brd = ucode_word[7 +: 2];
wire [ 1:0] uc_fadd_bc41e5c3_0_y0sgn = 2'd0;
wire        uc_issue_fcmp_46863199_0 = transacting & ucode_word[9 +: 1];
wire [ 1:0] uc_fcmp_46863199_0_asgn = 2'd0;
wire [ 2:0] uc_fcmp_46863199_0_ard = ucode_word[10 +: 3];
wire [ 1:0] uc_fcmp_46863199_0_bsgn = 2'd0;
wire [ 1:0] uc_fcmp_46863199_0_brd = ucode_word[13 +: 2];
wire        uc_issue_fmul_ilog2_const_6b5098c4_0 = transacting & ucode_word[15 +: 1];
wire [ 1:0] uc_fmul_ilog2_const_6b5098c4_0_asgn = 2'd0;
wire        uc_fmul_ilog2_const_6b5098c4_0_ard = ucode_word[16 +: 1];
wire [ 1:0] uc_fmul_ilog2_const_6b5098c4_0_y0sgn = 2'd0;
wire        uc_issue_fmul_ilog2_const_085a5e09_0 = transacting & ucode_word[17 +: 1];
wire [ 1:0] uc_fmul_ilog2_const_085a5e09_0_asgn = 2'd0;
wire [ 1:0] uc_fmul_ilog2_const_085a5e09_0_y0sgn = 2'd0;
wire [ 2:0] uc_op_b0 = {3{transacting}} & ucode_word[18 +: 3];
wire [ 1:0] uc_op_b4 = {2{transacting}} & ucode_word[21 +: 2];
wire [ 1:0] uc_op_b3 = {2{transacting}} & ucode_word[23 +: 2];
wire [ 1:0] uc_op_r1 = {2{transacting}} & ucode_word[25 +: 2];
wire        uc_op_r7 = transacting & ucode_word[27 +: 1];
wire [ 1:0] uc_op_b5 = {2{transacting}} & ucode_word[28 +: 2];
wire        uc_op_r0 = transacting & ucode_word[30 +: 1];
wire [ 1:0] uc_op_r2 = {2{transacting}} & ucode_word[31 +: 2];
wire [ 1:0] uc_op_b1 = {2{transacting}} & ucode_word[33 +: 2];
wire [ 1:0] uc_op_r3 = {2{transacting}} & ucode_word[35 +: 2];
wire [ 1:0] uc_op_r5 = {2{transacting}} & ucode_word[37 +: 2];
wire        uc_op_r4 = transacting & ucode_word[39 +: 1];
wire        uc_op_r6 = transacting & ucode_word[40 +: 1];
wire        uc_op_b2 = transacting & ucode_word[41 +: 1];

holoso_fadd #(
    .WEXP(4), .WMAN(8), .STAGE_INPUT(0), .STAGE_DECODE(0), .STAGE_ALIGN(0), .STAGE_NORMALIZE(0), .STAGE_PACK(0), .STAGE_OUTPUT(0), .LATENCY(4)
) u_fadd_bc41e5c3_0 (
    .clk(clk), .rst(rst), .in_valid(uc_issue_fadd_bc41e5c3_0),
    .a_sgnop(uc_fadd_bc41e5c3_0_asgn),
    .b_sgnop(uc_fadd_bc41e5c3_0_bsgn),
    .y_sgnop(uc_fadd_bc41e5c3_0_y0sgn),
    .a(s_fadd_bc41e5c3_0_a),
    .b(s_fadd_bc41e5c3_0_b),
    .out_valid(),
    .y(s_fadd_bc41e5c3_0_y0)
);

holoso_fcmp #(
    .WEXP(4), .WMAN(8), .STAGE_INPUT(0), .LATENCY(1)
) u_fcmp_46863199_0 (
    .clk(clk), .rst(rst), .in_valid(uc_issue_fcmp_46863199_0),
    .a_sgnop(uc_fcmp_46863199_0_asgn),
    .b_sgnop(uc_fcmp_46863199_0_bsgn),
    .a(s_fcmp_46863199_0_a),
    .b(s_fcmp_46863199_0_b),
    .out_valid(),
    .a_gt_b(s_fcmp_46863199_0_y0),
    .a_eq_b(),
    .a_lt_b(s_fcmp_46863199_0_y2)
);

holoso_fmul_ilog2_const #(
    .WEXP(4), .WMAN(8), .K(-1), .STAGE_INPUT(0), .STAGE_DECODE(0), .LATENCY(1)
) u_fmul_ilog2_const_6b5098c4_0 (
    .clk(clk), .rst(rst), .in_valid(uc_issue_fmul_ilog2_const_6b5098c4_0),
    .a_sgnop(uc_fmul_ilog2_const_6b5098c4_0_asgn),
    .y_sgnop(uc_fmul_ilog2_const_6b5098c4_0_y0sgn),
    .a(s_fmul_ilog2_const_6b5098c4_0_a),
    .out_valid(),
    .y(s_fmul_ilog2_const_6b5098c4_0_y0)
);

holoso_fmul_ilog2_const #(
    .WEXP(4), .WMAN(8), .K(1), .STAGE_INPUT(0), .STAGE_DECODE(0), .LATENCY(1)
) u_fmul_ilog2_const_085a5e09_0 (
    .clk(clk), .rst(rst), .in_valid(uc_issue_fmul_ilog2_const_085a5e09_0),
    .a_sgnop(uc_fmul_ilog2_const_085a5e09_0_asgn),
    .y_sgnop(uc_fmul_ilog2_const_085a5e09_0_y0sgn),
    .a(s_fmul_ilog2_const_085a5e09_0_a),
    .out_valid(),
    .y(s_fmul_ilog2_const_085a5e09_0_y0)
);

assign err = 1'b0;

// Next-PC sequencer (combinational). The PC holds at the accept (pc==0) and present (pc==LASTPC) boundaries; bubble
// steps carry a NOP word and the PC keeps advancing. The executing step lags the fetch PC by FETCH_LAG. A block's
// terminator redirects the fetch PC at the block's boundary step (a branch reads its boolean register). Each branch
// also sets transacting_in -- 1 for a live accept/body word, 0 at the boundaries -- so each branch tags its own word.
always @* begin
    if (rst) begin
        next_pc        = 0;
        transacting_in = 1'b0;
    end else if (out_valid) begin  // present: hold until the result is taken
        next_pc        = out_ready ? 0 : LASTPC;
        transacting_in = 1'b0;
    end else if (in_ready) begin   // accept: hold until a transaction arrives
        next_pc        = in_valid ? 1 : 0;
        transacting_in = in_valid;
    end else begin                 // advance the fetch: the body of a live transaction
        transacting_in = 1'b1;
        case (pc)
            1: next_pc = bregs[1] ? 74 : 2;
            2: next_pc = bregs[0] ? 7 : 3;
            6: next_pc = 103;
            73: next_pc = 103;
            82: next_pc = bregs[3] ? 91 : 83;
            90: next_pc = 103;
            default: next_pc = pc + 1'b1;
        endcase
    end
end

// Operand read muxes: a per-port case over the read codebook (registers and constants), driving the wrapper.
always @* begin
    case (uc_fadd_bc41e5c3_0_ard)
        2'd0: s_fadd_bc41e5c3_0_a = regs[1];
        2'd1: s_fadd_bc41e5c3_0_a = regs[2];
        2'd2: s_fadd_bc41e5c3_0_a = regs[3];
        default: s_fadd_bc41e5c3_0_a = const_1;
    endcase
    case (uc_fadd_bc41e5c3_0_brd)
        2'd0: s_fadd_bc41e5c3_0_b = regs[0];
        2'd1: s_fadd_bc41e5c3_0_b = regs[6];
        2'd2: s_fadd_bc41e5c3_0_b = const_0;
        default: s_fadd_bc41e5c3_0_b = const_1;
    endcase
    case (uc_fcmp_46863199_0_ard)
        3'd0: s_fcmp_46863199_0_a = regs[1];
        3'd1: s_fcmp_46863199_0_a = const_5;
        3'd2: s_fcmp_46863199_0_a = const_4;
        3'd3: s_fcmp_46863199_0_a = const_1;
        3'd4: s_fcmp_46863199_0_a = const_3;
        3'd5: s_fcmp_46863199_0_a = const_0;
        default: s_fcmp_46863199_0_a = const_6;
    endcase
    case (uc_fcmp_46863199_0_brd)
        2'd0: s_fcmp_46863199_0_b = regs[0];
        2'd1: s_fcmp_46863199_0_b = regs[2];
        2'd2: s_fcmp_46863199_0_b = regs[3];
        default: s_fcmp_46863199_0_b = const_3;
    endcase
    case (uc_fmul_ilog2_const_6b5098c4_0_ard)
        1'd0: s_fmul_ilog2_const_6b5098c4_0_a = regs[1];
        default: s_fmul_ilog2_const_6b5098c4_0_a = regs[4];
    endcase
    s_fmul_ilog2_const_085a5e09_0_a = regs[5];
end

// All sequential logic in one clocked process. Reset gates only the control state (pc, err_pc_q, transacting_q) and the
// persistent state registers; every other register is reset-unconditional. Each is driven by exactly one statement.
always @(posedge clk) begin
    // Microcode fetch: PC latch; ucode_word pipelines ucode_q.
    ucode_addr_q <= next_pc;
    ucode_word   <= ucode_q;

    // Register writes (reset-unconditional): one opcode-selected statement per register.
    if (in_ready && in_valid) regs[0] <= in_char;
    else if (uc_op_r0) regs[0] <= s_fmul_ilog2_const_085a5e09_0_y0;
    if (uc_op_r4) regs[4] <= (bregs[0] ? const_1 : const_3);
    case (uc_op_r5)
        2'd1: regs[5] <= (bregs[3] ? regs[7] : regs[3]);
        2'd2: regs[5] <= (bregs[0] ? regs[1] : regs[0]);
        2'd3: regs[5] <= (bregs[1] ? regs[1] : regs[0]);
    endcase
    if (uc_op_r6) regs[6] <= (bregs[1] ? const_1 : const_3);
    if (uc_op_r7) regs[7] <= s_fadd_bc41e5c3_0_y0;
    if (in_ready && in_valid) bregs[0] <= in_start;
    else case (uc_op_b0)
        3'd1: bregs[0] <= ~s_fcmp_46863199_0_y2;
        3'd2: bregs[0] <= ~s_fcmp_46863199_0_y0;
        3'd3: bregs[0] <= ~bregs[0] & bregs[3];
        3'd4: bregs[0] <= 1'b1;
        3'd5: bregs[0] <= bregs[0] ^ bregs[1];
    endcase
    case (uc_op_b3)
        2'd1: bregs[3] <= ~s_fcmp_46863199_0_y0;
        2'd2: bregs[3] <= ~bregs[0] | bregs[2];
        2'd3: bregs[3] <= (bregs[0] ? bregs[4] : bregs[3]);
    endcase
    case (uc_op_b4)
        2'd1: bregs[4] <= ~s_fcmp_46863199_0_y0;
        2'd2: bregs[4] <= bregs[4] & bregs[5];
    endcase
    case (uc_op_b5)
        2'd1: bregs[5] <= ~s_fcmp_46863199_0_y2;
        2'd2: bregs[5] <= ~s_fcmp_46863199_0_y0;
    endcase

    // Control and persistent state: the reset-gated registers.
    if (rst) begin
        pc            <= 0;
        err_pc_q      <= 0;
        transacting_q <= 0;
        regs[1] <= 12'h000;  // _phase reset snapshot
        regs[2] <= 12'h000;  // _index reset snapshot
        regs[3] <= 12'h000;  // _shift reset snapshot
        bregs[1] <= 1'b0;  // _busy reset snapshot
        bregs[2] <= 1'b0;  // _parity reset snapshot
    end else begin
        pc <= next_pc;
        transacting_q <= (transacting_q << 1) | transacting_in;
        if (err) err_pc_q <= pc - FETCH_LAG;  // err wins; execution lags the fetch PC by FETCH_LAG, so step is pc-lag
        else if (in_ready && in_valid) err_pc_q <= 0;  // clear the diagnostic when a new transaction is accepted
        case (uc_op_r1)
            2'd1: regs[1] <= s_fadd_bc41e5c3_0_y0;
            2'd2: regs[1] <= (bregs[5] ? regs[1] : const_2);
            2'd3: regs[1] <= const_2;
        endcase
        case (uc_op_r2)
            2'd1: regs[2] <= s_fmul_ilog2_const_6b5098c4_0_y0;
            2'd2: regs[2] <= (bregs[5] ? regs[2] : regs[7]);
            2'd3: regs[2] <= const_3;
        endcase
        case (uc_op_r3)
            2'd1: regs[3] <= s_fadd_bc41e5c3_0_y0;
            2'd2: regs[3] <= (bregs[4] ? regs[0] : regs[3]);
        endcase
        case (uc_op_b1)
            2'd1: bregs[1] <= ~s_fcmp_46863199_0_y0;
            2'd2: bregs[1] <= ~bregs[5] & bregs[1];
            2'd3: bregs[1] <= 1'b1;
        endcase
        if (uc_op_b2) bregs[2] <= bregs[0] ^ bregs[1];
    end
end

assign in_ready  = (pc == 0);
assign out_valid = (pc == LASTPC);  // result valid on PRESENT; execution lags the fetch by FETCH_LAG
assign err_pc    = err_pc_q;
assign out_0 = bregs[0];
assign out_1 = bregs[1];

endmodule
