// Generated by Holoso v<VERSION> <https://holoso.digital>.
// This file is generated output and is unencumbered: no copyright is claimed over it and no license terms apply.
// You may use, modify, and redistribute it freely, in open-source or proprietary designs, without restrictions.

`timescale 1ns/1ps

// Float format: exponent 4 bits, significand 8 bits, total 12 bits.
module uart_rx (
    // CONTROL PORTS
    // Clock/reset and ready/valid handshake for one scheduled invocation.
    input  wire clk,
    input  wire rst,
    input  wire in_valid,
    output wire in_ready,
    output wire out_valid,
    input  wire out_ready,
    // INPUT PORTS
    // Latched when in_valid && in_ready.
    input  wire in_rx,
    // OUTPUT/STATE PORTS
    // Valid when out_valid is pulsed. Publicly visible states are included here.
    output wire out_0,
    output wire [11:0] out_1,
    output wire out_2,
    output wire out_3,
    // DIAGNOSTIC PORTS
    // Runtime diagnostics available while the module is running.
    output wire [6:0] err_pc
);

localparam           WEXP      =   4;  // Float exponent bits fixed by the static schedule
localparam           WMAN      =   8;  // Float mantissa bits fixed by the static schedule
localparam           W         = WEXP + WMAN;
localparam           NREG      =   8;
localparam           CYCW      =   7;  // err_pc width: enough for any executing step (0..present)
localparam           PCW       =   7;  // fetch-PC width: counts to LASTPC (execution lags the fetch by FETCH_LAG)
localparam           FETCH_LAG =   2;  // executing step = pc - FETCH_LAG (3-stage control fetch)
localparam [PCW-1:0] PRESENT   = 118;  // executing step on which the outputs are valid in the array
localparam [PCW-1:0] LASTPC    = 120;  // = PRESENT + FETCH_LAG; out_valid asserts here
localparam           UCW       =  42;  // microcode word width after lifting out constant control fields
localparam           NBREG     =   6;
// pc: 0 = idle/accept, present at executing step PRESENT; out_valid at pc==LASTPC (fetch leads execution).

// BEGIN holoso_support_inline.vh: the file is spliced into each generated module.

// Arithmetic shift by a constant. Positive shamt shifts left. For variable shamt use holoso_ashift.
function signed [W-1:0] holoso_ashiftc;
    input signed [W-1:0] x;
    input signed [W-1:0] shamt;
    reg signed [W:0] shamt_ext;
    reg [$clog2(W)-1:0] shamt_narrow;
    reg signed [W-1:0] shifted_left;
    reg signed [W-1:0] shifted_right;
    begin
        shamt_ext = {shamt[W-1], shamt};
        shamt_narrow = shamt[$clog2(W)-1:0];
        shifted_left = x << shamt_narrow;
        shifted_right = x >>> -shamt_narrow;
        if (shamt_ext >= W) begin
            holoso_ashiftc = {W{1'b0}};
        end else if (shamt_ext <= -W) begin
            holoso_ashiftc = {W{x[W-1]}};
        end else if (shamt[W-1]) begin
            holoso_ashiftc = shifted_right;
        end else begin
            holoso_ashiftc = shifted_left;
        end
    end
endfunction

// Combinational mapping from float to boolean: a zero or a subnormal (if supported) float is false, otherwise true.
// E.g., if IEEE 754 binary32 is used (with subnormals), values with magnitude under ~1e-38 are mapped to falsity.
function holoso_ftobool;
    input [W-1:0] x;
    holoso_ftobool = |x[W-2:WMAN-1];
endfunction

// Combinational mapping from boolean to float: falsity is zero, truth is one.
function [W-1:0] holoso_ffrombool;
    input b;
    holoso_ffrombool = b ? {2'b00, {(WEXP - 1) {1'b1}}, {(WMAN - 1) {1'b0}}} : {W{1'b0}};
endfunction

// Combinational predicate: y=1 iff x is finite (i.e., x is not an infinity).
function holoso_fisfinite;
    input [W-1:0] x;
    holoso_fisfinite = ~&x[W-2:WMAN-1];
endfunction

function holoso_fisposinf;
    input [W-1:0] x;
    holoso_fisposinf = ~holoso_fisfinite(x) & ~x[W-1];
endfunction

function holoso_fisneginf;
    input [W-1:0] x;
    holoso_fisneginf = ~holoso_fisfinite(x) & x[W-1];
endfunction

// Combinational saturator: replaces infinity with the largest finite value of the same sign; finite pass through.
function [W-1:0] holoso_fsaturate;
    input [W-1:0] x;
    holoso_fsaturate = (&x[W-2:WMAN-1]) ? {x[W-1], {(WEXP - 1) {1'b1}}, 1'b0, {(WMAN - 1) {1'b1}}} : x;
endfunction

// Combinational floating-point sign conditioner (absolute first, then optional negate): op[0]=negate, op[1]=absolute.
//      op=0: +x        op=1: -x        op=2: +|x|      op=3: -|x|
function [W-1:0] holoso_fsgnop;
    input [W-1:0] x;
    input [1:0]   op;
    holoso_fsgnop = {(x[W-1] & ~op[1]) ^ op[0], x[W-2:0]};
endfunction

// END of holoso_support_inline.vh

reg  [PCW-1:0]  pc;            // fetch program counter; the executing step lags it by FETCH_LAG
reg  [PCW-1:0]  next_pc;       // combinational next-state presented to the ROM each cycle
reg  [PCW-1:0]  ucode_addr_q;  // PC latch: splits pc -> next_pc -> ROM address for the case read
reg  [CYCW-1:0] err_pc_q;
wire            err;           // an operator error is detected on the current step

reg                 transacting_in;                           // per-branch tag: this pc's word is a live step
reg [FETCH_LAG-1:0] transacting_q;                            // delays the tag FETCH_LAG onto executing word
wire                transacting = transacting_q[FETCH_LAG-1]; // gates the executing word's effects

reg  [W-1:0] regs  [0:NREG-1];   // read-first: a write is visible next step
reg          bregs [0:NBREG-1];

reg  [W-1:0] s_fcmp_46863199_0_a;
reg  [W-1:0] s_fcmp_46863199_0_b;
wire         s_fcmp_46863199_0_y0;
wire         s_fcmp_46863199_0_y2;
reg  [W-1:0] s_fadd_bc41e5c3_0_a;
reg  [W-1:0] s_fadd_bc41e5c3_0_b;
wire [W-1:0] s_fadd_bc41e5c3_0_y0;
reg  [W-1:0] s_fmul_ilog2_const_085a5e09_0_a;
wire [W-1:0] s_fmul_ilog2_const_085a5e09_0_y0;
reg  [W-1:0] s_fmul_ilog2_const_6b5098c4_0_a;
wire [W-1:0] s_fmul_ilog2_const_6b5098c4_0_y0;
reg  [W-1:0] s_fmul_ilog2_const_ea2ed72b_0_a;
wire [W-1:0] s_fmul_ilog2_const_ea2ed72b_0_y0;

wire [W-1:0] const_0 = 12'h380;  // 1.0
wire [W-1:0] const_1 = 12'h700;  // 128.0
wire [W-1:0] const_2 = 12'h570;  // 15.0
wire [W-1:0] const_3 = 12'h000;  // 0.0
wire [W-1:0] const_4 = 12'h4e0;  // 7.0
wire [W-1:0] const_5 = 12'h500;  // 8.0
wire [W-1:0] const_6 = 12'h520;  // 10.0

// Microcode VLIW ROM.
reg [UCW-1:0] ucode_q;     // 2nd fetch stage
reg [UCW-1:0] ucode_word;  // 3rd fetch stage
// Microcode word field map:
//   [0]      uc_issue_fcmp_46863199_0
//   [3:1]    uc_fcmp_46863199_0_ard
//   [5:4]    uc_fcmp_46863199_0_brd
//   [6]      uc_issue_fadd_bc41e5c3_0
//   [8:7]    uc_fadd_bc41e5c3_0_asgn
//   [10:9]   uc_fadd_bc41e5c3_0_ard
//   [12:11]  uc_fadd_bc41e5c3_0_bsgn
//   [14:13]  uc_fadd_bc41e5c3_0_brd
//   [15]     uc_issue_fmul_ilog2_const_085a5e09_0
//   [16]     uc_issue_fmul_ilog2_const_6b5098c4_0
//   [17]     uc_issue_fmul_ilog2_const_ea2ed72b_0
//   [20:18]  uc_op_b3
//   [23:21]  uc_op_r0
//   [26:24]  uc_op_b1
//   [27]     uc_op_r3
//   [28]     uc_op_r5
//   [30:29]  uc_op_r1
//   [31]     uc_op_r7
//   [33:32]  uc_op_r2
//   [35:34]  uc_op_b4
//   [37:36]  uc_op_b5
//   [39:38]  uc_op_r4
//   [40]     uc_op_b2
//   [41]     uc_op_r6
(* rom_style = "block", syn_romstyle = "EBR" *)
always @(posedge clk)
    case (ucode_addr_q)
        0: ucode_q <= 42'h00000000000;
        1: ucode_q <= 42'h00000000000;
        2: ucode_q <= 42'h01665b00000;  // land r2=~b0?c3:r2, b1=~b0|b1, r0=~b0?c4:r0, r1=~b0?c3:r1, b4=0, b3=0, b5=0
        3: ucode_q <= 42'h00000000000;
        4: ucode_q <= 42'h00000000000;
        5: ucode_q <= 42'h00000000000;
        6: ucode_q <= 42'h00000000021;  // issue ~b3=cmp(r0,c3)
        7: ucode_q <= 42'h00000040000;  // commit b3
        8: ucode_q <= 42'h00000000000;
        9: ucode_q <= 42'h00000000000;
        10: ucode_q <= 42'h00000000000;
        11: ucode_q <= 42'h000000004c0;  // issue r0=-c0+r0
        12: ucode_q <= 42'h00000000000;
        13: ucode_q <= 42'h00000000000;
        14: ucode_q <= 42'h00000000000;
        15: ucode_q <= 42'h01400300000;  // commit r0; land b4=0, b3=0, b5=0
        16: ucode_q <= 42'h00000000000;
        17: ucode_q <= 42'h00000000000;
        18: ucode_q <= 42'h00000000000;
        19: ucode_q <= 42'h00000000005;  // issue ~b3=cmp(c3,r1)
        20: ucode_q <= 42'h00000080000;  // commit b3
        21: ucode_q <= 42'h00000000000;
        22: ucode_q <= 42'h00000000000;
        23: ucode_q <= 42'h00000000000;
        24: ucode_q <= 42'h00000000007;  // issue ~b3=cmp(c5,r1)
        25: ucode_q <= 42'h00000080000;  // commit b3
        26: ucode_q <= 42'h00000000000;
        27: ucode_q <= 42'h00000000000;
        28: ucode_q <= 42'h00000000000;
        29: ucode_q <= 42'h00000000009;  // issue b3=cmp(c6,r1)
        30: ucode_q <= 42'h000000c0000;  // commit b3
        31: ucode_q <= 42'h00000000000;
        32: ucode_q <= 42'h00000000000;
        33: ucode_q <= 42'h00000000000;
        34: ucode_q <= 42'h00000006873;  // issue r3=r2+-c1, ~b1=cmp(r2,c1)
        35: ucode_q <= 42'h00001000000;  // commit b1
        36: ucode_q <= 42'h00000000000;
        37: ucode_q <= 42'h00000000000;
        38: ucode_q <= 42'h00008000000;  // commit r3
        39: ucode_q <= 42'h04000000000;  // land r4=b1?r3:r2
        40: ucode_q <= 42'h00000008000;  // issue r5=r4×2^1
        41: ucode_q <= 42'h00010000000;  // commit r5
        42: ucode_q <= 42'h000000046db;  // issue r3=-c1+r5, ~b3=cmp(c1,r5)
        43: ucode_q <= 42'h00000040000;  // commit b3
        44: ucode_q <= 42'h00002000000;  // land b1=b1^b3
        45: ucode_q <= 42'h00000000000;
        46: ucode_q <= 42'h00008000000;  // commit r3
        47: ucode_q <= 42'h08000000000;  // land r4=b3?r3:r5
        48: ucode_q <= 42'h00000008000;  // issue r5=r4×2^1
        49: ucode_q <= 42'h00010000000;  // commit r5
        50: ucode_q <= 42'h000000046db;  // issue r3=-c1+r5, ~b3=cmp(c1,r5)
        51: ucode_q <= 42'h00000040000;  // commit b3
        52: ucode_q <= 42'h00002000000;  // land b1=b1^b3
        53: ucode_q <= 42'h00000000000;
        54: ucode_q <= 42'h00008000000;  // commit r3
        55: ucode_q <= 42'h08000000000;  // land r4=b3?r3:r5
        56: ucode_q <= 42'h00000008000;  // issue r5=r4×2^1
        57: ucode_q <= 42'h00010000000;  // commit r5
        58: ucode_q <= 42'h000000046db;  // issue r3=-c1+r5, ~b3=cmp(c1,r5)
        59: ucode_q <= 42'h00000040000;  // commit b3
        60: ucode_q <= 42'h00002000000;  // land b1=b1^b3
        61: ucode_q <= 42'h00000000000;
        62: ucode_q <= 42'h00008000000;  // commit r3
        63: ucode_q <= 42'h08000000000;  // land r4=b3?r3:r5
        64: ucode_q <= 42'h00000008000;  // issue r5=r4×2^1
        65: ucode_q <= 42'h00010000000;  // commit r5
        66: ucode_q <= 42'h000000046db;  // issue r3=-c1+r5, ~b3=cmp(c1,r5)
        67: ucode_q <= 42'h00000040000;  // commit b3
        68: ucode_q <= 42'h00002000000;  // land b1=b1^b3
        69: ucode_q <= 42'h00000000000;
        70: ucode_q <= 42'h00008000000;  // commit r3
        71: ucode_q <= 42'h08000000000;  // land r4=b3?r3:r5
        72: ucode_q <= 42'h00000008000;  // issue r5=r4×2^1
        73: ucode_q <= 42'h00010000000;  // commit r5
        74: ucode_q <= 42'h000000046db;  // issue r3=-c1+r5, ~b3=cmp(c1,r5)
        75: ucode_q <= 42'h00000040000;  // commit b3
        76: ucode_q <= 42'h00002000000;  // land b1=b1^b3
        77: ucode_q <= 42'h00000000000;
        78: ucode_q <= 42'h00008000000;  // commit r3
        79: ucode_q <= 42'h08000000000;  // land r4=b3?r3:r5
        80: ucode_q <= 42'h00000008000;  // issue r5=r4×2^1
        81: ucode_q <= 42'h00010000000;  // commit r5
        82: ucode_q <= 42'h000000046db;  // issue r3=-c1+r5, ~b3=cmp(c1,r5)
        83: ucode_q <= 42'h00000040000;  // commit b3
        84: ucode_q <= 42'h00002000000;  // land b1=b1^b3
        85: ucode_q <= 42'h00000000000;
        86: ucode_q <= 42'h00008000000;  // commit r3
        87: ucode_q <= 42'h08000000000;  // land r4=b3?r3:r5
        88: ucode_q <= 42'h00000008000;  // issue r5=r4×2^1
        89: ucode_q <= 42'h00010000000;  // commit r5
        90: ucode_q <= 42'h0000000001b;  // issue ~b3=cmp(c1,r5)
        91: ucode_q <= 42'h00000040000;  // commit b3
        92: ucode_q <= 42'h00000140000;  // land b3=b1^b3
        93: ucode_q <= 42'h02803180000;  // land b3=b2^b3, b4=1, b5=~b0, b1=0
        94: ucode_q <= 42'h00000000000;
        95: ucode_q <= 42'h00000000000;
        96: ucode_q <= 42'h00000000000;
        97: ucode_q <= 42'h00000002440;  // issue r1=c0+r1
        98: ucode_q <= 42'h00000000000;
        99: ucode_q <= 42'h00000000000;
        100: ucode_q <= 42'h00000000000;
        101: ucode_q <= 42'h11420700000;  // commit r1; land r0=c2, b4=0, b3=0, b5=0, b2=b0
        102: ucode_q <= 42'h00000000000;
        103: ucode_q <= 42'h00000000000;
        104: ucode_q <= 42'h00000000000;
        105: ucode_q <= 42'h20000012440;  // issue r1=c0+r1, r0=r2×2^-1; land r6=float(b0)
        106: ucode_q <= 42'h00000420000;  // issue r7=r6×2^7; commit r0
        107: ucode_q <= 42'h00080000000;  // commit r7
        108: ucode_q <= 42'h00000000240;  // issue r2=r7+r0
        109: ucode_q <= 42'h00020000000;  // commit r1
        110: ucode_q <= 42'h00000000000;
        111: ucode_q <= 42'h00000000000;
        112: ucode_q <= 42'h01500700000;  // commit r2; land r0=c2, b4=0, b3=0, b5=0
        113: ucode_q <= 42'h00000000000;
        114: ucode_q <= 42'h00000000000;
        115: ucode_q <= 42'h00000000000;
        116: ucode_q <= 42'h01444900000;  // land b1=~b0&b1, r0=b0?r0:c2, r1=b0?r1:c0, b4=0, b3=0, b5=0
        117: ucode_q <= 42'h00000000000;
        118: ucode_q <= 42'h00000000000;
        119: ucode_q <= 42'h00000000000;
        120: ucode_q <= 42'h00000000000;
        default: ucode_q <= 42'h0;  // unreached (PC bounded to LASTPC); NOP fill
    endcase

// Decoded control fields. A field constant across the whole program is driven by a constant net (so synthesis prunes
// the logic it feeds); a varying field is a slice of the instruction word. The effect-trigger fields -- the ``gated``
// ones (operator issue strobes and per-register write opcodes) -- are ANDed with `transacting` HERE, so a held
// ucode[0] dwell, a fill bubble, or a stale pre-reset word decodes to 0 (NOP): no issue and every register holds.
// The AND wraps the constant branch too, so the gate stays unconditional even if a trigger ever folds to a constant.
wire        uc_issue_fcmp_46863199_0 = transacting & ucode_word[0 +: 1];
wire [ 1:0] uc_fcmp_46863199_0_asgn = 2'd0;
wire [ 2:0] uc_fcmp_46863199_0_ard = ucode_word[1 +: 3];
wire [ 1:0] uc_fcmp_46863199_0_bsgn = 2'd0;
wire [ 1:0] uc_fcmp_46863199_0_brd = ucode_word[4 +: 2];
wire        uc_issue_fadd_bc41e5c3_0 = transacting & ucode_word[6 +: 1];
wire [ 1:0] uc_fadd_bc41e5c3_0_asgn = ucode_word[7 +: 2];
wire [ 1:0] uc_fadd_bc41e5c3_0_ard = ucode_word[9 +: 2];
wire [ 1:0] uc_fadd_bc41e5c3_0_bsgn = ucode_word[11 +: 2];
wire [ 1:0] uc_fadd_bc41e5c3_0_brd = ucode_word[13 +: 2];
wire [ 1:0] uc_fadd_bc41e5c3_0_y0sgn = 2'd0;
wire        uc_issue_fmul_ilog2_const_085a5e09_0 = transacting & ucode_word[15 +: 1];
wire [ 1:0] uc_fmul_ilog2_const_085a5e09_0_asgn = 2'd0;
wire [ 1:0] uc_fmul_ilog2_const_085a5e09_0_y0sgn = 2'd0;
wire        uc_issue_fmul_ilog2_const_6b5098c4_0 = transacting & ucode_word[16 +: 1];
wire [ 1:0] uc_fmul_ilog2_const_6b5098c4_0_asgn = 2'd0;
wire [ 1:0] uc_fmul_ilog2_const_6b5098c4_0_y0sgn = 2'd0;
wire        uc_issue_fmul_ilog2_const_ea2ed72b_0 = transacting & ucode_word[17 +: 1];
wire [ 1:0] uc_fmul_ilog2_const_ea2ed72b_0_asgn = 2'd0;
wire [ 1:0] uc_fmul_ilog2_const_ea2ed72b_0_y0sgn = 2'd0;
wire [ 2:0] uc_op_b3 = {3{transacting}} & ucode_word[18 +: 3];
wire [ 2:0] uc_op_r0 = {3{transacting}} & ucode_word[21 +: 3];
wire [ 2:0] uc_op_b1 = {3{transacting}} & ucode_word[24 +: 3];
wire        uc_op_r3 = transacting & ucode_word[27 +: 1];
wire        uc_op_r5 = transacting & ucode_word[28 +: 1];
wire [ 1:0] uc_op_r1 = {2{transacting}} & ucode_word[29 +: 2];
wire        uc_op_r7 = transacting & ucode_word[31 +: 1];
wire [ 1:0] uc_op_r2 = {2{transacting}} & ucode_word[32 +: 2];
wire [ 1:0] uc_op_b4 = {2{transacting}} & ucode_word[34 +: 2];
wire [ 1:0] uc_op_b5 = {2{transacting}} & ucode_word[36 +: 2];
wire [ 1:0] uc_op_r4 = {2{transacting}} & ucode_word[38 +: 2];
wire        uc_op_b2 = transacting & ucode_word[40 +: 1];
wire        uc_op_r6 = transacting & ucode_word[41 +: 1];

holoso_fcmp #(
    .WEXP(4), .WMAN(8), .STAGE_INPUT(0), .LATENCY(1)
) u_fcmp_46863199_0 (
    .clk(clk), .rst(rst), .in_valid(uc_issue_fcmp_46863199_0),
    .a_sgnop(uc_fcmp_46863199_0_asgn),
    .b_sgnop(uc_fcmp_46863199_0_bsgn),
    .a(s_fcmp_46863199_0_a),
    .b(s_fcmp_46863199_0_b),
    .out_valid(),
    .a_gt_b(s_fcmp_46863199_0_y0),
    .a_eq_b(),
    .a_lt_b(s_fcmp_46863199_0_y2)
);

holoso_fadd #(
    .WEXP(4), .WMAN(8), .STAGE_INPUT(0), .STAGE_DECODE(0), .STAGE_ALIGN(0), .STAGE_NORMALIZE(0), .STAGE_PACK(0), .STAGE_OUTPUT(0), .LATENCY(4)
) u_fadd_bc41e5c3_0 (
    .clk(clk), .rst(rst), .in_valid(uc_issue_fadd_bc41e5c3_0),
    .a_sgnop(uc_fadd_bc41e5c3_0_asgn),
    .b_sgnop(uc_fadd_bc41e5c3_0_bsgn),
    .y_sgnop(uc_fadd_bc41e5c3_0_y0sgn),
    .a(s_fadd_bc41e5c3_0_a),
    .b(s_fadd_bc41e5c3_0_b),
    .out_valid(),
    .y(s_fadd_bc41e5c3_0_y0)
);

holoso_fmul_ilog2_const #(
    .WEXP(4), .WMAN(8), .K(1), .STAGE_INPUT(0), .STAGE_DECODE(0), .LATENCY(1)
) u_fmul_ilog2_const_085a5e09_0 (
    .clk(clk), .rst(rst), .in_valid(uc_issue_fmul_ilog2_const_085a5e09_0),
    .a_sgnop(uc_fmul_ilog2_const_085a5e09_0_asgn),
    .y_sgnop(uc_fmul_ilog2_const_085a5e09_0_y0sgn),
    .a(s_fmul_ilog2_const_085a5e09_0_a),
    .out_valid(),
    .y(s_fmul_ilog2_const_085a5e09_0_y0)
);

holoso_fmul_ilog2_const #(
    .WEXP(4), .WMAN(8), .K(-1), .STAGE_INPUT(0), .STAGE_DECODE(0), .LATENCY(1)
) u_fmul_ilog2_const_6b5098c4_0 (
    .clk(clk), .rst(rst), .in_valid(uc_issue_fmul_ilog2_const_6b5098c4_0),
    .a_sgnop(uc_fmul_ilog2_const_6b5098c4_0_asgn),
    .y_sgnop(uc_fmul_ilog2_const_6b5098c4_0_y0sgn),
    .a(s_fmul_ilog2_const_6b5098c4_0_a),
    .out_valid(),
    .y(s_fmul_ilog2_const_6b5098c4_0_y0)
);

holoso_fmul_ilog2_const #(
    .WEXP(4), .WMAN(8), .K(7), .STAGE_INPUT(0), .STAGE_DECODE(0), .LATENCY(1)
) u_fmul_ilog2_const_ea2ed72b_0 (
    .clk(clk), .rst(rst), .in_valid(uc_issue_fmul_ilog2_const_ea2ed72b_0),
    .a_sgnop(uc_fmul_ilog2_const_ea2ed72b_0_asgn),
    .y_sgnop(uc_fmul_ilog2_const_ea2ed72b_0_y0sgn),
    .a(s_fmul_ilog2_const_ea2ed72b_0_a),
    .out_valid(),
    .y(s_fmul_ilog2_const_ea2ed72b_0_y0)
);

assign err = 1'b0;

// Next-PC sequencer (combinational). The PC holds at the accept (pc==0) and present (pc==LASTPC) boundaries; bubble
// steps carry a NOP word and the PC keeps advancing. The executing step lags the fetch PC by FETCH_LAG. A block's
// terminator redirects the fetch PC at the block's boundary step (a branch reads its boolean register). Each branch
// also sets transacting_in -- 1 for a live accept/body word, 0 at the boundaries -- so each branch tags its own word.
always @* begin
    if (rst) begin
        next_pc        = 0;
        transacting_in = 1'b0;
    end else if (out_valid) begin  // present: hold until the result is taken
        next_pc        = out_ready ? 0 : LASTPC;
        transacting_in = 1'b0;
    end else if (in_ready) begin   // accept: hold until a transaction arrives
        next_pc        = in_valid ? 1 : 0;
        transacting_in = in_valid;
    end else begin                 // advance the fetch: the body of a live transaction
        transacting_in = 1'b1;
        case (pc)
            1: next_pc = bregs[1] ? 6 : 2;
            5: next_pc = 120;
            10: next_pc = bregs[3] ? 19 : 11;
            18: next_pc = 120;
            23: next_pc = bregs[3] ? 116 : 24;
            28: next_pc = bregs[3] ? 105 : 29;
            33: next_pc = bregs[3] ? 97 : 34;
            96: next_pc = 120;
            104: next_pc = 120;
            115: next_pc = 120;
            default: next_pc = pc + 1'b1;
        endcase
    end
end

// Operand read muxes: a per-port case over the read codebook (registers and constants), driving the wrapper.
always @* begin
    case (uc_fcmp_46863199_0_ard)
        3'd0: s_fcmp_46863199_0_a = regs[0];
        3'd1: s_fcmp_46863199_0_a = regs[2];
        3'd2: s_fcmp_46863199_0_a = const_3;
        3'd3: s_fcmp_46863199_0_a = const_5;
        3'd4: s_fcmp_46863199_0_a = const_6;
        default: s_fcmp_46863199_0_a = const_1;
    endcase
    case (uc_fcmp_46863199_0_brd)
        2'd0: s_fcmp_46863199_0_b = regs[1];
        2'd1: s_fcmp_46863199_0_b = regs[5];
        2'd2: s_fcmp_46863199_0_b = const_3;
        default: s_fcmp_46863199_0_b = const_1;
    endcase
    case (uc_fadd_bc41e5c3_0_ard)
        2'd0: s_fadd_bc41e5c3_0_a = regs[2];
        2'd1: s_fadd_bc41e5c3_0_a = regs[7];
        2'd2: s_fadd_bc41e5c3_0_a = const_0;
        default: s_fadd_bc41e5c3_0_a = const_1;
    endcase
    case (uc_fadd_bc41e5c3_0_brd)
        2'd0: s_fadd_bc41e5c3_0_b = regs[0];
        2'd1: s_fadd_bc41e5c3_0_b = regs[1];
        2'd2: s_fadd_bc41e5c3_0_b = regs[5];
        default: s_fadd_bc41e5c3_0_b = const_1;
    endcase
    s_fmul_ilog2_const_085a5e09_0_a = regs[4];
    s_fmul_ilog2_const_6b5098c4_0_a = regs[2];
    s_fmul_ilog2_const_ea2ed72b_0_a = regs[6];
end

// All sequential logic in one clocked process. Reset gates only the control state (pc, err_pc_q, transacting_q) and the
// persistent state registers; every other register is reset-unconditional. Each is driven by exactly one statement.
always @(posedge clk) begin
    // Microcode fetch: PC latch; ucode_word pipelines ucode_q.
    ucode_addr_q <= next_pc;
    ucode_word   <= ucode_q;

    // Register writes (reset-unconditional): one opcode-selected statement per register.
    if (uc_op_r3) regs[3] <= s_fadd_bc41e5c3_0_y0;
    case (uc_op_r4)
        2'd1: regs[4] <= (bregs[1] ? regs[3] : regs[2]);
        2'd2: regs[4] <= (bregs[3] ? regs[3] : regs[5]);
    endcase
    if (uc_op_r5) regs[5] <= s_fmul_ilog2_const_085a5e09_0_y0;
    if (uc_op_r6) regs[6] <= holoso_ffrombool(bregs[0]);
    if (uc_op_r7) regs[7] <= s_fmul_ilog2_const_ea2ed72b_0_y0;
    if (in_ready && in_valid) bregs[0] <= in_rx;
    case (uc_op_b3)
        3'd1: bregs[3] <= ~s_fcmp_46863199_0_y0;
        3'd2: bregs[3] <= ~s_fcmp_46863199_0_y2;
        3'd3: bregs[3] <= s_fcmp_46863199_0_y0;
        3'd4: bregs[3] <= 1'b0;
        3'd5: bregs[3] <= bregs[1] ^ bregs[3];
        3'd6: bregs[3] <= bregs[2] ^ bregs[3];
    endcase
    case (uc_op_b4)
        2'd1: bregs[4] <= 1'b0;
        2'd2: bregs[4] <= 1'b1;
    endcase
    case (uc_op_b5)
        2'd1: bregs[5] <= 1'b0;
        2'd2: bregs[5] <= ~bregs[0];
    endcase

    // Control and persistent state: the reset-gated registers.
    if (rst) begin
        pc            <= 0;
        err_pc_q      <= 0;
        transacting_q <= 0;
        regs[0] <= 12'h000;  // _count reset snapshot
        regs[1] <= 12'h000;  // _index reset snapshot
        regs[2] <= 12'h000;  // _char reset snapshot
        bregs[1] <= 1'b0;  // _busy reset snapshot
        bregs[2] <= 1'b0;  // _parity_rx reset snapshot
    end else begin
        pc <= next_pc;
        transacting_q <= (transacting_q << 1) | transacting_in;
        if (err) err_pc_q <= pc - FETCH_LAG;  // err wins; execution lags the fetch PC by FETCH_LAG, so step is pc-lag
        else if (in_ready && in_valid) err_pc_q <= 0;  // clear the diagnostic when a new transaction is accepted
        case (uc_op_r0)
            3'd1: regs[0] <= s_fadd_bc41e5c3_0_y0;
            3'd2: regs[0] <= s_fmul_ilog2_const_6b5098c4_0_y0;
            3'd3: regs[0] <= const_2;
            3'd4: regs[0] <= (bregs[0] ? regs[0] : const_2);
            3'd5: regs[0] <= (~bregs[0] ? const_4 : regs[0]);
        endcase
        case (uc_op_r1)
            2'd1: regs[1] <= s_fadd_bc41e5c3_0_y0;
            2'd2: regs[1] <= (bregs[0] ? regs[1] : const_0);
            2'd3: regs[1] <= (~bregs[0] ? const_3 : regs[1]);
        endcase
        case (uc_op_r2)
            2'd1: regs[2] <= s_fadd_bc41e5c3_0_y0;
            2'd2: regs[2] <= (~bregs[0] ? const_3 : regs[2]);
        endcase
        case (uc_op_b1)
            3'd1: bregs[1] <= ~s_fcmp_46863199_0_y2;
            3'd2: bregs[1] <= bregs[1] ^ bregs[3];
            3'd3: bregs[1] <= 1'b0;
            3'd4: bregs[1] <= ~bregs[0] & bregs[1];
            3'd5: bregs[1] <= ~bregs[0] | bregs[1];
        endcase
        if (uc_op_b2) bregs[2] <= bregs[0];
    end
end

assign in_ready  = (pc == 0);
assign out_valid = (pc == LASTPC);  // result valid on PRESENT; execution lags the fetch by FETCH_LAG
assign err_pc    = err_pc_q;
assign out_0 = bregs[4];
assign out_1 = regs[2];
assign out_2 = bregs[3];
assign out_3 = bregs[5];

endmodule
