"""Functional cosimulation: drive generated modules and check their outputs bit-for-bit against the model backend."""

import math
from collections.abc import Mapping

import numpy as np
import pytest
from cocotb_tools.runner import get_runner

import holoso
from holoso import (
    FAddOptions,
    FCmpOptions,
    FDivOptions,
    FMulILog2Options,
    FMulOptions,
    FSortOptions,
    FloatFormat,
    OperatorOptions,
    Options,
)
from holoso._backend.verilog import generate as generate_verilog
from holoso._eel import lower
from holoso._lir import pooled_write_word
from holoso._mir import lower as lower_to_mir

from holoso._value import ScalarLike
from ._cosim import run_cosim
from ._modelref import (
    branch_boundary_kernel,
    build_lir,
    mir_options,
    ChainedSlots,
    COMPARATOR_OPTIONS_CASES,
    const_branch_kernel,
    default_options,
    DEFAULT_UNROLL_MAX_TRIPS,
    diamond_then_loop_kernel,
    OptionsCase,
    overlap_dead_arm_spill_kernel,
    overlap_div_err_kernel,
    overlap_spill_kernel,
    phi_swap_computed_loop,
    PIPELINE_OPTIONS_CASES,
    SelectHold,
    SharedLiveOut,
    SharedLiveOutBool,
    staged_options,
)
from .hdl.hdl_float_oracle import HDL_DIR, REPO_ROOT, SIMULATORS, build_args, sources

pytestmark = pytest.mark.cosim


@pytest.mark.parametrize("sim", SIMULATORS)
def test_cosim_small_kernel(sim: str) -> None:
    def kernel(a: float, b: float) -> float:
        return (a - b) * 0.25 + a * b

    run_cosim(sim, holoso.synthesize(kernel, default_options(FloatFormat(8, 24)), name="kernel"))


@pytest.mark.parametrize("config", COMPARATOR_OPTIONS_CASES, ids=lambda config: config.label)
@pytest.mark.parametrize("sim", SIMULATORS)
def test_cosim_comparison_at_branch_boundary(sim: str, config: OptionsCase) -> None:
    # The boundary-slack corner kernel (see _modelref.branch_boundary_kernel), exercised at both comparator-only and
    # full-pipeline latency points. The white-box twin in test_schedule.py
    # (test_branch_comparison_commits_at_block_makespan) pins that this kernel actually hits the corner.
    fmt = FloatFormat(6, 18)
    result = holoso.synthesize(branch_boundary_kernel, config.make_options(fmt), name=f"cmp_branch_{config.label}")
    run_cosim(sim, result)


@pytest.mark.parametrize("config", COMPARATOR_OPTIONS_CASES, ids=lambda config: config.label)
@pytest.mark.parametrize("sim", SIMULATORS)
def test_cosim_overlap_spill(sim: str, config: OptionsCase) -> None:
    # Cross-block software pipelining: the entry block shrinks its terminator to a wide chain's write word, and
    # that result spills past the terminator into BOTH single-predecessor arms, which read it. If the arm read did not
    # wait for the in-flight landing in the successor frame -- or the spill mis-aligned by even one frame -- the RTL
    # would diverge from the cycle-accurate model here. The white-box twin
    # (test_schedule.py test_overlap_spilled_result_lands_in_successor_frame) pins that the spill actually triggers.
    # See _modelref.overlap_spill_kernel. The staged cases move the early condition's landing relative to the spilling
    # chain, and the full staged case also moves the wide chain itself.
    fmt = FloatFormat(6, 18)
    result = holoso.synthesize(overlap_spill_kernel, config.make_options(fmt), name=f"overlap_spill_{config.label}")
    run_cosim(sim, result)


@pytest.mark.parametrize("config", COMPARATOR_OPTIONS_CASES, ids=lambda config: config.label)
@pytest.mark.parametrize("sim", SIMULATORS)
def test_cosim_const_branch(sim: str, config: OptionsCase) -> None:
    # Drained-boundary (round-5 fix): an empty const-branch block's condition is a pc-gated install read AT the
    # terminator, landing at the drained boundary; the drain must not shrink below it or the branch reads
    # the condition one PC before it lands. The model crashes (KeyError) on the first transaction, but a stale-register
    # branch misdirect is a SILENT RTL miscompile only cosim discriminates (RTL vs model from one LIR). The white-box
    # twin (test_schedule.py test_const_branch_install_block_drains_to_its_inline_landing) pins the block stays at the
    # drained boundary.
    fmt = FloatFormat(6, 18)
    result = holoso.synthesize(const_branch_kernel, config.make_options(fmt), name=f"const_branch_{config.label}")
    run_cosim(sim, result)


@pytest.mark.parametrize("config", COMPARATOR_OPTIONS_CASES, ids=lambda config: config.label)
@pytest.mark.parametrize("sim", SIMULATORS)
def test_cosim_diamond_then_loop(sim: str, config: OptionsCase) -> None:
    # Empty merge-block elimination (B4): threading the non-convertible diamond's empty merge onto its arms composes
    # its phi arms into the loop header, producing a THREE-arm loop-header phi (two forward init arms from the diamond
    # arms plus the back-edge) -- a phi shape no other kernel pushes through the RTL emitter. The model and RTL are
    # generated by different paths from one LIR, so only cosim discriminates a wrong emitter assumption (e.g. a loop-
    # header phi having exactly two arms) from a self-consistent model. The white-box twin
    # (test_schedule.py test_empty_merge_block_is_threaded_into_its_successor) pins that the merge was actually removed.
    fmt = FloatFormat(6, 18)
    result = holoso.synthesize(
        diamond_then_loop_kernel, config.make_options(fmt), name=f"diamond_then_loop_{config.label}"
    )
    run_cosim(sim, result)


@pytest.mark.parametrize("config", COMPARATOR_OPTIONS_CASES, ids=lambda config: config.label)
@pytest.mark.parametrize("sim", SIMULATORS)
def test_cosim_overlap_dead_arm_spill(sim: str, config: OptionsCase) -> None:
    # P3a tightened the cross-block spill carry to the model's true landing PC (land - term_offset - 1), changing the
    # emitted Verilog for this kernel. cosim is the orthogonal gate to the source-semantic dead-arm test: it proves the
    # RTL's register write timing stays lockstep with the model's _pending re-keying under the tighter read-gate (the
    # model and RTL are generated by different paths from one LIR). See _modelref.overlap_dead_arm_spill_kernel; the
    # silent clobber it guards against is caught by test_schedule.py, not here (model and RTL share the register file).
    fmt = FloatFormat(6, 18)
    result = holoso.synthesize(
        overlap_dead_arm_spill_kernel, config.make_options(fmt), name=f"overlap_dead_arm_spill_{config.label}"
    )
    run_cosim(sim, result)


@pytest.mark.parametrize("sim", SIMULATORS)
def test_cosim_min_max(sim: str) -> None:
    # Binary min/max lower to holoso_fsort. Taking BOTH min and max of one pair fuses to a SINGLE firing that writes
    # two wide registers at once -- the first operator to do so -- so this proves the generated RTL lands both results
    # bit-exactly against the model. The |a|,|b| sort in a second firing exercises the operand sign conditioners.
    def kernel(a: float, b: float) -> tuple[float, ...]:
        return min(a, b), max(a, b), min(abs(a), abs(b))

    options = Options(
        OperatorOptions(
            fadd=FAddOptions(),
            fmul=FMulOptions(),
            fdiv=FDivOptions(),
            fmul_ilog2=FMulILog2Options(),
            fcmp=FCmpOptions(),
            fsort=FSortOptions(),
        ),
        ffmt=FloatFormat(8, 24),
    )
    run_cosim(sim, holoso.synthesize(kernel, options, name="min_max"))


class _ShiftRegister2:
    """A two-deep delay line returning the input from two steps ago; both state slots are non-coalesced copy slots."""

    def __init__(self) -> None:
        self._a = 0.0
        self._b = 0.0

    def __call__(self, x: float) -> float:
        out = self._b
        self._b = self._a
        self._a = x
        return out


class _UnusedBoolInputAccumulator:
    def __init__(self) -> None:
        self.y = 0.0

    def __call__(self, flag: bool, x: float) -> float:
        self.y = self.y + x + 1.0
        return self.y


@pytest.mark.parametrize("config", PIPELINE_OPTIONS_CASES, ids=lambda config: config.label)
@pytest.mark.parametrize("sim", SIMULATORS)
def test_cosim_shift_register_backpressure(sim: str, config: OptionsCase) -> None:
    # The returned value taps a copy-slot register and the chain advances every accept, so together with the testbench's
    # random back-pressure this pins down that the boundary copy fires exactly once per accepted transaction -- no
    # mid-handshake output mutation and no state over-advance while out_ready is held low.
    fmt = FloatFormat(6, 18)
    result = holoso.synthesize(_ShiftRegister2().__call__, config.make_options(fmt), name=f"shift2_{config.label}")
    run_cosim(sim, result)


@pytest.mark.parametrize("config", PIPELINE_OPTIONS_CASES, ids=lambda config: config.label)
@pytest.mark.parametrize("sim", SIMULATORS)
def test_cosim_unused_bool_input_keeps_cfg_state_timing(sim: str, config: OptionsCase) -> None:
    fmt = FloatFormat(6, 18)
    vectors: list[Mapping[str, ScalarLike]] = [
        {"flag": False, "x": 2.0},
        {"flag": True, "x": 4.0},
    ]
    result = holoso.synthesize(
        _UnusedBoolInputAccumulator().__call__, config.make_options(fmt), name=f"unused_bool_state_{config.label}"
    )
    run_cosim(sim, result, vectors=vectors)


@pytest.mark.parametrize("sim", SIMULATORS)
def test_cosim_new_operator_stages(sim: str) -> None:
    def kernel(a: float, b: float, c: float) -> float:
        return (a - b) / c + a * b * 0.25  # fadd, fdiv, fmul, and fmul_ilog2 (the 2^-2 scale) all in one kernel

    # Exercise the newly-shipped ZKF knobs end-to-end: fadd STAGE_INPUT/STAGE_NORMALIZE/STAGE_PACK, fmul STAGE_PACK,
    # fdiv STAGE_PACK, and fmul_ilog2 STAGE_INPUT -- all folded into the latency model and the latched datapath.
    options = Options(
        OperatorOptions(
            fadd=FAddOptions(stage_input=1, stage_normalize=2, stage_pack=1),
            fmul=FMulOptions(stage_input=1, stage_pack=1),
            fdiv=FDivOptions(stage_pack=1),
            fmul_ilog2=FMulILog2Options(stage_input=1),
            fcmp=FCmpOptions(),
        ),
        ffmt=FloatFormat(8, 24),
    )
    run_cosim(sim, holoso.synthesize(kernel, options, name="new_stages"))


# The generated bench only checks err_pc == 0 over a bounded input range, so it never exercises the div0 -> err_pc
# path. This custom bench drives an exact zero divisor and asserts the diagnostic is set, then cleared on the next
# accepted transaction. It cannot reuse the generated bench because the numerical model does not predict errors.
_ERR_BENCH = """
import cocotb
from cocotb.clock import Clock
from cocotb.triggers import FallingEdge, RisingEdge, Timer
import holoso

_FMT = holoso.FloatFormat(@@WEXP@@, @@WMAN@@)


async def _transact(dut, a, b):
    while int(dut.in_ready.value) != 1:
        await RisingEdge(dut.clk)
        await Timer(1, unit="ns")
    dut.in_a.value = int(_FMT.encode(a))
    dut.in_b.value = int(_FMT.encode(b))
    dut.in_valid.value = 1
    await RisingEdge(dut.clk)
    await Timer(1, unit="ns")
    dut.in_valid.value = 0
    while int(dut.out_valid.value) != 1:
        await RisingEdge(dut.clk)
        await Timer(1, unit="ns")
    err = int(dut.err_pc.value)
    await RisingEdge(dut.clk)
    await Timer(1, unit="ns")
    return err


@cocotb.test()
async def div0_errpc(dut):
    cocotb.start_soon(Clock(dut.clk, 10, unit="ns").start())
    await FallingEdge(dut.clk)
    dut.rst.value = 1
    dut.in_valid.value = 0
    for _ in range(4):
        await RisingEdge(dut.clk)
    dut.rst.value = 0
    await FallingEdge(dut.clk)
    dut.out_ready.value = 1

    assert await _transact(dut, 6.0, 2.0) == 0, "clean divide spuriously flagged err_pc"
    assert await _transact(dut, 1.0, 0.0) != 0, "divide-by-zero did not set err_pc"
    assert await _transact(dut, 6.0, 2.0) == 0, "err_pc was not cleared on the next transaction"
"""


def _run_err_bench(sim: str, name: str, fmt: FloatFormat, verilog: str, bench_text: str, suffix: str = "err") -> None:
    """Build `name`'s RTL plus a custom error-checking cocotb bench and run it -- the shared tail of the err tests."""
    gen_dir = REPO_ROOT / "build" / "holoso_gen" / sim / f"{name}_{suffix}_w{fmt.wexp}_{fmt.wman}"
    gen_dir.mkdir(parents=True, exist_ok=True)
    build_dir = REPO_ROOT / "build" / "cocotb" / sim / f"{suffix}_{name}_w{fmt.wexp}_{fmt.wman}"
    (gen_dir / f"{name}.v").write_text(verilog)
    test_module = f"test_{name}_{suffix}"
    (gen_dir / f"{test_module}.py").write_text(bench_text)
    runner = get_runner(sim)
    runner.build(
        sources=[gen_dir / f"{name}.v", *sources()],
        includes=[HDL_DIR],
        hdl_toplevel=name,
        build_args=build_args(sim),
        build_dir=str(build_dir),
        clean=True,
        timescale=("1ns", "1ps"),
    )
    runner.test(
        hdl_toplevel=name,
        test_module=test_module,
        test_dir=str(gen_dir),
        build_dir=str(build_dir),
        results_xml=str(build_dir / "results.xml"),
    )


@pytest.mark.parametrize("sim", SIMULATORS)
def test_cosim_div0_error(sim: str) -> None:
    # Staged only: this is the one public-entry row where the error rides fdiv's full stage pipeline.
    def kdiv(a: float, b: float) -> float:
        return a / b

    fmt = FloatFormat(6, 18)
    name = "kdiv_staged"
    verilog = holoso.synthesize(kdiv, staged_options(fmt), name=name).verilog_output.verilog
    bench = _ERR_BENCH.replace("@@WEXP@@", str(fmt.wexp)).replace("@@WMAN@@", str(fmt.wman))
    _run_err_bench(sim, name, fmt, verilog, bench)


# log2 has two error ports (domain_error for x<0, pole for x==0), both ORed into the single err_pc. Like div0, the
# generated bench never reaches the error path (it asserts err_pc == 0 and the numerical model does not predict errors),
# so this custom bench drives both error operands and asserts err_pc latches for each, then clears.
_LOG2_ERR_BENCH = """
import cocotb
from cocotb.clock import Clock
from cocotb.triggers import FallingEdge, RisingEdge, Timer
import holoso

_FMT = holoso.FloatFormat(@@WEXP@@, @@WMAN@@)


async def _transact(dut, x):
    while int(dut.in_ready.value) != 1:
        await RisingEdge(dut.clk)
        await Timer(1, unit="ns")
    dut.in_x.value = int(_FMT.encode(x))
    dut.in_valid.value = 1
    await RisingEdge(dut.clk)
    await Timer(1, unit="ns")
    dut.in_valid.value = 0
    while int(dut.out_valid.value) != 1:
        await RisingEdge(dut.clk)
        await Timer(1, unit="ns")
    err = int(dut.err_pc.value)
    await RisingEdge(dut.clk)
    await Timer(1, unit="ns")
    return err


@cocotb.test()
async def log2_errpc(dut):
    cocotb.start_soon(Clock(dut.clk, 10, unit="ns").start())
    await FallingEdge(dut.clk)
    dut.rst.value = 1
    dut.in_valid.value = 0
    for _ in range(4):
        await RisingEdge(dut.clk)
    dut.rst.value = 0
    await FallingEdge(dut.clk)
    dut.out_ready.value = 1

    assert await _transact(dut, 8.0) == 0, "clean log2 spuriously flagged err_pc"
    assert await _transact(dut, 0.0) != 0, "log2(+0) pole did not set err_pc"
    assert await _transact(dut, 8.0) == 0, "err_pc was not cleared after the pole"
    assert await _transact(dut, -4.0) != 0, "log2(x<0) domain error did not set err_pc"
    assert await _transact(dut, 8.0) == 0, "err_pc was not cleared after the domain error"
"""


@pytest.mark.parametrize("config", PIPELINE_OPTIONS_CASES, ids=lambda config: config.label)
@pytest.mark.parametrize("sim", SIMULATORS)
def test_cosim_log2_error(sim: str, config: OptionsCase) -> None:
    def klog2(x: float) -> float:
        return math.log2(x)

    fmt = FloatFormat(6, 18)
    name = f"klog2_{config.label}"
    verilog = holoso.synthesize(klog2, config.make_options(fmt), name=name).verilog_output.verilog
    bench = _LOG2_ERR_BENCH.replace("@@WEXP@@", str(fmt.wexp)).replace("@@WMAN@@", str(fmt.wman))
    _run_err_bench(sim, name, fmt, verilog, bench)


# A 3-input variant of the err bench for the cross-block-overlap err_pc corner: it asserts the EXACT latched step
# (not merely nonzero), since the regression set err_pc to a wrong-but-nonzero value (the redirected successor frame).
_ERR_BENCH3 = """
import cocotb
from cocotb.clock import Clock
from cocotb.triggers import FallingEdge, RisingEdge, Timer
import holoso

_FMT = holoso.FloatFormat(@@WEXP@@, @@WMAN@@)


async def _transact(dut, x, y, z):
    while int(dut.in_ready.value) != 1:
        await RisingEdge(dut.clk)
        await Timer(1, unit="ns")
    dut.in_x.value = int(_FMT.encode(x))
    dut.in_y.value = int(_FMT.encode(y))
    dut.in_z.value = int(_FMT.encode(z))
    dut.in_valid.value = 1
    await RisingEdge(dut.clk)
    await Timer(1, unit="ns")
    dut.in_valid.value = 0
    while int(dut.out_valid.value) != 1:
        await RisingEdge(dut.clk)
        await Timer(1, unit="ns")
    err = int(dut.err_pc.value)
    await RisingEdge(dut.clk)
    await Timer(1, unit="ns")
    return err


@cocotb.test()
async def overlap_div0_errpc(dut):
    cocotb.start_soon(Clock(dut.clk, 10, unit="ns").start())
    await FallingEdge(dut.clk)
    dut.rst.value = 1
    dut.in_valid.value = 0
    for _ in range(4):
        await RisingEdge(dut.clk)
    dut.rst.value = 0
    await FallingEdge(dut.clk)
    dut.out_ready.value = 1

    # x<z takes the NON-fall-through (true) arm; y==0 errs the entry-block division, whose result spills past the
    # shrunk terminator. err_pc must still latch the division's own step (@@ERRPC@@), not the redirected successor PC.
    assert await _transact(dut, 1.0, 2.0, 3.0) == 0, "clean divide on the overlapped arm spuriously flagged err_pc"
    assert await _transact(dut, 0.0, 0.0, 1.0) == @@ERRPC@@, "div0 latched the wrong err_pc step across the redirect"
    assert await _transact(dut, 1.0, 2.0, 3.0) == 0, "err_pc was not cleared after the erroring transaction"
"""


@pytest.mark.parametrize("config", COMPARATOR_OPTIONS_CASES, ids=lambda config: config.label)
@pytest.mark.parametrize("sim", SIMULATORS)
def test_cosim_overlap_div0_errpc(sim: str, config: OptionsCase) -> None:
    # Overlap regression: an error-bearing division whose result spills past a SHRUNK
    # terminator must still latch err_pc to its OWN step, not the redirected non-fall-through successor frame. The data
    # is correct regardless (model == RTL), so only this step-exact err_pc cosim catches the regression. White-box
    # twin: test_schedule.py::test_overlap_keeps_error_op_diagnostic_latch_in_frame. See
    # _modelref.overlap_div_err_kernel. The expected err_pc step has no public spelling, so this test stays on the
    # private LIR chain and emits the RTL from the same LIR it reads the step from.
    fmt = FloatFormat(6, 18)
    name = f"overlap_div_err_{config.label}"
    options = config.make_options(fmt)
    lir = build_lir(
        lower_to_mir(lower(overlap_div_err_kernel, DEFAULT_UNROLL_MAX_TRIPS).hir, mir_options(options)),
        name,
    )
    entry = next(block for block in lir.blocks if block.index == lir.entry)
    (fdiv,) = [op for op in entry.ops if op.inst.operator.error_ports]
    err_pc = lir.block_base[entry.index] + pooled_write_word(fdiv.commit_cycle)
    bench = (
        _ERR_BENCH3.replace("@@WEXP@@", str(fmt.wexp))
        .replace("@@WMAN@@", str(fmt.wman))
        .replace("@@ERRPC@@", str(err_pc))
    )
    _run_err_bench(sim, name, fmt, generate_verilog(lir).verilog, bench, suffix="errpc")


@pytest.mark.parametrize(
    "config",
    [config for config in COMPARATOR_OPTIONS_CASES if config.label != "staged"],
    ids=lambda config: config.label,
)
@pytest.mark.parametrize("sim", SIMULATORS)
def test_cosim_mirrored_comparisons_swap_orientation(sim: str, config: OptionsCase) -> None:
    # RTL twin of test_schedule.test_commutative_comparator_swap_permutes_output_taps: mirrored comparisons over one
    # operand pair make the port assignment orient one comparator firing swapped (its lt tap moving to gt), so the
    # emitted module must still produce both relations bit-exactly through the permuted lane. The default row checks
    # the port permutation and fcmp_s1 the delayed comparator taps; full staging adds no new mapping here.
    def kernel(a: float, b: float) -> tuple[float, ...]:
        below = a < b
        above = b < a
        return float(below), float(above)

    fmt = FloatFormat(6, 18)
    run_cosim(sim, holoso.synthesize(kernel, config.make_options(fmt), name=f"mirrored_cmp_{config.label}"))


@pytest.mark.parametrize("config", PIPELINE_OPTIONS_CASES, ids=lambda config: config.label)
@pytest.mark.parametrize("sim", SIMULATORS)
def test_cosim_chained_slots_keep_the_old_value_across_the_install(sim: str, config: OptionsCase) -> None:
    # RTL twin of test_schedule.test_chained_slot_live_in_blocks_early_install: before the fix, "_b"'s early install
    # clobbered the value "_a"'s boundary copy reads, so the DUT diverged from the model on the second transaction.
    fmt = FloatFormat(6, 18)
    result = holoso.synthesize(ChainedSlots().__call__, config.make_options(fmt), name=f"chained_slots_{config.label}")
    run_cosim(sim, result)


@pytest.mark.parametrize("config", COMPARATOR_OPTIONS_CASES, ids=lambda config: config.label)
@pytest.mark.parametrize("sim", SIMULATORS)
def test_cosim_select_kernels(sim: str, config: OptionsCase) -> None:
    # If-converted selects in RTL: both polarities of a max kernel, an arm-sign select (the negation rides the
    # operand conditioner), and a comparison -> select -> arithmetic cross-bank chain, in one kernel.
    def kernel(a: float, b: float) -> float:
        m = a if a > b else b
        s = a if b > 0.0 else -a
        return m * 2.0 + s

    fmt = FloatFormat(6, 18)
    run_cosim(sim, holoso.synthesize(kernel, config.make_options(fmt), name=f"select_mix_{config.label}"))


@pytest.mark.parametrize("config", COMPARATOR_OPTIONS_CASES, ids=lambda config: config.label)
@pytest.mark.parametrize("sim", SIMULATORS)
def test_cosim_select_reads_state_live_in_before_early_install(sim: str, config: OptionsCase) -> None:
    # RTL twin of test_schedule.test_state_early_install_respects_a_select_reader: the slot's early install must not
    # fire before the Ret-block select reads the OLD live-in value.
    fmt = FloatFormat(6, 18)
    run_cosim(sim, holoso.synthesize(SelectHold().step, config.make_options(fmt), name=f"select_hold_{config.label}"))


@pytest.mark.parametrize("config", COMPARATOR_OPTIONS_CASES, ids=lambda config: config.label)
@pytest.mark.parametrize("sim", SIMULATORS)
def test_cosim_not_folding_sinks(sim: str, config: OptionsCase) -> None:
    # NOT-folding in RTL: inverted logic operands, an inverted bool output path (via the casts), both polarities of
    # one comparison, and a self-toggling inverted boolean state slot, across several transactions.
    class Toggle:
        def __init__(self) -> None:
            self._flip = False

        def step(self, a: float, b: float) -> float:
            old = self._flip
            self._flip = not self._flip
            gate = not (a > b)
            both = gate and (not (b > a))
            return float(gate) + 2.0 * float(both) + (4.0 if old else 0.0)

    fmt = FloatFormat(6, 18)
    run_cosim(sim, holoso.synthesize(Toggle().step, config.make_options(fmt), name=f"not_sinks_{config.label}"))


@pytest.mark.parametrize("config", COMPARATOR_OPTIONS_CASES, ids=lambda config: config.label)
@pytest.mark.parametrize("sim", SIMULATORS)
def test_cosim_inverted_bool_phi_arm(sim: str, config: OptionsCase) -> None:
    # RTL twin of test_schedule.test_inverted_bool_phi_arm_installs_with_opposite_polarities: the conditional flag
    # negation rides the phi-arm install's inversion.
    def kernel(a: float, b: float, c: float) -> tuple[float, ...]:
        flag = a > b
        if c > 0.0:
            flag = not flag
            d = a / (c * c + 1.0)
        else:
            d = b
        return float(flag), d

    fmt = FloatFormat(6, 18)
    run_cosim(sim, holoso.synthesize(kernel, config.make_options(fmt), name=f"inverted_arm_{config.label}"))


@pytest.mark.parametrize("config", COMPARATOR_OPTIONS_CASES, ids=lambda config: config.label)
@pytest.mark.parametrize("sim", SIMULATORS)
def test_cosim_phi_coalescing_residual_install_conflict(sim: str, config: OptionsCase) -> None:
    # RTL twin of test_schedule.test_phi_coalescing_residual_install_conflict_is_resolved: phi `a` would coalesce onto
    # input `x`'s register, but `x` is still live as sibling phi `z`'s identity arm (`z = x`) where `a`'s
    # residual sign-folded else-arm install writes that register, so the soundness fixpoint de-coalesces `a`. This
    # proves the de-coalesced residual install is bit-exact in RTL, not only against the Python cycle model. The
    # division keeps the diamond a real branch (un-if-converted), which is what creates the phi merge.
    def kernel(x: float, b: float, cc: float) -> tuple[float, ...]:
        if b < cc:
            a = x
            z = 1.0
            d = b
        else:
            a = -(x + 1.0)
            z = x
            d = x / b
        return a, z, d

    fmt = FloatFormat(6, 18)
    run_cosim(sim, holoso.synthesize(kernel, config.make_options(fmt), name=f"coal_conflict_{config.label}"))


@pytest.mark.parametrize("config", COMPARATOR_OPTIONS_CASES, ids=lambda config: config.label)
@pytest.mark.parametrize("sim", SIMULATORS)
def test_cosim_not_over_loop_phi_and_inverted_public_state(sim: str, config: OptionsCase) -> None:
    # Two NOT-folding corners under RTL: a flag negated per trip of a while loop (the self-arm inversion install
    # fires once per iteration through the back edge), and a PUBLIC boolean state attribute whose live-out is a
    # negation (the state_<attr> port and the install both ride inversions).
    class LoopToggle:
        def __init__(self) -> None:
            self.armed = False

        def step(self, x: float) -> float:
            flag = x > 0.0
            w = x
            while w > 1.0:
                flag = not flag
                w = w - 1.0
            self.armed = not (x > 2.0)
            return float(flag)

    fmt = FloatFormat(6, 18)
    run_cosim(sim, holoso.synthesize(LoopToggle().step, config.make_options(fmt), name=f"loop_toggle_{config.label}"))


@pytest.mark.parametrize("sim", SIMULATORS)
def test_cosim_two_sincos_share_ii_instance(sim: str) -> None:
    # Two independent sincos time-share one II>1 CORDIC; the schedule must space issues by the initiation interval.
    # Under-spacing drops the second in_valid (SIMULATION $fatal) or diverges from the model -- end-to-end II>1 proof.
    def kernel(a: float, b: float) -> tuple[float, float, float, float]:
        return math.sin(a), math.cos(a), math.sin(b), math.cos(b)

    run_cosim(sim, holoso.synthesize(kernel, default_options(FloatFormat(8, 24)), name="cs_two_sincos"))


@pytest.mark.parametrize("sim", SIMULATORS)
def test_cosim_two_atan2_share_ii_instance(sim: str) -> None:
    # The fatan2 twin of test_cosim_two_sincos: deeper latency than fsincos, so a distinct re-accept boundary the
    # schedule must space by the initiation interval.
    def kernel(a: float, b: float, c: float, d: float) -> tuple[float, float]:
        return math.atan2(a, b), math.atan2(c, d)

    run_cosim(sim, holoso.synthesize(kernel, default_options(FloatFormat(8, 24)), name="cs_two_atan2"))


@pytest.mark.parametrize("sim", SIMULATORS)
def test_cosim_atan2_hypot_fused(sim: str) -> None:
    # hypot and atan2 over one operand pair fuse into a single CORDIC firing (theta + magnitude).
    def kernel(y: float, x: float) -> tuple[float, float]:
        return math.hypot(y, x), math.atan2(y, x)

    run_cosim(sim, holoso.synthesize(kernel, default_options(FloatFormat(8, 24)), name="cs_atan2_hypot"))


@pytest.mark.parametrize("sim", SIMULATORS)
def test_cosim_library_composites(sim: str) -> None:
    # Composite library stubs end-to-end: cbrt's sign/exp2/log2 expansion behind its zero guard, tan's sincos+div,
    # the pow rung ladder under a static exponent, sinh's exp difference, and tanh's stable sigmoid form -- all
    # bit-exact against the model backend.
    def kernel(x: float, y: float) -> tuple[float, float, float, float, float]:
        return math.cbrt(x), math.tan(y), pow(x, 3.0), math.sinh(x), math.tanh(y)

    run_cosim(sim, holoso.synthesize(kernel, default_options(FloatFormat(8, 24)), name="cs_lib_composites"))


@pytest.mark.parametrize("sim", SIMULATORS)
def test_cosim_tan_pole_latches_no_error(sim: str) -> None:
    # At the format-nearest pi/2, cos rounds to exactly zero. tan's c==0 guard is a real branch (the divide is
    # unspeculatable, so if-conversion cannot fold it into an always-executed select), which skips the divide at the
    # pole -- so no divide-by-zero error is latched. The bench asserts err_pc==0 on every vector, so an unguarded
    # sin/cos would fail here; a normal input in the same run confirms the divide path still works.
    def kernel(x: float) -> float:
        return math.tan(x)

    fmt = FloatFormat(8, 24)
    pole = float(np.float32(math.pi / 2))
    vectors: list[Mapping[str, ScalarLike]] = [
        {"x": pole},
        {"x": -pole},
        {"x": 0.5},
    ]
    run_cosim(sim, holoso.synthesize(kernel, default_options(fmt), name="cs_tan_pole"), vectors=vectors)


@pytest.mark.parametrize("sim", SIMULATORS)
def test_cosim_phi_swap_computed_arm(sim: str) -> None:
    # The RTL leg of the computed-arm swap regression (see test_interpret): the DUT replays the same LIR as the model,
    # so this pins the emitted install words against the bench's bit-exact model across multi-trip loop executions.
    # Explicit vectors keep the while trip count small; the bench's own sweep would draw huge counts.
    fmt = FloatFormat(6, 18)
    vectors: list[Mapping[str, ScalarLike]] = [{"x": x, "n": n} for x in (1.0, 2.0, -1.5) for n in (1.0, 2.0, 4.0)]
    result = holoso.synthesize(phi_swap_computed_loop, default_options(fmt), name="cs_phi_swap_computed")
    run_cosim(sim, result, vectors=vectors)


@pytest.mark.parametrize("sim", SIMULATORS)
def test_cosim_shared_live_out_state_slots(sim: str) -> None:
    # The install arm outranks the opcode arm in the same statement, so if the two could ever be enabled on one PC the
    # DUT would diverge from the model here -- across a persistent recurrence, on the very first transaction.
    # _modelref.SharedLiveOut is the one home of this kernel; its elaboration/premise twin lives in test_backend.
    result = holoso.synthesize(SharedLiveOut().step, default_options(FloatFormat(6, 18)), name="shared_live_out")
    run_cosim(sim, result)


@pytest.mark.parametrize("sim", SIMULATORS)
def test_cosim_shared_live_out_bool_state_slots(sim: str) -> None:
    # The boolean bank leans on the same priority argument as the wide one, and boolean installs are boundary-only, so
    # a shadowed write here would diverge from the model on the recurrence rather than on a single transaction.
    result = holoso.synthesize(
        SharedLiveOutBool().step, default_options(FloatFormat(6, 18)), name="shared_bool_live_out"
    )
    run_cosim(sim, result)
