"""
Kernels generated at runtime: a function `exec`'d from source text the host built, with no file behind it. Source
retrieval goes through `inspect.getsourcelines`, which `linecache` satisfies without a filesystem entry, so a
generated function synthesizes as the root and inlines as a callee -- including when it is reached through an
instance attribute of a stateful root, the shape a SymPy-style lambdify held by a constructor produces.
"""

import itertools
import linecache
import types
from collections.abc import Callable

import pytest

import holoso
from holoso import FAddOptions, FMulILog2Options, FMulOptions, OperatorOptions, Options, SourceUnavailable

_OPTIONS = Options(OperatorOptions(fadd=FAddOptions(), fmul=FMulOptions(), fmul_ilog2=FMulILog2Options()))

_counter = itertools.count()


def _generate(body: str, *, register: bool = True) -> types.FunctionType:
    source = f"def _generated(x: float, y: float) -> float:\n    return {body}\n"
    filename = f"<holoso-test-generated-{next(_counter)}>"
    namespace: dict[str, object] = {}
    exec(compile(source, filename, "exec"), namespace)  # noqa: S102 -- generated by this test, not by input
    if register:
        # None in the mtime slot is load-bearing: inspect.findsource runs linecache.checkcache, which evicts every
        # entry whose file fails to stat unless its mtime is None.
        linecache.cache[filename] = (len(source), None, source.splitlines(keepends=True), filename)
    fn = namespace["_generated"]
    assert isinstance(fn, types.FunctionType)
    return fn


class _Accumulator:
    def __init__(self, body: str, gain: float, *, register: bool = True) -> None:
        self.total = 0.0
        self.gain = gain
        self._kernel: Callable[[float, float], float] = _generate(body, register=register)

    def step(self, x: float, y: float) -> float:
        scaled = self._kernel(x, y) * self.gain
        self.total = self.total + scaled
        return self.total - scaled  # distinct from the state, so the return port survives the elision rule


_ROWS = ((0.5, 1.0), (1.5, 1.0), (-2.0, 0.25), (0.0, -3.0))


def test_generated_function_as_the_root() -> None:
    fn = _generate("(x + y) * 0.5 - x * x * 0.125")
    sim = holoso.synthesize(fn, _OPTIONS, name="gen_root").numerical_model.elaborate()
    for x, y in _ROWS:
        assert float(sim.run(x, y)[0]) == fn(x, y), f"x={x} y={y}"


def test_generated_kernel_inlines_through_an_instance_attribute() -> None:
    """The generated callee folds out of the attribute snapshot while `total` remains a state register."""
    body = "(x + y) * 0.5 - x * x * 0.125"
    result = holoso.synthesize(_Accumulator(body, 2.0).step, _OPTIONS, name="gen_acc")
    assert [port.name for port in result.output_ports] == ["out_0", "state_total"]
    sim = result.numerical_model.elaborate()
    reference = _Accumulator(body, 2.0)
    for x, y in _ROWS:
        returned, state = (float(v) for v in sim.run(x, y))
        assert returned == reference.step(x, y), f"x={x} y={y}"
        assert state == reference.total, f"x={x} y={y}"


def test_generated_units_are_kept_apart() -> None:
    """Each generated function compiles from its own text; a shared spelling of the callee cannot cross them."""
    lo, hi = _Accumulator("x + y + 100.0", 1.0), _Accumulator("x + y + 200.0", 1.0)
    sim_lo = holoso.synthesize(lo.step, _OPTIONS, name="gen_lo").numerical_model.elaborate()
    sim_hi = holoso.synthesize(hi.step, _OPTIONS, name="gen_hi").numerical_model.elaborate()
    for x, y in _ROWS:
        lo.step(x, y)
        hi.step(x, y)
        assert float(sim_lo.run(x, y)[1]) == lo.total, f"x={x} y={y}"
        assert float(sim_hi.run(x, y)[1]) == hi.total, f"x={x} y={y}"


def test_unregistered_generated_source_is_refused_with_the_retrieval_contract() -> None:
    with pytest.raises(SourceUnavailable, match="registered in linecache"):
        holoso.synthesize(_Accumulator("x + y", 1.0, register=False).step, _OPTIONS, name="gen_unregistered")
