"""
Pure-Python verification support for a generated module: a self-contained cocotb testbench artifact, plus the float64
reference, the tolerance model, and the input sampling used to build its embedded vectors.
"""

import json
from collections.abc import Callable, Mapping, Sequence
from typing import Any

import numpy as np

from ._format import FloatFormat
from ._frontend import flatten_value
from ._lir import Lir
from ._schedule import cycle_count


def unit_roundoff(fmt: FloatFormat) -> float:
    """The format's unit roundoff, ``2**-(wman-1)`` (relative spacing of representable values)."""
    return 2.0 ** -(fmt.wman - 1)


def default_tolerance(
    fmt: FloatFormat, op_count: int, magnitude: float = 1.0, rel_factor: float = 16.0
) -> tuple[float, float]:
    """A defensible (rtol, atol) for a kernel of ``op_count`` operations evaluated over operands up to ``magnitude``."""
    u = unit_roundoff(fmt)
    rtol = rel_factor * max(op_count, 1) * u
    atol = rtol * abs(magnitude)
    return rtol, atol


def evaluate_reference(fn: Callable[..., object], inputs: Mapping[str, float]) -> list[float]:
    """Call ``fn`` in float64 with the named inputs and flatten the result into ordered output values."""
    result = fn(**inputs)
    return [float(value) for _, value in flatten_value(result)]


Sampler = Callable[[FloatFormat, Sequence[str], np.random.Generator], dict[str, float]]


def generic_sampler(fmt: FloatFormat, names: Sequence[str], rng: np.random.Generator) -> dict[str, float]:
    """A simple well-bounded sampler: each input uniform in [-4, 4]."""
    return {name: float(rng.uniform(-4.0, 4.0)) for name in names}


def build_vectors(
    fn: Callable[..., object],
    fmt: FloatFormat,
    input_names: Sequence[str],
    output_names: Sequence[str],
    op_count: int,
    *,
    count: int,
    rng: np.random.Generator,
    timeout_cycles: int,
    cycles: int,
    sampler: Sampler = generic_sampler,
) -> dict[str, Any]:
    """
    Produce ``count`` ``(input-bits, expected-floats, tolerance)`` records for the cosim driver.

    ``cycles`` is the model's exact in_valid->out_valid latency; the driver asserts the DUT matches it on every vector.
    """
    vectors: list[dict[str, Any]] = []
    for _ in range(count):
        values = sampler(fmt, input_names, rng)
        bits = {name: fmt.encode(value) for name, value in values.items()}
        decoded = {name: fmt.decode(pattern) for name, pattern in bits.items()}  # the values the DUT actually sees
        expected = evaluate_reference(fn, decoded)
        magnitude = max((abs(v) for v in decoded.values()), default=1.0)
        rtol, atol = default_tolerance(fmt, op_count, magnitude=magnitude)
        vectors.append({"in": bits, "exp": dict(zip(output_names, expected)), "rtol": rtol, "atol": atol})
    return {
        "wexp": fmt.wexp,
        "wman": fmt.wman,
        "inputs": list(input_names),
        "outputs": list(output_names),
        "timeout_cycles": timeout_cycles,
        "cycles": cycles,
        "vectors": vectors,
    }


_TEMPLATE = '''\
"""Auto-generated by Holoso: self-contained cocotb testbench for module @@MODULE@@."""

import json
import math

import cocotb
from cocotb.clock import Clock
from cocotb.triggers import FallingEdge, RisingEdge, Timer

_SPEC = json.loads(r"""@@SPEC@@""")


def _decode(wexp, wman, bits):
    wfrac = wman - 1
    width = wexp + wman
    exp_inf = (1 << wexp) - 1
    sign = (bits >> (width - 1)) & 1
    exp = (bits >> wfrac) & exp_inf
    frac = bits & ((1 << wfrac) - 1)
    if exp == 0:
        return 0.0
    if exp == exp_inf:
        return float("-inf") if sign else float("inf")
    value = math.ldexp((1 << wfrac) | frac, exp - ((1 << (wexp - 1)) - 1) - wfrac)
    return -value if sign else value


def _within(actual, expected, rtol, atol):
    if math.isinf(expected) or math.isinf(actual) or math.isnan(expected) or math.isnan(actual):
        return actual == expected
    return abs(actual - expected) <= atol + rtol * abs(expected)


@cocotb.test()
async def cosim(dut):
    wexp, wman = _SPEC["wexp"], _SPEC["wman"]
    timeout = int(_SPEC["timeout_cycles"])
    expected_cycles = int(_SPEC["cycles"])
    cocotb.start_soon(Clock(dut.clk, 10, unit="ns").start())
    await FallingEdge(dut.clk)
    dut.rst.value = 1
    dut.in_valid.value = 0
    for _ in range(4):
        await RisingEdge(dut.clk)
    dut.rst.value = 0
    await FallingEdge(dut.clk)
    dut.out_ready.value = 1

    for index, vec in enumerate(_SPEC["vectors"]):
        while int(dut.in_ready.value) != 1:
            await RisingEdge(dut.clk)
            await Timer(1, unit="ns")
        for name, bits in vec["in"].items():
            getattr(dut, "in_" + name).value = int(bits)
        dut.in_valid.value = 1
        await RisingEdge(dut.clk)
        await Timer(1, unit="ns")
        dut.in_valid.value = 0
        elapsed = 1
        while int(dut.out_valid.value) != 1:
            await RisingEdge(dut.clk)
            await Timer(1, unit="ns")
            elapsed += 1
            assert elapsed <= timeout, "timeout on vector %d" % index
        assert elapsed == expected_cycles, "vector %d cycle count: got %d expected %d" % (
            index,
            elapsed,
            expected_cycles,
        )
        for name, expected in vec["exp"].items():
            got = _decode(wexp, wman, int(getattr(dut, name).value))
            assert _within(got, expected, vec["rtol"], vec["atol"]), (
                "vector %d port %s: got %r expected %r" % (index, name, got, expected)
            )
        await RisingEdge(dut.clk)
        await Timer(1, unit="ns")
'''


def render_testbench(
    lir: Lir, fmt: FloatFormat, fn: Callable[..., object], *, count: int = 16, seed: int = 0xC0FFEE
) -> str:
    """Build embedded vectors with the generic sampler and splice them into the testbench template."""
    timeout = 4 * (lir.makespan + len(lir.inputs) + 8) + 64
    spec = build_vectors(
        fn,
        fmt,
        [load.name for load in lir.inputs],
        [wire.name for wire in lir.outputs],
        lir.op_count,
        count=count,
        rng=np.random.default_rng(seed),
        timeout_cycles=timeout,
        cycles=cycle_count(lir),
        sampler=generic_sampler,
    )
    return _TEMPLATE.replace("@@MODULE@@", lir.module_name).replace("@@SPEC@@", json.dumps(spec))
