"""
The cocotb backend: a self-contained, self-checking testbench for a generated module.

``generate`` embeds the module's :class:`NumericalModel` into a standalone cocotb test.
The testbench asserts the DUT's output bits match the model's exactly -- the model is bit-exact to the RTL,
so the check needs no tolerance. The model and the DUT are reset and stepped in lock-step.

The input sequence is either an explicit list of vectors supplied by the caller (replayed verbatim) or, when none is
given, a default random sweep drawn from a fixed seed. The seed also drives the back-pressure stalls, so every generated
bench is fully reproducible.
"""

import base64
import pickle
import zlib
from collections.abc import Mapping
from dataclasses import dataclass

from .numerical import NumericalModel

# language=python
_TEMPLATE = '''\
"""
Auto-generated by Holoso: bit-exact cocotb testbench for module @@MODULE@@.
"""

import base64
import pickle
import random
import zlib

import cocotb
from cocotb.clock import Clock
from cocotb.triggers import FallingEdge, RisingEdge, Timer

# TODO: make it self-contained by removing the holoso dependency: https://github.com/Zubax/holoso/issues/12
# Currently it is needed for unpickling.
import holoso

_MODEL = pickle.loads(zlib.decompress(base64.b64decode("@@BLOB@@")))  # TODO https://github.com/Zubax/holoso/issues/12
_FMT = _MODEL.float_format

# An explicit input sequence -- rows of per-input ZKF bits ordered as _MODEL.input_names -- or None to draw the default
# random sweep below. The fixed seed makes the default sweep and the back-pressure stalls reproducible.
_VECTORS = @@VECTORS@@
_SEED = 0x9E3779B97F4A7C15  # TODO: allow overriding the seed, count, and range via plusargs.
_DEFAULT_COUNT = 64
_DEFAULT_RANGE = (-4.0, +4.0)  # small bounded range keeps multi-operation kernels from overflowing into infinities
_MAX_TRANSACTION_CYCLES = 1 << 20  # out_valid ceiling: well above any real transaction, tripped only by a runaway loop


def _output_bits(value):
    return int(value) if isinstance(value, bool) else value.bits


@cocotb.test()
async def cosim(dut):
    rng = random.Random(_SEED)
    in_names = _MODEL.input_names
    out_names = _MODEL.output_names
    if _VECTORS is not None:
        sequence = _VECTORS
    else:
        lo, hi = _DEFAULT_RANGE
        sequence = [[_FMT.encode(rng.uniform(lo, hi)) for _ in in_names] for _ in range(_DEFAULT_COUNT)]

    cocotb.start_soon(Clock(dut.clk, 10, unit="ns").start())
    await FallingEdge(dut.clk)
    dut.rst.value = 1
    dut.in_valid.value = 0
    for _ in range(4):
        await RisingEdge(dut.clk)
    dut.rst.value = 0
    await FallingEdge(dut.clk)
    dut.out_ready.value = 0
    _MODEL.reset()  # match the DUT's just-applied reset; persistent state then advances in lock-step with the DUT

    for index, in_bits in enumerate(sequence):
        # The model is fed exactly the bits the DUT receives, so the comparison is bit-exact. For a stateful module
        # this is one step of a sequence: the model and DUT carry their state forward together across iterations.
        expected = _MODEL(*[holoso.FloatValue.from_bits(_FMT, bits) for bits in in_bits])
        exp_bits = [_output_bits(value) for value in expected]

        while int(dut.in_ready.value) != 1:
            await RisingEdge(dut.clk)
            await Timer(1, unit="ns")
        for name, bits in zip(in_names, in_bits):
            getattr(dut, "in_" + name).value = int(bits)
        dut.in_valid.value = 1
        await RisingEdge(dut.clk)
        await Timer(1, unit="ns")
        dut.in_valid.value = 0

        # TODO: verify exact latency after branch support makes the model predict per-transaction latency. A ceiling
        # guards against a runaway data-dependent loop (the model already bounds its own iteration count): a divergence
        # between the converged model and a non-terminating DUT surfaces as a clear failure rather than a hung sim.
        waited = 0
        while int(dut.out_valid.value) != 1:
            await RisingEdge(dut.clk)
            await Timer(1, unit="ns")
            waited += 1
            assert waited < _MAX_TRANSACTION_CYCLES, "vector %d: out_valid not asserted within %d cycles" % (
                index,
                _MAX_TRANSACTION_CYCLES,
            )
        assert int(dut.err_pc.value) == 0, "vector %d: unexpected error at cycle %d" % (index, int(dut.err_pc.value))

        # Random back-pressure: hold out_ready low for a stall. out_valid and the outputs must stay stable, and the
        # persistent state must not advance until the transaction is actually accepted (out_valid && out_ready).
        for _ in range(rng.randint(0, 3)):
            assert int(dut.out_valid.value) == 1, "vector %d: out_valid dropped under back-pressure" % index
            for name, want in zip(out_names, exp_bits):
                got = int(getattr(dut, name).value)
                assert got == want, "vector %d port %s changed under back-pressure" % (index, name)
            await RisingEdge(dut.clk)
            await Timer(1, unit="ns")

        dut.out_ready.value = 1  # accept on the next edge
        await Timer(1, unit="ns")
        for name, want in zip(out_names, exp_bits):
            got = int(getattr(dut, name).value)
            assert got == want, "vector %d port %s: got 0x%x expected 0x%x" % (index, name, got, want)
        await RisingEdge(dut.clk)
        await Timer(1, unit="ns")
        dut.out_ready.value = 0
'''


@dataclass(frozen=True, slots=True)
class CocotbOutput:
    """The cocotb backend's output: one self-contained, self-checking cocotb testbench module."""

    testbench: str

    def __str__(self) -> str:
        return f"{type(self).__name__}(testbench_bytes={len(self.testbench.encode())})"


def _embed_vectors(model: NumericalModel, vectors: list[Mapping[str, int]] | None) -> str:
    """Render the explicit input sequence as a Python literal of input-name-ordered ZKF-bit rows, or ``None``."""
    if vectors is None:
        return "None"
    order = model.input_names
    rows: list[list[int]] = []
    for index, vector in enumerate(vectors):
        if missing := [name for name in order if name not in vector]:
            raise ValueError(f"cosim vector {index} is missing inputs {missing}")
        rows.append([int(vector[name]) for name in order])
    return repr(rows)


def generate(model: NumericalModel, vectors: list[Mapping[str, int]] | None = None) -> CocotbOutput:
    """
    Build a self-contained cocotb testbench that checks the DUT against the embedded bit-exact model.

    When ``vectors`` is given, each maps an input-port name to its ZKF bits and the bench replays the sequence verbatim
    (one accepted transaction per vector, state carried across for stateful modules). When it is ``None``, the bench
    draws a fixed-seed random sweep over a small bounded range instead. Either way the run is fully reproducible.
    """
    blob = base64.b64encode(zlib.compress(pickle.dumps(model, pickle.HIGHEST_PROTOCOL))).decode("ascii")
    testbench = (
        _TEMPLATE.replace("@@MODULE@@", model.lir.module_name)
        .replace("@@VECTORS@@", _embed_vectors(model, vectors))
        .replace("@@BLOB@@", blob)
    )
    return CocotbOutput(testbench=testbench)
