"""
The cocotb backend: a self-contained, self-checking testbench for a generated module.

``generate`` embeds the module's :class:`NumericalModel` (as a compressed, base64-encoded pickle) into a standalone
cocotb test. At simulation time the testbench draws random input vectors, runs the embedded model to get the expected
outputs, drives the DUT, and asserts the DUT's output bits match the model's exactly -- the model is bit-exact to the
RTL, so the check needs no tolerance. The testbench imports ``holoso`` only to unpickle the model.
"""

import base64
import json
import pickle
import zlib
from dataclasses import dataclass

from .._interface import ModuleInterface
from .numerical import NumericalModel

_TEMPLATE = '''\
"""
Auto-generated by Holoso: bit-exact cocotb testbench for module @@MODULE@@.
"""

import base64
import pickle
import random
import zlib

import cocotb
from cocotb.clock import Clock
from cocotb.triggers import FallingEdge, RisingEdge, Timer

# TODO: make it self-contained by removing the holoso dependency: https://github.com/Zubax/holoso/issues/12
# Currently it is needed for unpickling.
import holoso

_CFG = @@CFG@@
_MODEL = pickle.loads(zlib.decompress(base64.b64decode("@@BLOB@@")))  # TODO https://github.com/Zubax/holoso/issues/12
_FMT = _MODEL.float_format


@cocotb.test()
async def cosim(dut):
    rng = random.Random(_CFG["seed"])
    value_range = _CFG["range"]
    timeout = int(_CFG["timeout_cycles"])
    expected_cycles = int(_CFG["cycles"])
    in_names = _MODEL.input_names
    out_names = _MODEL.output_names

    cocotb.start_soon(Clock(dut.clk, 10, unit="ns").start())
    await FallingEdge(dut.clk)
    dut.rst.value = 1
    dut.in_valid.value = 0
    for _ in range(4):
        await RisingEdge(dut.clk)
    dut.rst.value = 0
    await FallingEdge(dut.clk)
    dut.out_ready.value = 1

    for index in range(int(_CFG["count"])):
        # The model is fed exactly the bits the DUT receives, so the comparison is bit-exact.
        in_bits = [_FMT.encode(rng.uniform(-value_range, value_range)) for _ in in_names]
        expected = _MODEL(*[_FMT.decode(bits) for bits in in_bits])
        exp_bits = [_FMT.encode(value) for value in expected]

        while int(dut.in_ready.value) != 1:
            await RisingEdge(dut.clk)
            await Timer(1, unit="ns")
        for name, bits in zip(in_names, in_bits):
            getattr(dut, "in_" + name).value = int(bits)
        dut.in_valid.value = 1
        await RisingEdge(dut.clk)
        await Timer(1, unit="ns")
        dut.in_valid.value = 0

        elapsed = 1
        while int(dut.out_valid.value) != 1:
            await RisingEdge(dut.clk)
            await Timer(1, unit="ns")
            elapsed += 1
            assert elapsed <= timeout, "vector %d: timed out after %d cycles waiting for out_valid" % (index, elapsed)
        assert elapsed == expected_cycles, "vector %d: cycle count %d, expected %d" % (index, elapsed, expected_cycles)
        assert int(dut.err_cyc.value) == 0, "vector %d: unexpected error at cycle %d" % (index, int(dut.err_cyc.value))

        for name, want in zip(out_names, exp_bits):
            got = int(getattr(dut, name).value)
            assert got == want, "vector %d port %s: got 0x%x expected 0x%x" % (index, name, got, want)
        await RisingEdge(dut.clk)
        await Timer(1, unit="ns")
'''


@dataclass(frozen=True, slots=True)
class CocotbOutput:
    """The cocotb backend's output: one self-contained, self-checking cocotb testbench module."""

    testbench: str


def generate(
    model: NumericalModel,
    interface: ModuleInterface,
    *,
    count: int = 64,
    seed: int = 0xC0FFEE,
    value_range: float = 4.0,
) -> CocotbOutput:
    """
    Build a self-contained cocotb testbench that checks the DUT against the embedded bit-exact model.

    ``count`` random vectors are drawn at simulation time (seeded by ``seed``); each input is a ZKF value uniform in
    ``[-value_range, value_range]``, bounded to keep multi-operation kernels from overflowing into infinities.
    """
    cfg = {
        "cycles": interface.ii.cycles,
        "timeout_cycles": max(64, interface.ii.cycles * 4),
        "count": count,
        "seed": seed,
        "range": value_range,
    }
    blob = base64.b64encode(zlib.compress(pickle.dumps(model, pickle.HIGHEST_PROTOCOL))).decode("ascii")
    testbench = (
        _TEMPLATE.replace("@@MODULE@@", interface.module_name)
        .replace("@@CFG@@", json.dumps(cfg, indent=4))
        .replace("@@BLOB@@", blob)
    )
    return CocotbOutput(testbench=testbench)
