"""
The cocotb backend: a self-contained, self-checking testbench for a generated module.

``generate`` embeds the module's :class:`NumericalModel` into a standalone cocotb test.
The testbench asserts the DUT's output bits match the model's exactly -- the model is bit-exact to the RTL,
so the check needs no tolerance. The model and the DUT are reset and stepped in lock-step.
"""

import base64
import pickle
import zlib
from dataclasses import dataclass

from .numerical import NumericalModel

# language=python
_TEMPLATE = '''\
"""
Auto-generated by Holoso: bit-exact cocotb testbench for module @@MODULE@@.
"""

import base64
import pickle
import random
import zlib

import cocotb
from cocotb.clock import Clock
from cocotb.triggers import FallingEdge, RisingEdge, Timer

# TODO: make it self-contained by removing the holoso dependency: https://github.com/Zubax/holoso/issues/12
# Currently it is needed for unpickling.
import holoso

_MODEL = pickle.loads(zlib.decompress(base64.b64decode("@@BLOB@@")))  # TODO https://github.com/Zubax/holoso/issues/12
_FMT = _MODEL.float_format


@cocotb.test()
async def cosim(dut):
    rng = random.Random()  # TODO seed via plusargs
    in_names = _MODEL.input_names
    out_names = _MODEL.output_names

    cocotb.start_soon(Clock(dut.clk, 10, unit="ns").start())
    await FallingEdge(dut.clk)
    dut.rst.value = 1
    dut.in_valid.value = 0
    for _ in range(4):
        await RisingEdge(dut.clk)
    dut.rst.value = 0
    await FallingEdge(dut.clk)
    dut.out_ready.value = 0
    _MODEL.reset()  # match the DUT's just-applied reset; persistent state then advances in lock-step with the DUT

    for index in range(64):  # TODO configurable test count via plusargs
        # The model is fed exactly the bits the DUT receives, so the comparison is bit-exact. For a stateful module
        # this is one step of a sequence: the model and DUT carry their state forward together across iterations.
        # TODO: value range must be configurable via plusargs
        in_bits = [_FMT.encode(rng.uniform(-4, +4)) for _ in in_names]
        expected = _MODEL(*[holoso.FloatValue.from_bits(_FMT, bits) for bits in in_bits])
        exp_bits = [value.bits for value in expected]

        while int(dut.in_ready.value) != 1:
            await RisingEdge(dut.clk)
            await Timer(1, unit="ns")
        for name, bits in zip(in_names, in_bits):
            getattr(dut, "in_" + name).value = int(bits)
        dut.in_valid.value = 1
        await RisingEdge(dut.clk)
        await Timer(1, unit="ns")
        dut.in_valid.value = 0

        # TODO: verify exact latency after branch support makes the model predict per-transaction latency.
        while int(dut.out_valid.value) != 1:
            await RisingEdge(dut.clk)
            await Timer(1, unit="ns")
        assert int(dut.err_pc.value) == 0, "vector %d: unexpected error at cycle %d" % (index, int(dut.err_pc.value))

        # Random back-pressure: hold out_ready low for a stall. out_valid and the outputs must stay stable, and the
        # persistent state must not advance until the transaction is actually accepted (out_valid && out_ready).
        for _ in range(rng.randint(0, 3)):
            assert int(dut.out_valid.value) == 1, "vector %d: out_valid dropped under back-pressure" % index
            for name, want in zip(out_names, exp_bits):
                got = int(getattr(dut, name).value)
                assert got == want, "vector %d port %s changed under back-pressure" % (index, name)
            await RisingEdge(dut.clk)
            await Timer(1, unit="ns")

        dut.out_ready.value = 1  # accept on the next edge
        await Timer(1, unit="ns")
        for name, want in zip(out_names, exp_bits):
            got = int(getattr(dut, name).value)
            assert got == want, "vector %d port %s: got 0x%x expected 0x%x" % (index, name, got, want)
        await RisingEdge(dut.clk)
        await Timer(1, unit="ns")
        dut.out_ready.value = 0
'''


@dataclass(frozen=True, slots=True)
class CocotbOutput:
    """The cocotb backend's output: one self-contained, self-checking cocotb testbench module."""

    testbench: str

    def __str__(self) -> str:
        return f"{type(self).__name__}(testbench_bytes={len(self.testbench.encode())})"


def generate(model: NumericalModel) -> CocotbOutput:
    """
    Build a self-contained cocotb testbench that checks the DUT against the embedded bit-exact model.

    A fixed set of random vectors is drawn at simulation time. Each input is a ZKF value uniform in a small bounded
    range to keep multi-operation kernels from overflowing into infinities.
    """
    blob = base64.b64encode(zlib.compress(pickle.dumps(model, pickle.HIGHEST_PROTOCOL))).decode("ascii")
    testbench = _TEMPLATE.replace("@@MODULE@@", model.lir.module_name).replace("@@BLOB@@", blob)
    return CocotbOutput(testbench=testbench)
