"""Thin API for the low-level IR consumer contract."""

from ._build import build as build
from ._ir import Lir as Lir
from ._ir import (
    BoolConstRef as BoolConstRef,
    BoolInputLoad as BoolInputLoad,
    BoolOperand as BoolOperand,
    BoolOutputWire as BoolOutputWire,
    BoolRegRef as BoolRegRef,
    BoolSource as BoolSource,
    BoolWrite as BoolWrite,
    Branch as Branch,
    FloatConstRef as FloatConstRef,
    FloatCopy as FloatCopy,
    FloatInputLoad as FloatInputLoad,
    FloatOperand as FloatOperand,
    FloatOutputWire as FloatOutputWire,
    FloatStateSlot as FloatStateSlot,
    InlineScheduledOp as InlineScheduledOp,
    PooledScheduledOp as PooledScheduledOp,
    PortWrite as PortWrite,
    RegRef as RegRef,
    ScheduledOp as ScheduledOp,
    FETCH_LAG as FETCH_LAG,
    FETCH_STAGES as FETCH_STAGES,
    boundary_step as boundary_step,
    copy_step_cycle as copy_step_cycle,
    inline_fire_cycle as inline_fire_cycle,
    operand_read_cycle as operand_read_cycle,
    pooled_writeback_word as pooled_writeback_word,
    result_landing_cycle as result_landing_cycle,
    scalar_type_of as scalar_type_of,
    InlineProducer as InlineProducer,
    InputProducer as InputProducer,
    Jump as Jump,
    LirBlock as LirBlock,
    OperationProducer as OperationProducer,
    OperatorInstance as OperatorInstance,
    Producer as Producer,
    RegFileLayout as RegFileLayout,
    Ret as Ret,
    StateProducer as StateProducer,
)
from ._ports import (
    ControlInputPort as ControlInputPort,
    ControlOutputPort as ControlOutputPort,
    ControlPort as ControlPort,
    DataInputPort as DataInputPort,
    DataOutputPort as DataOutputPort,
    DataPort as DataPort,
    Direction as Direction,
    Port as Port,
)
from ._analysis import latest_producer_before as latest_producer_before
