// This is a collection of modules that may be used by HLS synthesized modules generated by Holoso.
// Where reasonable, Holoso may also inject ad-hoc combinational logic directly into the generated module.
// Some of the modules depend on the Kulibin library: https://github.com/Zubax/kulibin
//
// Modules use the in_valid/out_valid pattern to signal data availability.
// Those that have limited throughput provide in_ready/out_ready for stalling.
// The active-high synchronous reset only resets the control path, leaving data path undefined.
// Before the first out_valid is asserted, the values of the outputs are indeterminate (may be X).
//
// Modules named with an underscore are internal implementation details.

`timescale 1ns/1ps

// ====================================================================================================================
// REGISTER FILE

// Multiport combinational register file with flattened lane buses.
//
// The packed lane buses use zero-based port order.
// The helper macro in holoso_support.vh is intended to be used inside indexed part-selects, for example:
//
//     rd_addr[`HOLOSO_REGFILE_LANE(WADDR, 0)]
//     rd_data[`HOLOSO_REGFILE_LANE(W,    0)]
//     wr_addr[`HOLOSO_REGFILE_LANE(WADDR, 1)]
//     wr_data[`HOLOSO_REGFILE_LANE(W,    1)]
//     wr_en[1]
//
// Reads are combinational. With RWPASS=0, each read port returns the selected stored register only.
// With RWPASS!=0, if an active write targets the selected read address, the read port returns the matching
// write-data lanes before the clock edge; this intentional write-to-read combinational path implements write-through
// same-cycle behavior. Enabling RWPASS adds one W-bit wide binary mux on the read path.
//
// Writes are synchronous. On the rising edge of clk, each addressed register with an active matching write
// port is updated to the matching write-data lanes.
//
// There is no reset input and stored data is not initialized. Accesses are unchecked; the client must only use
// addresses below NREG. Out-of-range behavior is unspecified. Conflicting write behavior is unspecified.
module holoso_regfile#(
    parameter W      = 32,           // width of one data word
    parameter WADDR  = 5,            // width of one address lane
    parameter NRD    = 1,            // number of combinational read ports
    parameter NWR    = 1,            // number of synchronous write ports
    parameter NREG   = (1 << WADDR), // number of stored registers; defaults to the full addressable range
    parameter RWPASS = 0             // enables same-cycle read/write combinational pass-through
)(
    input wire clk,

    input wire       [NWR-1:0] wr_en,
    input wire [NWR*WADDR-1:0] wr_addr,
    input wire     [NWR*W-1:0] wr_data,

    input  wire [NRD*WADDR-1:0] rd_addr,
    output wire     [NRD*W-1:0] rd_data
);
    reg [W-1:0] regs [0:NREG-1];

    function [W-1:0] _or_write_words;
        input [NWR*W-1:0] words;
        integer i;
        begin
            _or_write_words = {W{1'b0}};
            for (i = 0; i < NWR; i = i + 1) begin
                _or_write_words = _or_write_words | words[(i * W) +: W];
            end
        end
    endfunction

    genvar reg_idx;
    genvar rd_idx;
    genvar wr_idx;
    generate
        if ((W <= 0) || (WADDR <= 0) || (NRD <= 0) || (NWR <= 0) || (NREG <= 0) || (NREG > (1 << WADDR))) begin : g_bad
            _holoso_regfile_bad_parameters_invalid_usage bad_parameters();
        end else begin : g_ok
            // WRITE PORTS
            for (reg_idx = 0; reg_idx < NREG; reg_idx = reg_idx + 1) begin : g_reg
                localparam [WADDR-1:0] REG_ADDR = reg_idx;

                wire   [NWR-1:0] wr_match;
                wire [NWR*W-1:0] wr_data_masked;
                wire     [W-1:0] wr_data_or = _or_write_words(wr_data_masked);

                for (wr_idx = 0; wr_idx < NWR; wr_idx = wr_idx + 1) begin : g_wr
                    wire match = wr_en[wr_idx] && (wr_addr[(wr_idx * WADDR) +: WADDR] == REG_ADDR);
                    assign wr_match[wr_idx] = match;
                    assign wr_data_masked[(wr_idx * W) +: W] = match ? wr_data[(wr_idx * W) +: W] : {W{1'b0}};
                end

                always @(posedge clk) begin
                    if (|wr_match) begin
                        regs[reg_idx] <= wr_data_or;
                    end
                end
            end
            // READ PORTS
            for (rd_idx = 0; rd_idx < NRD; rd_idx = rd_idx + 1) begin : g_rd
                wire  [WADDR-1:0] rd_addr_lane = rd_addr[(rd_idx * WADDR) +: WADDR];
                if (RWPASS) begin : g_passthrough
                    wire   [NWR-1:0] rd_wr_match;
                    wire [NWR*W-1:0] rd_wr_data_masked;
                    wire     [W-1:0] rd_wr_data_or = _or_write_words(rd_wr_data_masked);

                    for (wr_idx = 0; wr_idx < NWR; wr_idx = wr_idx + 1) begin : g_wr
                        wire match = wr_en[wr_idx] && (wr_addr[(wr_idx * WADDR) +: WADDR] == rd_addr_lane);
                        assign rd_wr_match[wr_idx] = match;
                        assign rd_wr_data_masked[(wr_idx * W) +: W] = match ? wr_data[(wr_idx * W) +: W] : {W{1'b0}};
                    end
                    assign rd_data[(rd_idx * W) +: W] = (|rd_wr_match) ? rd_wr_data_or : regs[rd_addr_lane];
                end else begin : g_no_passthrough
                    assign rd_data[(rd_idx * W) +: W] = regs[rd_addr_lane];
                end
            end
        end
    endgenerate
endmodule

// ====================================================================================================================
// FLOATING POINT BASIC OPERATORS
//
// Using Zubax Kulibin float -- an IEEE 754-like format with simplifications: no NaN, no subnormals, no negative 0.
// Refer to the Kulibin library for details.
//
// Parameters: WEXP -- exponent bit width, WMAN -- mantissa/significand bit width (incl. hidden bit).
// The total width is WFULL=WEXP+WMAN (the significand MSb is absent but there is also the sign bit, like IEEE 754).
//
// Additional register stages can be introduced to tweak critical path timings vs. pipeline latency using
// dedicated parameters; refer to the Kulibin source for their specific meaning.

// Combinational floating-point sign conditioner operator; to be used at the inputs/outputs of arithmetic operators.
// Sign conditioning is a trivial and/xor single-bit gate enabling free computation of abs/neg.
// Conditional inputs can be tied off to constants, in which case the corresponding circuits are optimized away.
// Function:
//      y =     +x      if op=0
//      y =     -x      if op=1
//      y = +abs(x)     if op=2
//      y = -abs(x)     if op=3
module holoso_fsgnop#(parameter WFULL = 24) (input wire [WFULL-1:0] x, input wire [1:0] op, output wire [WFULL-1:0] y);
    wire   op_abs = op[1];
    wire   op_neg = op[0];
    wire   s_in   = x[WFULL-1];
    wire   s_out  = (s_in & ~op_abs) ^ op_neg;
    assign y      = { s_out, x[WFULL-2:0] };
endmodule

// Floating point adder/subtractor with sign conditioning:  y = sgnop(sgnop(a) + sgnop(b))
// E.g., subtraction: y=a+(-b); negative absolute difference: y=-abs(a-b), magnitude difference: y=abs(a)-abs(b), ...
module holoso_fadd#(parameter WEXP = 6, parameter WMAN = 18, parameter STAGE_DECODE = 0, parameter STAGE_ALIGN = 0) (
    input  wire clk,
    input  wire rst,
    input  wire                 in_valid,
    input  wire           [1:0] a_sgnop,
    input  wire           [1:0] b_sgnop,
    input  wire           [1:0] y_sgnop,
    input  wire [WEXP+WMAN-1:0] a,
    input  wire [WEXP+WMAN-1:0] b,
    output wire                 out_valid,
    output wire [WEXP+WMAN-1:0] y
);
    localparam WFULL = WEXP + WMAN;
    wire [WFULL-1:0] a1;
    wire [WFULL-1:0] b1;
    wire [WFULL-1:0] y1;
    holoso_fsgnop#(.WFULL(WFULL)) u_sgnop_a (.x(a), .op(a_sgnop), .y(a1));
    holoso_fsgnop#(.WFULL(WFULL)) u_sgnop_b (.x(b), .op(b_sgnop), .y(b1));
    holoso_fsgnop#(.WFULL(WFULL)) u_sgnop_y (.x(y1), .op(y_sgnop), .y(y));
    zkf_add#(.WEXP(WEXP), .WMAN(WMAN), .STAGE_DECODE(STAGE_DECODE), .STAGE_ALIGN(STAGE_ALIGN)) u_add (
        .clk(clk), .rst(rst),
        .in_valid(in_valid), .a(a1), .b(b1),
        .out_valid(out_valid), .y(y1)
    );
endmodule

// Floating point multiplier with sign conditioning: y = sgnop(sgnop(a) * sgnop(b))
module holoso_fmul#(parameter WEXP = 6, parameter WMAN = 18, parameter STAGE_PRODUCT = 0) (
    input  wire clk,
    input  wire rst,
    input  wire                 in_valid,
    input  wire           [1:0] a_sgnop,
    input  wire           [1:0] b_sgnop,
    input  wire           [1:0] y_sgnop,
    input  wire [WEXP+WMAN-1:0] a,
    input  wire [WEXP+WMAN-1:0] b,
    output wire                 out_valid,
    output wire [WEXP+WMAN-1:0] y
);
    localparam WFULL = WEXP + WMAN;
    wire [WFULL-1:0] a1;
    wire [WFULL-1:0] b1;
    wire [WFULL-1:0] y1;
    holoso_fsgnop#(.WFULL(WFULL)) u_sgnop_a (.x(a),  .op(a_sgnop), .y(a1));
    holoso_fsgnop#(.WFULL(WFULL)) u_sgnop_b (.x(b),  .op(b_sgnop), .y(b1));
    holoso_fsgnop#(.WFULL(WFULL)) u_sgnop_y (.x(y1), .op(y_sgnop), .y(y));
    zkf_mul#(.WEXP(WEXP), .WMAN(WMAN), .STAGE_PRODUCT(STAGE_PRODUCT)) u_mul (.clk(clk), .rst(rst),
                                                                             .in_valid(in_valid), .a(a1), .b(b1),
                                                                             .out_valid(out_valid), .y(y1));
endmodule

// Constant-power-of-two scaler with sign conditioning:  y = sgnop(sgnop(a) * 2^K)
// K is a signed integer exponent shift; -2^(WEXP-1) < K < 2^(WEXP-1). The scaling is exact.
module holoso_fmul_ilog2_const#(parameter WEXP = 6, parameter WMAN = 18,
                                parameter integer K = 0, parameter STAGE_DECODE = 0) (
    input  wire clk,
    input  wire rst,
    input  wire                 in_valid,
    input  wire           [1:0] a_sgnop,
    input  wire           [1:0] y_sgnop,
    input  wire [WEXP+WMAN-1:0] a,
    output wire                 out_valid,
    output wire [WEXP+WMAN-1:0] y
);
    localparam WFULL = WEXP + WMAN;
    wire [WFULL-1:0] a1;
    wire [WFULL-1:0] y1;
    holoso_fsgnop#(.WFULL(WFULL)) u_sgnop_a (.x(a),  .op(a_sgnop), .y(a1));
    holoso_fsgnop#(.WFULL(WFULL)) u_sgnop_y (.x(y1), .op(y_sgnop), .y(y));
    zkf_mul_ilog2_const#(.WEXP(WEXP), .WMAN(WMAN), .K(K), .STAGE_DECODE(STAGE_DECODE)) u_mul_ilog2_const (
        .clk(clk), .rst(rst),
        .in_valid(in_valid), .a(a1),
        .out_valid(out_valid), .y(y1)
    );
endmodule

// Floating point divider with sign conditioning: y = sgnop(sgnop(a) / sgnop(b))
// div0 is asserted alongside out_valid when the divisor is (positive) zero; the value of y is then unspecified.
// The quotient is rounded.
module holoso_fdiv#(parameter WEXP = 6, parameter WMAN = 18, parameter STAGE_INPUT = 0) (
    input  wire clk,
    input  wire rst,
    input  wire                 in_valid,
    input  wire           [1:0] a_sgnop,
    input  wire           [1:0] b_sgnop,
    input  wire           [1:0] y_sgnop,
    input  wire [WEXP+WMAN-1:0] a,
    input  wire [WEXP+WMAN-1:0] b,
    output wire                 out_valid,
    output wire [WEXP+WMAN-1:0] y,
    output wire                 div0
);
    localparam WFULL = WEXP + WMAN;
    wire [WFULL-1:0] a1;
    wire [WFULL-1:0] b1;
    wire [WFULL-1:0] y1;
    holoso_fsgnop#(.WFULL(WFULL)) u_sgnop_a (.x(a),  .op(a_sgnop), .y(a1));
    holoso_fsgnop#(.WFULL(WFULL)) u_sgnop_b (.x(b),  .op(b_sgnop), .y(b1));
    holoso_fsgnop#(.WFULL(WFULL)) u_sgnop_y (.x(y1), .op(y_sgnop), .y(y));
    zkf_div#(.WEXP(WEXP), .WMAN(WMAN), .STAGE_INPUT(STAGE_INPUT)) u_div (.clk(clk), .rst(rst),
                                                                         .in_valid(in_valid), .a(a1), .b(b1),
                                                                         .out_valid(out_valid), .q(y1), .div0(div0));
endmodule

// Combinational saturator: replaces infinity with the largest finite value of the same sign; finite pass through.
module holoso_fsaturate#(parameter WEXP = 6, parameter WMAN = 18) (
    input  wire [WEXP+WMAN-1:0] x,
    output wire [WEXP+WMAN-1:0] y
);
    zkf_saturate#(.WEXP(WEXP), .WMAN(WMAN)) u_saturate (.x(x), .y(y));
endmodule

// Floating point min/max sorter with sign conditioning on inputs and outputs:
//      min = sgnop(min(sgnop(a), sgnop(b)))
//      max = sgnop(max(sgnop(a), sgnop(b)))
// Useful for e.g. sort-by-absolute-value or producing sign-flipped extrema.
module holoso_fsort#(parameter WEXP = 6, parameter WMAN = 18) (
    input  wire clk,
    input  wire rst,
    input  wire                 in_valid,
    input  wire           [1:0] a_sgnop,
    input  wire           [1:0] b_sgnop,
    input  wire           [1:0] min_sgnop,
    input  wire           [1:0] max_sgnop,
    input  wire [WEXP+WMAN-1:0] a,
    input  wire [WEXP+WMAN-1:0] b,
    output wire                 out_valid,
    output wire [WEXP+WMAN-1:0] min,
    output wire [WEXP+WMAN-1:0] max
);
    localparam WFULL = WEXP + WMAN;
    wire [WFULL-1:0] a1;
    wire [WFULL-1:0] b1;
    wire [WFULL-1:0] min1;
    wire [WFULL-1:0] max1;
    holoso_fsgnop#(.WFULL(WFULL)) u_sgnop_a   (.x(a),    .op(a_sgnop),   .y(a1));
    holoso_fsgnop#(.WFULL(WFULL)) u_sgnop_b   (.x(b),    .op(b_sgnop),   .y(b1));
    holoso_fsgnop#(.WFULL(WFULL)) u_sgnop_min (.x(min1), .op(min_sgnop), .y(min));
    holoso_fsgnop#(.WFULL(WFULL)) u_sgnop_max (.x(max1), .op(max_sgnop), .y(max));
    zkf_sort#(.WEXP(WEXP), .WMAN(WMAN)) u_sort (.clk(clk), .rst(rst),
                                                .in_valid(in_valid), .a(a1), .b(b1),
                                                .out_valid(out_valid), .min(min1), .max(max1));
endmodule

// Floating point comparator with sign conditioning on inputs only:
//      (a_gt_b, a_eq_b, a_lt_b) = compare(sgnop(a), sgnop(b))
// Outputs are mutually-exclusive one-hot flags.
module holoso_fcmp#(parameter WEXP = 6, parameter WMAN = 18) (
    input  wire clk,
    input  wire rst,
    input  wire                 in_valid,
    input  wire           [1:0] a_sgnop,
    input  wire           [1:0] b_sgnop,
    input  wire [WEXP+WMAN-1:0] a,
    input  wire [WEXP+WMAN-1:0] b,
    output wire                 out_valid,
    output wire                 a_gt_b,
    output wire                 a_eq_b,
    output wire                 a_lt_b
);
    localparam WFULL = WEXP + WMAN;
    wire [WFULL-1:0] a1;
    wire [WFULL-1:0] b1;
    holoso_fsgnop#(.WFULL(WFULL)) u_sgnop_a (.x(a), .op(a_sgnop), .y(a1));
    holoso_fsgnop#(.WFULL(WFULL)) u_sgnop_b (.x(b), .op(b_sgnop), .y(b1));
    zkf_cmp#(.WEXP(WEXP), .WMAN(WMAN)) u_cmp (.clk(clk), .rst(rst),
                                              .in_valid(in_valid), .a(a1), .b(b1),
                                              .out_valid(out_valid),
                                              .a_gt_b(a_gt_b), .a_eq_b(a_eq_b), .a_lt_b(a_lt_b));
endmodule

// Like holoso_fcmp but the second operand "b" is a constant. Signop only on a.
module holoso_fcmp_const#(parameter WEXP = 6, parameter WMAN = 18, parameter real B = 0.0) (
    input  wire clk,
    input  wire rst,
    input  wire                 in_valid,
    input  wire           [1:0] a_sgnop,
    input  wire [WEXP+WMAN-1:0] a,
    output wire                 out_valid,
    output wire                 a_gt_b,
    output wire                 a_eq_b,
    output wire                 a_lt_b
);
    localparam WFULL = WEXP + WMAN;
    wire [WFULL-1:0] b;
    wire [WFULL-1:0] a1;
    holoso_fconst#(.WEXP(WEXP), .WMAN(WMAN), .VALUE(B), .INF(0)) u_b (.y(b));
    holoso_fsgnop#(.WFULL(WFULL)) u_sgnop_a (.x(a), .op(a_sgnop), .y(a1));
    zkf_cmp#(.WEXP(WEXP), .WMAN(WMAN)) u_cmp (.clk(clk), .rst(rst),
                                              .in_valid(in_valid), .a(a1), .b(b),
                                              .out_valid(out_valid),
                                              .a_gt_b(a_gt_b), .a_eq_b(a_eq_b), .a_lt_b(a_lt_b));
endmodule

// Combinational predicate: y=1 iff x is finite (i.e., x is not an infinity).
module holoso_fisfinite#(parameter WEXP = 6, parameter WMAN = 18) (input  wire [WEXP+WMAN-1:0] x, output wire y);
    zkf_is_finite#(.WEXP(WEXP), .WMAN(WMAN)) u_is_finite (.x(x), .y(y));
endmodule

// Elaboration-time floating-point constant generator. If INF != 0, y is a signed infinity with the sign of INF and
// VALUE is ignored; otherwise y encodes the IEEE 754 binary64 real literal VALUE in Kulibin float format.
module holoso_fconst#(parameter WEXP = 6, parameter WMAN = 18, parameter real VALUE = 0.0, parameter integer INF = 0) (
    output wire [WEXP+WMAN-1:0] y
);
    zkf_const#(.WEXP(WEXP), .WMAN(WMAN), .VALUE(VALUE), .INF(INF)) u_const (.y(y));
endmodule

// Combinational mapping from float to boolean: a zero or a subnormal (if supported) float is false, otherwise true.
// E.g., if IEEE 754 binary32 is used (with subnormals), values with magnitude under ~1e-38 are mapped to falsity.
module holoso_ftobool#(parameter WEXP = 6, parameter WMAN = 18) (input wire [WEXP+WMAN-1:0] x, output wire y);
    assign y = |x[WEXP+WMAN-2:WMAN-1];  // zero if the exponent is zero; assume no subnormals or subnormals~0
endmodule

// Combinational mapping from boolean to float: falsity is zero, truth is one.
module holoso_ffrombool#(parameter WEXP = 6, parameter WMAN = 18) (input wire x, output wire [WEXP+WMAN-1:0] y);
    wire [WEXP+WMAN-1:0] one;
    holoso_fconst#(.WEXP(WEXP), .WMAN(WMAN), .VALUE(1.0), .INF(0)) u_one (.y(one));
    assign y = x ? one : {(WEXP+WMAN){1'b0}};
endmodule
