"""Thin API for the hardware-agnostic high-level IR."""

from ._const import Const as Const, FloatConst as FloatConst, IntConst as IntConst
from ._const import const_value as const_value, make_const as make_const
from ._copy import copy_node as copy_node, rebuild as rebuild, reverse_postorder as reverse_postorder
from ._dce import eliminate_dead_code as eliminate_dead_code
from ._ir import (
    Branch as Branch,
    Hir as Hir,
    HirBuilder as HirBuilder,
    InPort as InPort,
    Jump as Jump,
    Node as Node,
    Operation as Operation,
    Phi as Phi,
    Ret as Ret,
    StateRead as StateRead,
    Terminator as Terminator,
    references as references,
)
from ._scaling import Scaling as Scaling, scaling_of as scaling_of
from ._operators import (
    BoolAnd as BoolAnd,
    BoolNot as BoolNot,
    BoolOr as BoolOr,
    BoolSelect as BoolSelect,
    BoolToFloat as BoolToFloat,
    BoolToInt as BoolToInt,
    BoolXor as BoolXor,
    FloatAbs as FloatAbs,
    FloatAdd as FloatAdd,
    FloatAtan2 as FloatAtan2,
    FloatAtan2Turns as FloatAtan2Turns,
    FloatComparison as FloatComparison,
    FloatCos as FloatCos,
    FloatCosTurns as FloatCosTurns,
    FloatDiv as FloatDiv,
    FloatExp2 as FloatExp2,
    FloatFma as FloatFma,
    FloatHypot as FloatHypot,
    FloatILog2 as FloatILog2,
    FloatIsFinite as FloatIsFinite,
    FloatIsInf as FloatIsInf,
    FloatIsNegInf as FloatIsNegInf,
    FloatIsPosInf as FloatIsPosInf,
    FloatLog2 as FloatLog2,
    FloatMax as FloatMax,
    FloatMin as FloatMin,
    FloatMul as FloatMul,
    FloatMulPow2 as FloatMulPow2,
    FloatMulPow2Dynamic as FloatMulPow2Dynamic,
    FloatNeg as FloatNeg,
    FloatRounding as FloatRounding,
    FloatSelect as FloatSelect,
    FloatSin as FloatSin,
    FloatSinTurns as FloatSinTurns,
    FloatSqrt as FloatSqrt,
    FloatToBool as FloatToBool,
    FloatToInt as FloatToInt,
    IntAbs as IntAbs,
    IntAdd as IntAdd,
    IntBwAnd as IntBwAnd,
    IntBwNot as IntBwNot,
    IntBwOr as IntBwOr,
    IntBwXor as IntBwXor,
    IntComparison as IntComparison,
    IntDivFloor as IntDivFloor,
    IntMod as IntMod,
    IntMul as IntMul,
    IntMulPow2 as IntMulPow2,
    IntNeg as IntNeg,
    IntPopcount as IntPopcount,
    IntSelect as IntSelect,
    IntShiftLeft as IntShiftLeft,
    IntShiftRight as IntShiftRight,
    IntSub as IntSub,
    IntToBool as IntToBool,
    IntToFloat as IntToFloat,
    NoNumber as NoNumber,
    Operator as Operator,
    Rounding as Rounding,
)
from ._optimize import optimize as optimize
from .._util import Relation as Relation
from ._types import (
    BoolType as BoolType,
    FloatType as FloatType,
    IntType as IntType,
    Type as Type,
)
