"""
Out-of-context (OOC) measurement-wrapper generator for Holoso-generated modules.

A Holoso kernel can carry hundreds to thousands of data IO bits, which do not map to the pins of most parts.
This wrapper reduces the primary IO to a single input word plus an input selector and a single output word plus an
output selector (control signals pass through un-muxed), so the design fits real device pins.

Why a mux and not a fan-out from one shared pin or tied constants: either of those would let the synthesizer
constant-propagate / CSE through the datapath and collapse the very circuit we are trying to measure.
The boundary registers (marked keep/syn_preserve/dont_touch) also make the reported f_max a register-to-register limit:
r_in -> DUT -> r_out.

Reset strategy follows the project convention: only the control/validity registers are reset; the datapath
registers are reset-unconditional.
"""

from dataclasses import dataclass

from holoso.result import Port, SynthesisResult

# Marks the boundary flops so synthesis keeps them as real register-to-register IO boundaries.
KEEP_ATTR = '(* keep = "true", syn_preserve = "true", dont_touch = "true" *)'

_ERR_CYC = "err_cyc"


@dataclass(frozen=True, slots=True)
class WordSlot:
    """One DUT data port mapped to a value of the input or output selector."""

    selector: int
    port_name: str  # the DUT port: "in_<name>", "out_<...>", or "err_cyc"
    width: int


@dataclass(frozen=True, slots=True)
class OocWrapper:
    """A portable, pin-bounded measurement wrapper around a Holoso-generated module."""

    top: str
    dut_module: str
    verilog: str
    io_in_width: int  # W: max data-input width; 0 when the kernel has no data inputs
    io_out_width: int  # W_out: max over data outputs and err_cyc
    in_sel_width: int  # ceil(log2 N_inputs); 0 when there are 0 or 1 data inputs
    out_sel_width: int  # ceil(log2 N_output_slots); 0 when there is a single output slot
    inputs: list[WordSlot]  # selector -> DUT data input
    outputs: list[WordSlot]  # selector -> DUT data output / err_cyc

    @property
    def primary_io_bits(self) -> int:
        """Bounded primary-IO bit count: the two data words, the two selectors, and the 6 control bits."""
        return self.io_in_width + self.io_out_width + self.in_sel_width + self.out_sel_width + 6


def _sel_width(count: int) -> int:
    return max(0, (count - 1).bit_length()) if count > 0 else 0


def _decl(width: int) -> str:
    """Vector range prefix for a declaration; empty for a 1-bit signal."""
    return f"[{width - 1}:0] " if width > 1 else ""


def _zext(reg: str, width: int, target: int) -> str:
    if width >= target:
        return reg
    return f"{{{{{target - width}{{1'b0}}}}, {reg}}}"


def _find_err_cyc(result: SynthesisResult) -> Port:
    for port in result.interface.control_ports:
        if port.name == _ERR_CYC:
            return port
    raise ValueError(f"module {result.module_name!r} has no err_cyc port; cannot build an OOC wrapper")


def build_ooc_wrapper(result: SynthesisResult, *, top_suffix: str = "_ooc") -> OocWrapper:
    """Generate a mux-reduced OOC measurement wrapper for ``result``'s generated module."""
    iface = result.interface
    data_inputs = iface.input_ports
    data_outputs = iface.output_ports
    err_cyc = _find_err_cyc(result)

    in_slots = [WordSlot(i, p.name, p.width) for i, p in enumerate(data_inputs)]
    out_ports = (*data_outputs, err_cyc)
    out_slots = [WordSlot(k, p.name, p.width) for k, p in enumerate(out_ports)]

    io_in_width = max((p.width for p in data_inputs), default=0)
    io_out_width = max(p.width for p in out_ports)
    in_sel_width = _sel_width(len(in_slots))
    out_sel_width = _sel_width(len(out_slots))

    top = f"{result.module_name}{top_suffix}"
    verilog = _render(
        top=top,
        dut=result.module_name,
        in_slots=in_slots,
        out_slots=out_slots,
        io_in_width=io_in_width,
        io_out_width=io_out_width,
        in_sel_width=in_sel_width,
        out_sel_width=out_sel_width,
    )
    return OocWrapper(
        top=top,
        dut_module=result.module_name,
        verilog=verilog,
        io_in_width=io_in_width,
        io_out_width=io_out_width,
        in_sel_width=in_sel_width,
        out_sel_width=out_sel_width,
        inputs=in_slots,
        outputs=out_slots,
    )


def _render(
    *,
    top: str,
    dut: str,
    in_slots: list[WordSlot],
    out_slots: list[WordSlot],
    io_in_width: int,
    io_out_width: int,
    in_sel_width: int,
    out_sel_width: int,
) -> str:
    has_inputs = len(in_slots) > 0
    lines: list[str] = [
        "`default_nettype none",
        "",
        f"// OUT-OF-CONTEXT MEASUREMENT HARNESS for {dut} -- generated by synth/_ooc.py for FPGA f_max/area",
        "// evaluation only. Not a deliverable module and not part of the holoso package. Every DUT data IO is",
        "// registered behind a runtime-selected bank so the optimizer cannot collapse the datapath; the reported",
        "// f_max is the DUT register-to-register limit.",
        f"module {top} (",
    ]

    # ---- port list -------------------------------------------------------------------------------------------------
    ports = [
        "input  wire clk",
        "input  wire rst",
        "input  wire in_valid",
        "input  wire out_ready",
        "output wire in_ready",
        "output wire out_valid",
    ]
    if has_inputs:
        ports.append(f"input  wire {_decl(io_in_width)}io_in")
        if in_sel_width > 0:
            ports.append(f"input  wire {_decl(in_sel_width)}in_sel")
    ports.append(f"output wire {_decl(io_out_width)}io_out")
    if out_sel_width > 0:
        ports.append(f"input  wire {_decl(out_sel_width)}out_sel")
    lines.extend(f"    {port}," for port in ports[:-1])
    lines.append(f"    {ports[-1]}")
    lines.append(");")

    # ---- declarations ----------------------------------------------------------------------------------------------
    lines += [
        "    // Control/validity boundary registers (the only reset-bearing registers in this wrapper).",
        f"    {KEEP_ATTR} reg r_in_valid;",
        f"    {KEEP_ATTR} reg r_out_ready;",
        f"    {KEEP_ATTR} reg r_in_ready;",
        f"    {KEEP_ATTR} reg r_out_valid;",
        "",
    ]
    if has_inputs:
        lines.append("    // Input bank: one register per DUT data input, loaded only when the selector addresses it.")
        lines += [f"    {KEEP_ATTR} reg {_decl(s.width)}r_{s.port_name};" for s in in_slots]
        lines.append("")
    lines.append("    // DUT outputs, captured at the boundary, then muxed onto the single output word.")
    lines.append("    wire dut_in_ready;")
    lines.append("    wire dut_out_valid;")
    lines += [f"    wire {_decl(s.width)}dut_{s.port_name};" for s in out_slots]
    lines += [f"    {KEEP_ATTR} reg {_decl(s.width)}r_{s.port_name};" for s in out_slots]
    lines.append(f"    {KEEP_ATTR} reg {_decl(io_out_width)}r_io_out;")
    lines += [
        "",
        "    assign in_ready  = r_in_ready;",
        "    assign out_valid = r_out_valid;",
        "    assign io_out    = r_io_out;",
        "",
    ]

    # ---- DUT instance ----------------------------------------------------------------------------------------------
    conns = [
        ".clk(clk)",
        ".rst(rst)",
        ".in_valid(r_in_valid)",
        ".in_ready(dut_in_ready)",
        ".out_valid(dut_out_valid)",
        ".out_ready(r_out_ready)",
    ]
    conns += [f".{s.port_name}(r_{s.port_name})" for s in in_slots]
    conns += [f".{s.port_name}(dut_{s.port_name})" for s in out_slots]
    lines.append(f"    {dut} dut (")
    lines.extend(f"        {conn}," for conn in conns[:-1])
    lines.append(f"        {conns[-1]}")
    lines.append("    );")
    lines.append("")

    # ---- control always block (reset-bearing) ----------------------------------------------------------------------
    lines += [
        "    always @(posedge clk) begin",
        "        if (rst) begin",
        "            r_in_valid  <= 1'b0;",
        "            r_out_ready <= 1'b0;",
        "            r_in_ready  <= 1'b0;",
        "            r_out_valid <= 1'b0;",
        "        end else begin",
        "            r_in_valid  <= in_valid;",
        "            r_out_ready <= out_ready;",
        "            r_in_ready  <= dut_in_ready;",
        "            r_out_valid <= dut_out_valid;",
        "        end",
        "    end",
        "",
    ]

    # ---- datapath always block (reset-unconditional) --------------------------------------------------------------
    lines.append("    always @(posedge clk) begin")
    lines += _input_load_lines(in_slots, in_sel_width)
    lines += [f"        r_{s.port_name} <= dut_{s.port_name};" for s in out_slots]
    lines += _output_mux_lines(out_slots, out_sel_width, io_out_width)
    lines.append("    end")

    lines += ["endmodule", "", "`default_nettype wire", ""]
    return "\n".join(lines)


def _input_load_lines(in_slots: list[WordSlot], in_sel_width: int) -> list[str]:
    if not in_slots:
        return []
    if in_sel_width == 0:
        only = in_slots[0]
        return [f"        r_{only.port_name} <= io_in[{only.width - 1}:0];"]
    out = ["        case (in_sel)"]
    for s in in_slots:
        out.append(f"            {in_sel_width}'d{s.selector}: r_{s.port_name} <= io_in[{s.width - 1}:0];")
    out += ["            default: ;", "        endcase"]
    return out


def _output_mux_lines(out_slots: list[WordSlot], out_sel_width: int, io_out_width: int) -> list[str]:
    if out_sel_width == 0:
        only = out_slots[0]
        return [f"        r_io_out <= {_zext(f'r_{only.port_name}', only.width, io_out_width)};"]
    out = ["        case (out_sel)"]
    for s in out_slots:
        out.append(
            f"            {out_sel_width}'d{s.selector}: r_io_out <= {_zext(f'r_{s.port_name}', s.width, io_out_width)};"
        )
    out += [
        f"            default: r_io_out <= {_zext(f'r_{out_slots[0].port_name}', out_slots[0].width, io_out_width)};",
        "        endcase",
    ]
    return out
