#!/usr/bin/env python3
"""
Maintenance utility: vendor third-party HDL into the backend's rtl/ tree.

Holoso ships a single self-contained support library assembled from the hand-written wrappers plus the upstream HDL
primitives they instantiate. Rather than carrying upstream HDL as git submodules, we vendor a verbatim copy; this
script refreshes it. Each origin lands in its own destination subdirectory, so ownership is the subdirectory:
refreshing replaces exactly that subtree. A README.md beside the files records provenance and the upstream license;
the support-library builder globs all RTL files and stitches them all together.
"""

import shutil
import subprocess
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
BACKEND = REPO_ROOT / "holoso" / "_backend"


@dataclass(frozen=True, slots=True)
class Origin:
    remote: str
    ref: str
    source: str
    destination: Path


_ORIGINS = [
    Origin(
        remote="https://github.com/Zubax/kulibin",
        ref="dev",
        source="float/hdl",
        destination=BACKEND / "verilog" / "rtl" / "kulibin",
    ),
]


def _git(args: list[str], cwd: Path) -> str:
    return subprocess.run(["git", *args], cwd=cwd, check=True, capture_output=True, text=True).stdout.strip()


def _license(clone: Path) -> str:
    for candidate in ("LICENSE", "LICENSE.txt", "LICENSE.md", "COPYING"):
        if (clone / candidate).is_file():
            return (clone / candidate).read_text(encoding="utf-8", errors="replace").strip()
    return ""


def _readme(origin: Origin, commit: str, commit_date: str, license_text: str) -> str:
    lines = [
        f"# {origin.destination.name}",
        "",
        f"AUTO-GENERATED by `{sys.argv[0]}`. Do not edit by hand; refresh by re-running the script.",
        "",
        f"- Origin: <{origin.remote}>",
        f"- Ref: `{origin.ref}`",
        f"- Commit: `{commit}` ({commit_date})",
        f"- Source: `{origin.source}`",
        "",
    ]
    if license_text:
        lines += ["## License", "", license_text, ""]
    return "\n".join(lines)


def update(origin: Origin) -> None:
    with tempfile.TemporaryDirectory(prefix="holoso_vendor_") as tmp:
        clone = Path(tmp) / "src"
        print(f"Cloning {origin.remote} @ {origin.ref} ...")
        subprocess.run(["git", "clone", "--depth", "1", "--branch", origin.ref, origin.remote, str(clone)], check=True)
        commit = _git(["rev-parse", "HEAD"], clone)
        commit_date = _git(["log", "-1", "--format=%cI"], clone)
        license_text = _license(clone)
        root = clone / origin.source
        files = sorted(root.rglob("*.v"))
        assert files, f"no .v files under {origin.source!r} in {origin.remote}"

        # Replace the destination subtree wholesale so files that vanished upstream are dropped.
        if origin.destination.exists():
            shutil.rmtree(origin.destination)
        for path in files:
            target = origin.destination / path.relative_to(root)
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copyfile(path, target)
        (origin.destination / "README.md").write_text(
            _readme(origin, commit, commit_date, license_text), encoding="utf-8"
        )
    print(f"Vendored {len(files)} files into {origin.destination.relative_to(REPO_ROOT)} (commit {commit[:12]})")


def main() -> int:
    for origin in _ORIGINS:
        update(origin)
    return 0


if __name__ == "__main__":
    sys.exit(main())
