name: CI

on:
  push:
  pull_request:

jobs:
  nox:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/zubax/zubax-fpga-toolchain:latest
      options: --user root
    env:
      COCOTB_IGNORE_PYTHON_REQUIRES: "1"
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Run nox
        run: nox
